import { eq, and } from "drizzle-orm";
import {
  db,
  campaignCreativesTable,
  contentPiecesTable,
  mediaBriefsTable,
} from "@workspace/db";
import type { Logger } from "pino";
import { emitCampaignEvent } from "../realtime/realtime.service.js";

interface ImageConcept {
  conceptId?: string;
  title?: string;
  format?: string;
  colorPalette?: string[];
  mood?: string;
  visualElements?: string[];
  typography?: string;
  textOverlay?: string;
  composition?: string;
  lightingStyle?: string;
  phase?: string;
  dayIndex?: number;
}

type DalleSize = "1024x1024" | "1792x1024" | "1024x1792";
type CreativeFormat = "feed_square" | "feed_portrait" | "stories" | "banner" | "carousel_slide";

const FORMAT_MAP: Record<string, CreativeFormat> = {
  square_1x1: "feed_square",
  portrait_4x5: "feed_portrait",
  story_9x16: "stories",
  landscape_16x9: "banner",
  banner: "banner",
  thumbnail: "feed_square",
};

function mapFormat(raw: string | undefined): CreativeFormat {
  if (!raw) return "feed_square";
  return FORMAT_MAP[raw] ?? "feed_square";
}

function buildDallePrompt(concept: ImageConcept, productName: string): string {
  const elements = concept.visualElements?.join(", ") ?? "";
  const palette = concept.colorPalette?.join(", ") ?? "";
  const mood = concept.mood ?? "professional, high-energy";
  const composition = concept.composition ?? "clean, balanced";
  const lighting = concept.lightingStyle ?? "studio lighting";
  const phase = concept.phase ?? "";

  return [
    `High-quality advertising photography for ${productName} digital product launch${phase ? ` (${phase} phase)` : ""}.`,
    mood ? `Mood: ${mood}.` : "",
    elements ? `Visual elements: ${elements}.` : "",
    palette ? `Color palette inspiration: ${palette}.` : "",
    `Composition: ${composition}. ${lighting}.`,
    "NO text, letters, words, logos or watermarks visible in the image.",
    "Ultra realistic, cinematic quality, 4K resolution.",
  ].filter(Boolean).join(" ");
}

async function generateCreativeFromConcept(
  campaignId: string,
  workspaceId: string,
  concept: ImageConcept,
  productName: string,
  log: Logger,
): Promise<string | null> {
  const format = mapFormat(concept.format);
  const dallePrompt = buildDallePrompt(concept, productName);

  const [creative] = await db
    .insert(campaignCreativesTable)
    .values({
      campaignId,
      workspaceId,
      status: "concept_ready",
      platform: "universal" as const,
      format,
      requestNote: concept.title ?? null,
      concept: {
        headline: concept.title ?? "Visual do Lançamento",
        subHeadline: concept.phase ?? "",
        visualDescription: concept.composition ?? "",
        colorPalette: concept.colorPalette ?? [],
        cta: "",
        mentalTrigger: "authority",
        angle: concept.mood ?? "",
        mood: concept.mood ?? "professional",
        platform: "universal",
        format,
        dallePrompt,
        rationale: `Auto-gerado a partir do briefing de mídia aprovado. Fase: ${concept.phase ?? "geral"}`,
      },
      prompt: dallePrompt,
      metadata: { autoGenerated: true, conceptId: concept.conceptId, phase: concept.phase },
    })
    .returning();

  log.info({ campaignId, creativeId: creative?.id, format }, "Auto-generated creative concept from media brief");
  return creative?.id ?? null;
}

// ─── Visual generation for a specific content piece ──────────────────────────

interface PieceVisualResult {
  creativeId: string;
  dallePrompt: string;
  conceptTitle: string;
}

/**
 * Generates a DALL-E concept (not the image itself) for a specific social-media
 * content piece.  The concept is stored in campaignCreativesTable with
 * metadata.contentPieceId so that approvePreviewAndGenerateFinal can link back.
 *
 * Steps:
 *  1. Load the content piece (caption / body).
 *  2. Load creative_direction for global style guide.
 *  3. Build DALL-E prompt from copy context.
 *  4. Insert concept_ready creative row.
 */
export async function generateVisualForPiece(
  campaignId: string,
  workspaceId: string,
  pieceId: string,
  log: Logger,
): Promise<PieceVisualResult> {
  // Load the piece
  const [piece] = await db
    .select()
    .from(contentPiecesTable)
    .where(and(eq(contentPiecesTable.id, pieceId), eq(contentPiecesTable.campaignId, campaignId)))
    .limit(1);

  if (!piece) throw new Error("Peça de conteúdo não encontrada");

  // Load creative_direction for style guide
  const [directionPiece] = await db
    .select({ content: contentPiecesTable.content })
    .from(contentPiecesTable)
    .where(
      and(
        eq(contentPiecesTable.campaignId, campaignId),
        eq(contentPiecesTable.type, "creative_direction" as any),
        eq(contentPiecesTable.status, "approved"),
      ),
    )
    .limit(1);

  const direction = (directionPiece?.content as Record<string, unknown>) ?? {};
  const mood         = String(direction["moodWords"] ? (direction["moodWords"] as string[]).slice(0, 3).join(", ") : "professional, high-energy, aspirational");
  const colorPalette = Array.isArray(direction["colorPalette"]) ? (direction["colorPalette"] as string[]).slice(0, 4) : [];
  const visualStyle  = String(direction["visualStyle"] ?? direction["coreMessage"] ?? "cinematic, digital product");

  // Extract caption from piece content
  const contentObj = (piece.content && typeof piece.content === "object") ? piece.content as Record<string, unknown> : {};
  const caption = String(
    contentObj["caption"] ?? contentObj["body"] ?? contentObj["text"] ?? contentObj["copy"] ?? "",
  ).slice(0, 300);

  // Read platform from piece content JSONB (social_media agent stores it there)
  const contentForPlatform = (piece.content && typeof piece.content === "object") ? piece.content as Record<string, unknown> : {};
  const platformsArr = Array.isArray(contentForPlatform["platforms"]) ? (contentForPlatform["platforms"] as unknown[])[0] : undefined;
  const platform    = String(contentForPlatform["platform"] ?? platformsArr ?? "instagram");
  const dayIndex    = typeof piece.dayIndex === "number" ? piece.dayIndex : 0;
  const launchPhase = piece.launchPhase ?? piece.phase ?? "geral";

  const productName = "Produto"; // prompt still useful even without exact product name

  // Build DALL-E prompt from context
  const paletteStr  = colorPalette.length ? `Color palette: ${colorPalette.join(", ")}.` : "";
  const dallePrompt = [
    `High-quality social media advertising photography for a digital product launch (${platform}, day ${dayIndex}, ${launchPhase} phase).`,
    `Mood: ${mood}. ${visualStyle}.`,
    paletteStr,
    caption ? `Caption context: "${caption.slice(0, 120)}"` : "",
    "Composition: clean, modern, aspirational. Studio-quality lighting.",
    "NO text, letters, words, logos or watermarks in the image.",
    "Ultra realistic, cinematic 4K quality.",
  ].filter(Boolean).join(" ");

  const conceptTitle = `Visual ${platform} — Dia ${dayIndex} (${launchPhase})`;

  const formatMap: Record<string, string> = {
    instagram: "feed_portrait",
    tiktok: "stories",
    facebook: "feed_square",
  };
  const format = formatMap[platform] ?? "feed_square";

  const [creative] = await db
    .insert(campaignCreativesTable)
    .values({
      campaignId,
      workspaceId,
      status: "concept_ready",
      platform: "universal" as const,
      format: format as any,
      requestNote: conceptTitle,
      concept: {
        headline: conceptTitle,
        subHeadline: launchPhase,
        visualDescription: dallePrompt,
        colorPalette,
        cta: "",
        mentalTrigger: "authority",
        angle: caption.slice(0, 80),
        mood,
        platform,
        format,
        dallePrompt,
        rationale: `Auto-gerado a partir da peça de conteúdo aprovada. Plataforma: ${platform}. Dia ${dayIndex}.`,
      },
      prompt: dallePrompt,
      metadata: {
        autoGenerated: true,
        contentPieceId: pieceId,
        platform,
        dayIndex,
        launchPhase,
        productName,
      },
    })
    .returning();

  if (!creative) throw new Error("Falha ao criar conceito criativo");

  log.info({ campaignId, pieceId, creativeId: creative.id, platform }, "Visual concept created for content piece");

  emitCampaignEvent({
    campaignId,
    type: "agent_completed",
    agentType: "media_brief",
    message: `Conceito visual criado para ${platform} (Dia ${dayIndex}) — aguardando aprovação para gerar preview com DALL-E 3`,
    data: { creativeId: creative.id, pieceId },
    timestamp: new Date().toISOString(),
  });

  return { creativeId: creative.id, dallePrompt, conceptTitle };
}

export async function autoGenerateCreativesFromBrief(
  campaignId: string,
  workspaceId: string,
  pieceId: string,
  log: Logger,
): Promise<void> {
  try {
    const [piece] = await db
      .select()
      .from(contentPiecesTable)
      .where(and(eq(contentPiecesTable.id, pieceId), eq(contentPiecesTable.campaignId, campaignId)))
      .limit(1);

    if (!piece || piece.type !== "media_brief") return;

    const content = piece.content as Record<string, unknown>;
    const imageConcepts = (content["imageConcepts"] as ImageConcept[] | undefined) ?? [];
    const productName = (content["campaignTitle"] as string | undefined) ?? "Produto";

    if (!imageConcepts.length) return;

    emitCampaignEvent({
      campaignId,
      type: "agent_started",
      agentType: "media_brief",
      message: `Briefing de mídia aprovado — iniciando geração automática de ${imageConcepts.length} criativos visuais...`,
      timestamp: new Date().toISOString(),
    });

    const createdIds: string[] = [];

    for (const concept of imageConcepts.slice(0, 8)) {
      try {
        const id = await generateCreativeFromConcept(campaignId, workspaceId, concept, productName, log);
        if (id) createdIds.push(id);

        emitCampaignEvent({
          campaignId,
          type: "agent_thinking",
          agentType: "media_brief",
          message: `Criativo "${concept.title ?? concept.phase ?? "visual"}" criado — aguardando aprovação para gerar imagem`,
          timestamp: new Date().toISOString(),
        });
      } catch (err) {
        log.warn({ err, conceptId: concept.conceptId }, "Failed to create creative from concept — skipping");
      }
    }

    emitCampaignEvent({
      campaignId,
      type: "agent_completed",
      agentType: "media_brief",
      message: `${createdIds.length} conceitos de criativos criados. Acesse Criativos para aprovar e gerar as imagens com DALL-E 3.`,
      data: { createdCreativeIds: createdIds },
      timestamp: new Date().toISOString(),
    });

    log.info({ campaignId, count: createdIds.length }, "Auto-generated creatives from approved media brief");
  } catch (err) {
    log.warn({ err, campaignId, pieceId }, "autoGenerateCreativesFromBrief failed — non-blocking");
  }
}
