-- Fail-closed interaction governance. This migration only creates storage; it does not enable or publish anything.
DO $$ BEGIN CREATE TYPE "interaction_lifecycle" AS ENUM ('observed','scored','proposed','awaiting_approval','approved','scheduled','executing','verified','responded','failed','blocked','cancelled'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE "interaction_action" AS ENUM ('public_comment','private_message','reply','follow_up'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE "interaction_decision" AS ENUM ('allowed','blocked','requires_approval'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "interaction_governance_policies" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL, "workspace_id" uuid NOT NULL REFERENCES "workspaces"("id") ON DELETE cascade, "enabled" boolean NOT NULL DEFAULT false, "window_minutes" integer NOT NULL DEFAULT 1440, "workspace_ceiling" integer NOT NULL DEFAULT 0, "account_ceiling" integer NOT NULL DEFAULT 0, "competitor_ceiling" integer NOT NULL DEFAULT 0, "post_ceiling" integer NOT NULL DEFAULT 0, "recipient_ceiling" integer NOT NULL DEFAULT 0, "recipient_cooldown_minutes" integer NOT NULL DEFAULT 10080, "maximum_risk_score" integer NOT NULL DEFAULT 0, "require_approval" boolean NOT NULL DEFAULT true, "purpose" text NOT NULL DEFAULT 'public engagement', "jurisdiction_codes" jsonb NOT NULL DEFAULT '[]'::jsonb, "retention_days" integer NOT NULL DEFAULT 30, "created_at" timestamp with time zone NOT NULL DEFAULT now(), "updated_at" timestamp with time zone NOT NULL DEFAULT now());
CREATE UNIQUE INDEX IF NOT EXISTS "interaction_policy_workspace_uidx" ON "interaction_governance_policies" ("workspace_id");
CREATE TABLE IF NOT EXISTS "interaction_platform_capabilities" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL, "workspace_id" uuid NOT NULL REFERENCES "workspaces"("id") ON DELETE cascade, "integration_id" uuid NOT NULL REFERENCES "workspace_integrations"("id") ON DELETE cascade, "platform" text NOT NULL, "action" "interaction_action" NOT NULL, "official_adapter" boolean NOT NULL DEFAULT false, "enabled" boolean NOT NULL DEFAULT false, "allows_automatic_execution" boolean NOT NULL DEFAULT false, "requires_owned_asset" boolean NOT NULL DEFAULT true, "created_at" timestamp with time zone NOT NULL DEFAULT now(), "updated_at" timestamp with time zone NOT NULL DEFAULT now());
CREATE UNIQUE INDEX IF NOT EXISTS "interaction_capability_integration_action_uidx" ON "interaction_platform_capabilities" ("integration_id","action");
CREATE INDEX IF NOT EXISTS "interaction_capability_workspace_idx" ON "interaction_platform_capabilities" ("workspace_id");
CREATE TABLE IF NOT EXISTS "interaction_recipients" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL, "workspace_id" uuid NOT NULL REFERENCES "workspaces"("id") ON DELETE cascade, "fingerprint" text NOT NULL, "opted_out" boolean NOT NULL DEFAULT false, "opted_out_at" timestamp with time zone, "purpose" text NOT NULL DEFAULT 'public engagement', "jurisdiction_codes" jsonb NOT NULL DEFAULT '[]'::jsonb, "retention_until" timestamp with time zone, "created_at" timestamp with time zone NOT NULL DEFAULT now(), "updated_at" timestamp with time zone NOT NULL DEFAULT now());
CREATE UNIQUE INDEX IF NOT EXISTS "interaction_recipient_workspace_fingerprint_uidx" ON "interaction_recipients" ("workspace_id","fingerprint");
CREATE TABLE IF NOT EXISTS "interaction_opportunities" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL, "workspace_id" uuid NOT NULL REFERENCES "workspaces"("id") ON DELETE cascade, "campaign_id" uuid REFERENCES "campaigns"("id") ON DELETE set null, "recipient_id" uuid NOT NULL REFERENCES "interaction_recipients"("id") ON DELETE cascade, "integration_id" uuid NOT NULL REFERENCES "workspace_integrations"("id") ON DELETE cascade, "platform" text NOT NULL, "action" "interaction_action" NOT NULL, "competitor_ref" text, "post_ref" text, "evidence" jsonb NOT NULL DEFAULT '{}'::jsonb, "context" jsonb NOT NULL DEFAULT '{}'::jsonb, "lawful_basis" text NOT NULL DEFAULT 'unknown', "contactable" boolean NOT NULL DEFAULT false, "asset_owned" boolean NOT NULL DEFAULT false, "conversation_owned" boolean NOT NULL DEFAULT false, "risk_score" integer NOT NULL DEFAULT 100, "state" "interaction_lifecycle" NOT NULL DEFAULT 'observed', "created_at" timestamp with time zone NOT NULL DEFAULT now(), "updated_at" timestamp with time zone NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS "interaction_opportunity_workspace_state_idx" ON "interaction_opportunities" ("workspace_id","state","created_at"); CREATE INDEX IF NOT EXISTS "interaction_opportunity_recipient_idx" ON "interaction_opportunities" ("workspace_id","recipient_id","created_at");
CREATE TABLE IF NOT EXISTS "interaction_decisions" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL, "workspace_id" uuid NOT NULL REFERENCES "workspaces"("id") ON DELETE cascade, "opportunity_id" uuid NOT NULL REFERENCES "interaction_opportunities"("id") ON DELETE cascade, "decision" "interaction_decision" NOT NULL, "reasons" jsonb NOT NULL DEFAULT '[]'::jsonb, "governor_snapshot" jsonb NOT NULL DEFAULT '{}'::jsonb, "created_at" timestamp with time zone NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS "interaction_drafts" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL, "workspace_id" uuid NOT NULL REFERENCES "workspaces"("id") ON DELETE cascade, "opportunity_id" uuid NOT NULL REFERENCES "interaction_opportunities"("id") ON DELETE cascade, "content" text NOT NULL, "content_fingerprint" text NOT NULL, "cta_level" integer NOT NULL DEFAULT 0, "council_assessment" jsonb NOT NULL DEFAULT '{}'::jsonb, "similarity_score" integer NOT NULL DEFAULT 0, "state" "interaction_lifecycle" NOT NULL DEFAULT 'proposed', "created_at" timestamp with time zone NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS "interaction_draft_workspace_fingerprint_idx" ON "interaction_drafts" ("workspace_id","content_fingerprint");
CREATE TABLE IF NOT EXISTS "interaction_approvals" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL, "workspace_id" uuid NOT NULL REFERENCES "workspaces"("id") ON DELETE cascade, "draft_id" uuid NOT NULL REFERENCES "interaction_drafts"("id") ON DELETE cascade, "decision" text NOT NULL, "modified_content" text, "decided_by_user_id" uuid, "reason" text, "created_at" timestamp with time zone NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS "interaction_executions" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL, "workspace_id" uuid NOT NULL REFERENCES "workspaces"("id") ON DELETE cascade, "opportunity_id" uuid NOT NULL REFERENCES "interaction_opportunities"("id") ON DELETE cascade, "draft_id" uuid REFERENCES "interaction_drafts"("id") ON DELETE set null, "mode" text NOT NULL, "state" "interaction_lifecycle" NOT NULL DEFAULT 'scheduled', "evidence" jsonb NOT NULL DEFAULT '{}'::jsonb, "result" jsonb NOT NULL DEFAULT '{}'::jsonb, "incident" jsonb, "reserved_at" timestamp with time zone NOT NULL DEFAULT now(), "completed_at" timestamp with time zone);
CREATE INDEX IF NOT EXISTS "interaction_execution_workspace_time_idx" ON "interaction_executions" ("workspace_id","reserved_at");