-- Development-only migration. Production schema changes remain Publish-managed.
DO $$ BEGIN CREATE TYPE "radar_package" AS ENUM ('RADAR_ESSENTIAL','RADAR_PRO','RADAR_SCALE','WAR_ROOM'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE "radar_subscription_status" AS ENUM ('pending','active','cancelled','expired'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE "radar_billing_currency" AS ENUM ('BRL','USD'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE "radar_usage_dimension" AS ENUM ('light_scan','detailed_scan','council_run','monitored_campaign','competitor','region'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE "radar_purchase_request_status" AS ENUM ('pending_sales','cancelled','activated'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "radar_subscriptions" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL, "workspace_id" uuid NOT NULL REFERENCES "workspaces"("id") ON DELETE cascade, "package" "radar_package" NOT NULL, "currency" "radar_billing_currency" NOT NULL, "status" "radar_subscription_status" NOT NULL DEFAULT 'pending', "period_starts_at" timestamp with time zone NOT NULL, "period_ends_at" timestamp with time zone NOT NULL, "window_starts_at" timestamp with time zone, "window_ends_at" timestamp with time zone, "limits_snapshot" jsonb NOT NULL, "activated_by_user_id" uuid, "cancelled_at" timestamp with time zone, "created_at" timestamp with time zone NOT NULL DEFAULT now(), "updated_at" timestamp with time zone NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS "radar_subscriptions_workspace_status_idx" ON "radar_subscriptions" ("workspace_id","status","period_ends_at");
CREATE INDEX IF NOT EXISTS "radar_subscriptions_workspace_window_idx" ON "radar_subscriptions" ("workspace_id","window_ends_at");
CREATE TABLE IF NOT EXISTS "radar_usage_ledger" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL, "workspace_id" uuid NOT NULL REFERENCES "workspaces"("id") ON DELETE cascade, "subscription_id" uuid REFERENCES "radar_subscriptions"("id") ON DELETE set null, "dimension" "radar_usage_dimension" NOT NULL, "quantity" integer NOT NULL DEFAULT 1, "campaign_id" uuid, "idempotency_key" text NOT NULL, "period_starts_at" timestamp with time zone NOT NULL, "period_ends_at" timestamp with time zone NOT NULL, "metadata" jsonb NOT NULL DEFAULT '{}'::jsonb, "created_at" timestamp with time zone NOT NULL DEFAULT now());
CREATE UNIQUE INDEX IF NOT EXISTS "radar_usage_workspace_idempotency_uidx" ON "radar_usage_ledger" ("workspace_id","idempotency_key");
CREATE INDEX IF NOT EXISTS "radar_usage_workspace_dimension_period_idx" ON "radar_usage_ledger" ("workspace_id","dimension","period_starts_at");
CREATE TABLE IF NOT EXISTS "radar_purchase_requests" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL, "workspace_id" uuid NOT NULL REFERENCES "workspaces"("id") ON DELETE cascade, "package" "radar_package" NOT NULL, "currency" "radar_billing_currency" NOT NULL, "status" "radar_purchase_request_status" NOT NULL DEFAULT 'pending_sales', "requested_by_user_id" uuid, "notes" text, "idempotency_key" text NOT NULL, "created_at" timestamp with time zone NOT NULL DEFAULT now(), "updated_at" timestamp with time zone NOT NULL DEFAULT now());
CREATE UNIQUE INDEX IF NOT EXISTS "radar_purchase_request_workspace_key_uidx" ON "radar_purchase_requests" ("workspace_id","idempotency_key");
CREATE INDEX IF NOT EXISTS "radar_purchase_request_workspace_status_idx" ON "radar_purchase_requests" ("workspace_id","status");