-- Durable community inbox, moderation and provider-action audit records.
-- Provider mutations are deliberately not represented as successful by this migration.
DO $$ BEGIN CREATE TYPE "community_channel" AS ENUM ('whatsapp','telegram','instagram','facebook'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE "community_message_direction" AS ENUM ('inbound','outbound'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE "community_message_status" AS ENUM ('received','queued','sent','delivered','failed','capability_blocked'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE "community_decision" AS ENUM ('allow','queue','delete','restrict','ban','respond','capability_blocked'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE "community_attempt_status" AS ENUM ('pending','sent','succeeded','failed','capability_blocked'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
CREATE TABLE IF NOT EXISTS community_conversations (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id uuid NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE, integration_id uuid REFERENCES workspace_integrations(id) ON DELETE SET NULL, channel community_channel NOT NULL, provider_conversation_id text NOT NULL, title text, last_message_at timestamptz, metadata jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
CREATE UNIQUE INDEX IF NOT EXISTS community_conversation_provider_uidx ON community_conversations(workspace_id, channel, provider_conversation_id);
CREATE TABLE IF NOT EXISTS community_participants (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id uuid NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE, conversation_id uuid NOT NULL REFERENCES community_conversations(id) ON DELETE CASCADE, provider_participant_id text NOT NULL, display_name text, role text, consent_granted boolean NOT NULL DEFAULT false, identity_provenance text NOT NULL DEFAULT 'provider_event', metadata jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now());
CREATE UNIQUE INDEX IF NOT EXISTS community_participant_provider_uidx ON community_participants(conversation_id, provider_participant_id);
CREATE TABLE IF NOT EXISTS community_messages (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id uuid NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE, conversation_id uuid NOT NULL REFERENCES community_conversations(id) ON DELETE CASCADE, sender_participant_id uuid REFERENCES community_participants(id) ON DELETE SET NULL, provider_message_id text NOT NULL, direction community_message_direction NOT NULL, body text, attachments jsonb NOT NULL DEFAULT '[]'::jsonb, status community_message_status NOT NULL DEFAULT 'received', occurred_at timestamptz NOT NULL, metadata jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now());
CREATE UNIQUE INDEX IF NOT EXISTS community_message_provider_uidx ON community_messages(workspace_id, provider_message_id);
CREATE TABLE IF NOT EXISTS community_provider_events (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id uuid NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE, channel community_channel NOT NULL, provider_event_id text NOT NULL, payload jsonb NOT NULL, received_at timestamptz NOT NULL DEFAULT now());
CREATE UNIQUE INDEX IF NOT EXISTS community_provider_event_uidx ON community_provider_events(workspace_id, channel, provider_event_id);
CREATE TABLE IF NOT EXISTS community_moderation_rules (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id uuid NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE, channel community_channel, name text NOT NULL, enabled boolean NOT NULL DEFAULT true, condition jsonb NOT NULL, decision community_decision NOT NULL, requires_approval boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS community_moderation_decisions (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id uuid NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE, message_id uuid NOT NULL REFERENCES community_messages(id) ON DELETE CASCADE, rule_id uuid REFERENCES community_moderation_rules(id) ON DELETE SET NULL, decision community_decision NOT NULL, reason text NOT NULL, approved_by uuid, approved_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS community_action_attempts (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id uuid NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE, message_id uuid REFERENCES community_messages(id) ON DELETE SET NULL, integration_id uuid REFERENCES workspace_integrations(id) ON DELETE SET NULL, action community_decision NOT NULL, idempotency_key text NOT NULL, status community_attempt_status NOT NULL DEFAULT 'pending', provider_receipt jsonb, error text, created_at timestamptz NOT NULL DEFAULT now(), completed_at timestamptz);
CREATE UNIQUE INDEX IF NOT EXISTS community_action_idempotency_uidx ON community_action_attempts(workspace_id, idempotency_key);
CREATE TABLE IF NOT EXISTS community_response_policies (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id uuid NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE, campaign_id uuid REFERENCES campaigns(id) ON DELETE SET NULL, channel community_channel NOT NULL, enabled boolean NOT NULL DEFAULT false, requires_consent boolean NOT NULL DEFAULT true, requires_approval boolean NOT NULL DEFAULT true, daily_quota integer NOT NULL DEFAULT 0, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
ALTER TYPE group_status ADD VALUE IF NOT EXISTS 'capability_blocked';
ALTER TYPE group_status ADD VALUE IF NOT EXISTS 'sync_failed';
ALTER TABLE campaign_groups ADD COLUMN IF NOT EXISTS integration_id uuid;
ALTER TABLE campaign_groups ADD COLUMN IF NOT EXISTS lifecycle_status text NOT NULL DEFAULT 'planning';
ALTER TABLE campaign_groups ADD COLUMN IF NOT EXISTS lifecycle_error text;
ALTER TABLE campaign_groups ADD COLUMN IF NOT EXISTS last_synced_at timestamptz;