import assert from "node:assert/strict";
import { isAsaasPaidStatus, isAsaasReversalStatus } from "../modules/billing/billing.service.js";
import { isCampaignOwnedByWorkspace } from "../modules/market-intel/regional-intelligence.service.js";
import { includedRadarTrialWindow, isConfirmedNexosSubscriptionPayment, isTerminalRadarPaymentStatus, RADAR_CATALOG, radarScheduledMode, resolveRadarSubscription } from "../modules/market-intel/radar-entitlements.service.js";

const launch = new Date("2026-06-01T00:00:00.000Z");
const legacy = includedRadarTrialWindow(new Date("2021-01-01T00:00:00.000Z"), launch);
assert.equal(legacy.startsAt.toISOString(), launch.toISOString(), "legacy paid accounts begin at the commercial launch");
assert.equal(legacy.endsAt.toISOString(), "2026-08-30T00:00:00.000Z", "included trial is 90 calendar days");
const newCustomer = includedRadarTrialWindow(new Date("2026-06-15T00:00:00.000Z"), launch);
assert.equal(newCustomer.startsAt.toISOString(), "2026-06-15T00:00:00.000Z");
assert.equal(newCustomer.endsAt.toISOString(), "2026-09-13T00:00:00.000Z");
const withoutOfficialLaunch = includedRadarTrialWindow(new Date("2026-07-10T00:00:00.000Z"), null);
assert.equal(withoutOfficialLaunch.startsAt.toISOString(), "2026-07-10T00:00:00.000Z", "without an official launch date, the paid date is authoritative");
assert.equal(withoutOfficialLaunch.endsAt.toISOString(), "2026-10-08T00:00:00.000Z");
assert.equal(RADAR_CATALOG.RADAR_PRO.prices.BRL, 149700, "BRL amount is server catalog owned");
assert.equal(RADAR_CATALOG.RADAR_PRO.limits.councilRuns, 100);
assert.equal(radarScheduledMode(RADAR_CATALOG.RADAR_PRO.limits), "detailed");
assert.equal(isAsaasPaidStatus("RECEIVED"), true, "received provider payments may fulfill");
assert.equal(isAsaasPaidStatus("CONFIRMED"), true, "confirmed provider payments may fulfill");
assert.equal(isAsaasPaidStatus("PENDING"), false, "webhook event alone is not settlement");
assert.equal(isAsaasPaidStatus("OVERDUE"), false);
assert.equal(isAsaasPaidStatus("CONFIRMED"), true, "late webhook policy fulfills verified settlement");
assert.equal(isAsaasReversalStatus("PAYMENT_REFUNDED", "REFUNDED"), true);
assert.equal(isAsaasReversalStatus("PAYMENT_REFUNDED", "RECEIVED"), false, "spoofed reversal never revokes");
assert.equal(isAsaasReversalStatus("PAYMENT_CHARGEBACK_REQUESTED", "CHARGEBACK_REQUESTED"), true);
assert.equal(isTerminalRadarPaymentStatus("expired"), true);
assert.equal(isTerminalRadarPaymentStatus("overdue"), true);
assert.equal(isTerminalRadarPaymentStatus("pending"), false);
assert.equal(isConfirmedNexosSubscriptionPayment({ status: "paid", paidAt: new Date(), metadata: { type: "plan" } }), true, "protected work can provision trial before UI access");
assert.equal(isConfirmedNexosSubscriptionPayment({ status: "pending", paidAt: null, metadata: { type: "plan" } }), false, "unpaid workspaces never receive included trial");
assert.equal(isConfirmedNexosSubscriptionPayment({ status: "paid", paidAt: new Date(), metadata: { type: "pack" } }), false, "credit packs are not subscriptions");
const now = new Date("2026-09-08T12:00:00.000Z");
const base = { package: "RADAR_PRO", campaignId: null, windowStartsAt: null, windowEndsAt: null };
const war = { package: "WAR_ROOM", campaignId: "campaign-a", windowStartsAt: new Date("2026-09-08T00:00:00.000Z"), windowEndsAt: new Date("2026-09-09T00:00:00.000Z") };
assert.equal(resolveRadarSubscription([war, base], now, "campaign-a"), war, "campaign War Room overrides only its own base capacity");
assert.equal(resolveRadarSubscription([war, base], now, "campaign-b"), base);
assert.equal(isCampaignOwnedByWorkspace("workspace-a", "workspace-a"), true);
assert.equal(isCampaignOwnedByWorkspace("workspace-b", "workspace-a"), false, "tenant guard rejects foreign campaign");
console.log("radar checkout trial/catalog unit tests passed");