import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { once } from "node:events";
import express from "express";
import { eq, inArray, sql } from "drizzle-orm";
import { db, pool, usersTable, workspacesTable, plansTable, authRefreshSessionsTable as sessions, academyPurchasesTable as purchases, academyAccessEmailOutboxTable as jobs, academyAdminAuditTable as audits, academyDeliveryReconciliationsTable as reviews } from "@workspace/db";
import { issueTokens } from "../modules/auth/auth.service.js";
import academyRouter from "../modules/academy/academy.routes.js";
import { confirmAcademyManually, requestAcademyResend } from "../modules/academy/academy-delivery-intents.service.js";
import { dispatchAcademyAccessEmail } from "../modules/academy/academy-access-outbox.service.js";
import { generateAccessToken } from "../modules/academy/academy-access-code.js";
assert.equal(process.env.NODE_ENV, "test");
const localFetch = fetch; globalThis.fetch = async () => { throw new Error("External calls forbidden"); };
const owner = randomUUID(), other = randomUUID(), workspace = randomUUID(), purchase = randomUUID();
const previousOwners = process.env.ACADEMY_ADMIN_USER_IDS;
const app = express(); app.use(express.json()); app.use("/api/academy", academyRouter);
app.use((err: { statusCode?: number }, _req: express.Request, res: express.Response, _next: express.NextFunction) => { res.status(err.statusCode ?? 500).json({ error: "fixture error" }); });
const server = app.listen(0, "127.0.0.1"); await once(server, "listening");
const address = server.address(); assert.ok(address && typeof address !== "string"); const base = `http://127.0.0.1:${address.port}/api/academy`;
try {
  const [plan] = await db.select().from(plansTable).limit(1); assert.ok(plan);
  for (const id of [owner, other]) await db.insert(usersTable).values({ id, email: `p0-${id}@example.invalid`, name: "Owned P0 fixture", passwordHash: "not-a-password" });
  await db.insert(workspacesTable).values({ id: workspace, ownerId: owner, planId: plan.id, name: "Owned P0 fixture", slug: `p0-${workspace}` });
  const tokens = await issueTokens({ id: owner, email: `p0-${owner}@example.invalid` }, workspace);
  const outsider = await issueTokens({ id: other, email: `p0-${other}@example.invalid` }, workspace);
  process.env.ACADEMY_ADMIN_USER_IDS = owner;
  const headers = { authorization: `Bearer ${tokens.accessToken}`, "Content-Type": "application/json" };
  assert.equal((await localFetch(`${base}/admin/purchases`)).status, 401);
  assert.equal((await localFetch(`${base}/admin/purchases`, { headers: { authorization: `Bearer ${outsider.accessToken}` } })).status, 403);
  process.env.ACADEMY_ADMIN_USER_IDS = `${owner},${other}`;
  assert.equal((await localFetch(`${base}/admin/purchases`, { headers: { authorization: `Bearer ${outsider.accessToken}` } })).status, 401, "Allowlist alone does not replace workspace ownership");
  process.env.ACADEMY_ADMIN_USER_IDS = owner;
  const allowed = await localFetch(`${base}/admin/purchases`, { headers }); assert.equal(allowed.status, 200); assert.equal(allowed.headers.get("cache-control"), "no-store"); await allowed.json();
  process.env.ACADEMY_ADMIN_SECRET = "fixture-secret-".repeat(4); process.env.ACADEMY_ALLOW_LEGACY_ADMIN_SECRET = "true"; process.env.NODE_ENV = "production";
  assert.equal((await localFetch(`${base}/admin/purchases`, { headers: { "x-admin-secret": process.env.ACADEMY_ADMIN_SECRET } })).status, 401, "Legacy flag can never bypass production owner session"); process.env.NODE_ENV = "test";
  await db.update(sessions).set({ revokedAt: new Date() }).where(eq(sessions.userId, owner));
  assert.equal((await localFetch(`${base}/admin/purchases`, { headers })).status, 401, "Session revocation immediately blocks administrative use of old access tokens");
  const renewed = await issueTokens({ id: owner, email: `p0-${owner}@example.invalid` }, workspace);
  assert.equal((await localFetch(`${base}/admin/purchases`, { headers })).status, 401, "A new login cannot resurrect an old session-bound token");
  headers.authorization = `Bearer ${renewed.accessToken}`;
  await db.insert(purchases).values({ id: purchase, accessToken: generateAccessToken(), customerEmail: "owned@example.invalid", productId: "mini-guide", amountCents: 9700 });
  await confirmAcademyManually(purchase);
  await dispatchAcademyAccessEmail(purchase, { deliver: async () => ({ status: "sending", errorCode: "EMAIL_DELIVERY_UNKNOWN" }) });
  const [job] = await db.select().from(jobs).where(eq(jobs.purchaseId, purchase)); assert.ok(job);
  const body = { jobId: job.id, decision: "not_accepted", evidenceReference: "owned-provider-case-001" };
  const reviewHeaders = { ...headers, "Idempotency-Key": randomUUID() };
  const reconcile = () => localFetch(`${base}/admin/delivery-reconciliation`, { method: "POST", headers: reviewHeaders, body: JSON.stringify(body) });
  assert.equal((await reconcile()).status, 409, "Live attempt cannot be reconciled immediately");
  await db.update(jobs).set({ claimedAt: sql`now() - interval '16 minutes'` }).where(eq(jobs.id, job.id));
  assert.equal((await reconcile()).status, 200); assert.equal((await reconcile()).status, 200);
  assert.equal((await db.select().from(reviews).where(eq(reviews.jobId, job.id))).length, 1);
  assert.equal((await db.select().from(jobs).where(eq(jobs.purchaseId, purchase))).length, 1, "Reconciliation never automatically retries");
  await requestAcademyResend(purchase, randomUUID());
  await dispatchAcademyAccessEmail(purchase, { deliver: async () => ({ status: "sending", errorCode: "EMAIL_DELIVERY_UNKNOWN" }) });
  const uncertain = (await db.select().from(jobs).where(eq(jobs.purchaseId, purchase))).find((j) => j.status === "sending")!;
  await db.update(jobs).set({ claimedAt: sql`now() - interval '16 minutes'` }).where(eq(jobs.id, uncertain.id));
  const accepted = await localFetch(`${base}/admin/delivery-reconciliation`, { method: "POST", headers: { ...headers, "Idempotency-Key": randomUUID() }, body: JSON.stringify({ jobId: uncertain.id, decision: "accepted", providerId: "offline-receipt", evidenceReference: "owned-provider-case-002" }) });
  assert.equal(accepted.status, 200);
  const [receipt] = await db.select().from(jobs).where(eq(jobs.id, uncertain.id)); assert.equal(receipt!.status, "sent");
  const access = await localFetch(`${base}/verify/${(await db.select().from(purchases).where(eq(purchases.id, purchase)))[0]!.accessToken}`);
  assert.equal(access.status, 200); const publicResult = await access.json() as Record<string, unknown>; assert.deepEqual(Object.keys(publicResult).sort(), ["productId", "valid"]);
  const tutor = (code?: string) => localFetch(`${base}/tutor`, { method: "POST", headers: { "Content-Type": "application/json", ...(code ? { "X-Academy-Access-Code": code } : {}) }, body: "{}" });
  const [student] = await db.select().from(purchases).where(eq(purchases.id, purchase));
  assert.equal((await tutor()).status, 401);
  assert.equal((await tutor(student!.accessToken)).status, 403, "Mini-guide cannot consume complete-course AI tutor");
  await db.update(purchases).set({ productId: "complete-bundle" }).where(eq(purchases.id, purchase));
  assert.equal((await tutor(student!.accessToken)).status, 400, "Active complete-bundle reaches input validation without calling AI");
  await db.update(purchases).set({ revokedAt: new Date() }).where(eq(purchases.id, purchase));
  assert.equal((await tutor(student!.accessToken)).status, 403, "Revoked students cannot call AI");
  const audit = await db.select().from(audits).where(eq(audits.actorId, owner)); assert.ok(audit.length >= 5); assert.ok(audit.every((a) => !a.action.includes("owned-provider")));
  console.log("PASS P0: explicit owner sessions, ownership, revocation, no production shared-secret fallback, audit, private verification and evidence-based idempotent reconciliation; no real provider calls");
} finally {
  process.env.NODE_ENV = "test"; if (previousOwners === undefined) delete process.env.ACADEMY_ADMIN_USER_IDS; else process.env.ACADEMY_ADMIN_USER_IDS = previousOwners;
  server.closeAllConnections(); await new Promise<void>((resolve) => server.close(() => resolve()));
  await db.delete(purchases).where(eq(purchases.id, purchase));
  // Await asynchronous audit completion before removing owned actors.
  await new Promise((resolve) => setTimeout(resolve, 100));
  await db.delete(usersTable).where(inArray(usersTable.id, [owner, other])); await pool.end();
}
