import { useState, type ElementType } from "react";
import {
  Activity, AlertTriangle, ArrowRight, Bot, Check, CheckCircle2, ChevronDown,
  ChevronRight, CirclePause, Command, CreditCard, Gauge, Hand, Layers3,
  LayoutDashboard, Menu, MessageSquare, Moon, MoreHorizontal, Network,
  Pause, Play, Radio, Search, Settings2, ShieldCheck, SlidersHorizontal,
  Sparkles, Target, TrendingUp, Users, Volume2, VolumeX, X, Zap,
} from "lucide-react";

type Mode = "fundador" | "arquiteto";

const navGroups: { label: string; items: Array<[string, ElementType]> }[] = [
  { label: "NÚCLEO", items: [["Cockpit", LayoutDashboard], ["Campanhas", Target], ["Agentes", Bot]] },
  { label: "OPERAÇÃO", items: [["Pipeline", Network], ["Mídia Autônoma", Radio], ["Presença Social", MessageSquare]] },
  { label: "INTELIGÊNCIA", items: [["Analytics", Activity], ["Memória", Layers3], ["Compliance", ShieldCheck]] },
];

const metrics = [
  { label: "Investimento", value: "R$ 12.480", note: "de R$ 18.000", icon: CreditCard, tone: "violet" },
  { label: "Leads gerados", value: "1.842", note: "+18,4% vs. meta", icon: Users, tone: "cyan" },
  { label: "CPL", value: "R$ 6,78", note: "−11,2% esta semana", icon: Target, tone: "green" },
  { label: "ROAS", value: "4,7x", note: "acima do alvo 3,8x", icon: TrendingUp, tone: "amber" },
  { label: "Alcance orgânico", value: "284 mil", note: "+32% no período", icon: Radio, tone: "pink" },
];

const threads = [
  { id: "scaling", agent: "Atlas · Mídia Paga", title: "Escalando vencedores no Meta", status: "working", detail: "Redistribuindo verba para conjuntos com CPL abaixo de R$ 6,50.", icon: Zap },
  { id: "google", agent: "Atlas · Mídia Paga", title: "Google Search pausado", status: "paused", detail: "CPL subiu 26%. Orçamento preservado até nova leitura.", icon: AlertTriangle },
  { id: "garry", agent: "Garry · Social", title: "Agendando 7 posts", status: "success", detail: "Calendário de conteúdo aprovado para os próximos 7 dias.", icon: CheckCircle2 },
  { id: "nicholas", agent: "Nicholas · Analytics", title: "Realocando 12% do orçamento", status: "working", detail: "Movendo investimento para criativos com ROAS 5,4x.", icon: SlidersHorizontal },
  { id: "philip", agent: "Philip · Compliance", title: "Revisão de conformidade aprovada", status: "success", detail: "Todos os anúncios passaram pelas regras da Meta e CONAR.", icon: ShieldCheck },
];

export default function CurrentBaseline() {
  const [mode, setMode] = useState<Mode>("fundador");
  const [activeNav, setActiveNav] = useState("Cockpit");
  const [selected, setSelected] = useState("scaling");
  const [approved, setApproved] = useState(false);
  const [handoff, setHandoff] = useState(false);
  const [details, setDetails] = useState(false);
  const [alertVisible, setAlertVisible] = useState(true);
  const [muted, setMuted] = useState(false);
  const activeThread = threads.find((thread) => thread.id === selected) ?? threads[0];

  return (
    <div className="baseline-shell">
      <style>{`
        .baseline-shell{--bg:#07090f;--panel:#0c1019;--panel2:#101622;--line:#202839;--muted:#7c879d;--text:#f1f4fb;--violet:#9274ff;--cyan:#55d6ec;--green:#39d39f;--amber:#f4bb5f;--pink:#e478b4;background:var(--bg);color:var(--text);font-family:ui-monospace,SFMono-Regular,Menlo,monospace;display:flex;min-height:820px;width:100%;font-size:12px;letter-spacing:.01em}
        .baseline-shell *{box-sizing:border-box}.baseline-shell button{font:inherit;color:inherit;cursor:pointer}.baseline-shell button:focus-visible{outline:2px solid var(--cyan);outline-offset:2px}
        .baseline-side{width:238px;flex:none;border-right:1px solid var(--line);background:#090c13;padding:20px 14px;display:flex;flex-direction:column;gap:18px}
        .baseline-brand{display:flex;align-items:center;gap:10px;padding:0 7px 18px;border-bottom:1px solid var(--line)}.baseline-brand-mark{width:29px;height:29px;border:1px solid var(--violet);color:var(--violet);display:grid;place-items:center;box-shadow:0 0 17px #9274ff33}.baseline-brand strong{font-size:16px;letter-spacing:.16em}.baseline-brand small{display:block;color:var(--muted);font-size:9px;margin-top:4px;letter-spacing:.14em}
        .baseline-workspace{background:var(--panel);border:1px solid var(--line);padding:11px}.baseline-eyebrow{font-size:9px;color:var(--muted);letter-spacing:.13em;text-transform:uppercase}.baseline-workspace-name{font-weight:bold;margin-top:6px;display:flex;justify-content:space-between;align-items:center}.baseline-workspace-name svg{color:var(--muted)}
        .baseline-nav{flex:1}.baseline-nav h4{font-size:9px;color:#58647b;font-weight:normal;letter-spacing:.16em;margin:16px 8px 7px}.baseline-nav button{display:flex;align-items:center;gap:10px;width:100%;border:0;background:transparent;padding:9px 9px;text-align:left;color:#8994a8;min-height:38px}.baseline-nav button:hover,.baseline-nav button.active{background:#171329;color:var(--text)}.baseline-nav button.active{border-left:2px solid var(--violet);color:var(--violet)}.baseline-nav button svg{width:15px}.baseline-nav button span{flex:1}
        .baseline-credits{border-top:1px solid var(--line);padding:15px 7px 0}.baseline-credit-line{display:flex;justify-content:space-between;margin:7px 0;color:var(--muted);font-size:10px}.baseline-credit-line b{color:var(--text)}.baseline-meter{height:4px;background:#1e2636}.baseline-meter i{display:block;width:68%;height:100%;background:var(--violet)}.baseline-profile{display:flex;align-items:center;gap:9px;padding:10px 6px 0;color:var(--muted);font-size:10px}.baseline-avatar{width:25px;height:25px;border:1px solid var(--violet);display:grid;place-items:center;color:var(--violet)}
        .baseline-main{min-width:0;flex:1;padding:24px 29px 34px;overflow:hidden}.baseline-top{display:flex;align-items:center;gap:15px;border-bottom:1px solid var(--line);padding-bottom:20px}.baseline-top-title{flex:1}.baseline-top-title h1{font-family:Inter,system-ui,sans-serif;font-size:21px;letter-spacing:-.03em;margin:6px 0}.baseline-top-title p{margin:0;color:var(--muted);font-size:11px}.baseline-live{display:inline-flex;align-items:center;gap:6px;color:var(--green);font-size:10px;letter-spacing:.12em;text-transform:uppercase}.baseline-live i{display:block;width:6px;height:6px;background:var(--green);box-shadow:0 0 8px var(--green)}.baseline-toggle{display:flex;border:1px solid var(--line);padding:3px}.baseline-toggle button{border:0;background:transparent;color:var(--muted);padding:8px 11px;min-height:38px;font-size:10px}.baseline-toggle button.active{background:var(--violet);color:#fff}.baseline-icon-btn{background:transparent;border:1px solid var(--line);width:40px;height:40px;display:grid;place-items:center;color:var(--muted)}
        .baseline-hero{border:1px solid #2a2750;background:linear-gradient(100deg,#121328,#0d111c 70%);padding:20px 22px;margin:22px 0 16px;position:relative;overflow:hidden}.baseline-hero:after{content:"";position:absolute;right:-40px;top:-70px;width:220px;height:220px;border:1px solid #9274ff22;transform:rotate(45deg)}.baseline-hero-top{display:flex;justify-content:space-between;gap:18px;position:relative;z-index:1}.baseline-hero h2{font-family:Inter,system-ui,sans-serif;font-size:19px;margin:7px 0}.baseline-hero p{color:#aeb6c7;margin:0;max-width:590px;font-size:11px;line-height:1.6}.baseline-authority{color:var(--green);border:1px solid #39d39f55;padding:7px 9px;white-space:nowrap;height:max-content;font-size:10px}.baseline-progress{margin-top:19px;position:relative;z-index:1}.baseline-progress-line{height:5px;background:#24263c;display:flex}.baseline-progress-line i{width:86%;background:linear-gradient(90deg,var(--violet),var(--cyan))}.baseline-progress-labels{display:flex;justify-content:space-between;margin-top:7px;color:var(--muted);font-size:9px}.baseline-progress-labels b{color:var(--cyan)}
        .baseline-kpis{display:grid;grid-template-columns:repeat(5,1fr);border:1px solid var(--line);margin-bottom:16px}.baseline-kpi{padding:14px 13px;border-right:1px solid var(--line);min-width:0}.baseline-kpi:last-child{border:0}.baseline-kpi-head{display:flex;align-items:center;gap:7px;color:var(--muted);font-size:9px;text-transform:uppercase;letter-spacing:.06em;white-space:nowrap}.baseline-kpi-head svg{width:13px}.baseline-kpi-value{font-family:Inter,system-ui,sans-serif;font-size:20px;font-weight:700;margin-top:11px;white-space:nowrap}.baseline-kpi-note{font-size:9px;color:var(--green);margin-top:5px;white-space:nowrap}
        .baseline-columns{display:grid;grid-template-columns:minmax(0,1.18fr) minmax(290px,.82fr);gap:16px}.baseline-card{background:var(--panel);border:1px solid var(--line);padding:17px}.baseline-card-title{display:flex;align-items:center;gap:8px;color:#d4d9e4;font-size:10px;text-transform:uppercase;letter-spacing:.13em;margin-bottom:14px}.baseline-card-title svg{width:14px;color:var(--violet)}.baseline-card-title span{margin-left:auto;color:var(--muted);font-size:9px}
        .baseline-thread{display:flex;gap:11px;padding:12px 5px;border-top:1px solid #1b2230;cursor:pointer}.baseline-thread:hover,.baseline-thread.selected{background:#111725}.baseline-thread.selected{border-left:2px solid var(--cyan);padding-left:8px}.baseline-thread-icon{width:27px;height:27px;display:grid;place-items:center;flex:none;background:#172033}.baseline-thread-icon svg{width:14px}.baseline-thread-main{min-width:0;flex:1}.baseline-thread-line{display:flex;justify-content:space-between;gap:8px}.baseline-thread-title{font-size:11px;font-weight:bold}.baseline-thread-detail{font-size:10px;color:var(--muted);margin-top:6px;line-height:1.45}.status{font-size:9px;white-space:nowrap;text-transform:uppercase;letter-spacing:.08em}.status.working{color:var(--cyan)}.status.success{color:var(--green)}.status.warning{color:var(--amber)}.status.paused{color:#9aa4b8}
        .baseline-alert{border-left:2px solid var(--amber);background:#16130d;padding:13px 12px;margin-bottom:14px;display:flex;gap:10px}.baseline-alert svg{color:var(--amber);flex:none}.baseline-alert strong{font-size:10px}.baseline-alert p{color:#aaa080;font-size:10px;margin:6px 0 0;line-height:1.5}.baseline-alert button{margin-left:auto;align-self:flex-start;background:transparent;border:0;color:var(--muted)}
        .baseline-action{border:1px solid #3f326a;background:#171329;padding:15px;display:flex;gap:12px;align-items:flex-start}.baseline-action-icon{color:var(--violet);padding-top:2px}.baseline-action h3{font-family:Inter,system-ui,sans-serif;font-size:14px;margin:0 0 6px}.baseline-action p{font-size:10px;color:#a8b0c1;line-height:1.5;margin:0}.baseline-actions{display:flex;gap:8px;margin-top:12px;flex-wrap:wrap}.baseline-primary,.baseline-secondary{border:1px solid var(--violet);background:var(--violet);padding:9px 12px;min-height:40px;font-size:10px}.baseline-secondary{background:transparent;color:#b7a8ff!important;border-color:#5a4e88}.baseline-mode-copy{color:var(--muted);font-size:10px;line-height:1.5;margin:10px 0 0}.baseline-trace{margin-top:12px;border-top:1px solid var(--line);padding-top:11px;color:#8994a8;font-size:10px;line-height:1.7}.baseline-trace b{color:var(--cyan);font-weight:normal}.baseline-muted{color:var(--muted)}.baseline-mobile-menu{display:none}
        @media(max-width:900px){.baseline-side{width:205px}.baseline-main{padding:20px 18px}.baseline-kpis{grid-template-columns:repeat(3,1fr)}.baseline-kpi:nth-child(3){border-right:0}.baseline-kpi:nth-child(n+4){border-top:1px solid var(--line)}.baseline-columns{grid-template-columns:1fr}}
        @media(max-width:620px){.baseline-shell{min-height:844px;display:block}.baseline-side{display:none}.baseline-main{padding:14px 13px 26px}.baseline-top{padding-bottom:14px;gap:8px}.baseline-mobile-menu{display:grid}.baseline-top-title h1{font-size:16px}.baseline-top-title p{font-size:9px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.baseline-toggle button{padding:7px 8px;font-size:9px}.baseline-icon-btn{width:38px;height:38px}.baseline-hero{margin:14px 0 12px;padding:16px}.baseline-hero-top{display:block}.baseline-hero h2{font-size:16px}.baseline-authority{display:inline-block;margin-top:13px}.baseline-kpis{grid-template-columns:repeat(2,1fr)}.baseline-kpi:nth-child(3){border-right:1px solid var(--line)}.baseline-kpi:nth-child(n+3){border-top:1px solid var(--line)}.baseline-kpi:nth-child(even){border-right:0}.baseline-kpi{padding:12px 10px}.baseline-kpi-value{font-size:17px}.baseline-kpi-note{font-size:8px}.baseline-columns{gap:12px}.baseline-card{padding:13px}.baseline-thread-title{font-size:10px}.baseline-thread-detail{font-size:9px}.baseline-hero p{font-size:10px}}
        @media(prefers-reduced-motion:reduce){.baseline-shell *{scroll-behavior:auto!important;transition:none!important;animation:none!important}}
      `}</style>
      <aside className="baseline-side" aria-label="Navegação NexOS">
        <div className="baseline-brand"><div className="baseline-brand-mark"><Command size={16}/></div><div><strong>NEXOS</strong><small>OPERAÇÕES INTELIGENTES</small></div></div>
        <button className="baseline-workspace" aria-label="Trocar workspace"><div className="baseline-eyebrow">OPERAÇÃO ATIVA</div><div className="baseline-workspace-name">NexOS Growth Lab <ChevronDown size={14}/></div></button>
        <nav className="baseline-nav">{navGroups.map((group) => <div key={group.label}><h4>{group.label}</h4>{group.items.map(([label, Icon]) => <button key={label} className={activeNav === label ? "active" : ""} onClick={() => setActiveNav(label)}><Icon size={15}/><span>{label}</span>{label === "Agentes" && <small>7</small>}</button>)}</div>)}</nav>
        <div className="baseline-credits"><div className="baseline-eyebrow">CRÉDITOS DE IA <span aria-label="Saldo confirmado">●</span></div><div className="baseline-credit-line"><span>Saldo mensal</span><b>68.420 cr</b></div><div className="baseline-meter"><i/></div></div>
        <div className="baseline-profile"><div className="baseline-avatar">FC</div><span>Fundador · NexOS</span><Settings2 size={14} style={{marginLeft:"auto"}}/></div>
      </aside>
      <main className="baseline-main">
        <header className="baseline-top">
          <button className="baseline-icon-btn baseline-mobile-menu" aria-label="Abrir navegação"><Menu size={17}/></button>
          <div className="baseline-top-title"><div className="baseline-live"><i/> SISTEMA OPERACIONAL <span className="baseline-muted">/ 09:42 BRT</span></div><h1>Olá, Fundador. Aqui está o comando.</h1><p>Método Agenda Cheia — São Paulo <span className="baseline-muted">· Campanha ativa</span></p></div>
          <div className="baseline-toggle" role="group" aria-label="Modo de visualização"><button className={mode === "fundador" ? "active" : ""} onClick={() => setMode("fundador")}><Gauge size={12}/> Fundador</button><button className={mode === "arquiteto" ? "active" : ""} onClick={() => setMode("arquiteto")}><Zap size={12}/> Arquiteto</button></div>
          <button className="baseline-icon-btn" aria-label={muted ? "Ativar sons" : "Silenciar sons"} onClick={() => setMuted(!muted)}>{muted ? <VolumeX size={16}/> : <Volume2 size={16}/>}</button>
        </header>
        <section className="baseline-hero" aria-labelledby="mission-heading">
          <div className="baseline-hero-top"><div><div className="baseline-eyebrow">MISSÃO EM EXECUÇÃO · MASTER PLAN v12</div><h2 id="mission-heading">Encher a agenda de São Paulo com leads qualificados</h2><p>Meta de 2.400 leads até 30/06. O plano aprovado é a autoridade para todos os agentes e suas decisões de mídia.</p></div><div className="baseline-authority"><Check size={12}/> APROVAÇÃO HERDADA</div></div>
          <div className="baseline-progress"><div className="baseline-progress-line"><i/></div><div className="baseline-progress-labels"><span><b>77%</b> do objetivo alcançado</span><span>1.842 / 2.400 leads</span></div></div>
        </section>
        <section className="baseline-kpis" aria-label="Indicadores principais">{metrics.map((metric) => <div className="baseline-kpi" key={metric.label}><div className="baseline-kpi-head" style={{color:`var(--${metric.tone})`}}><metric.icon size={13}/>{metric.label}</div><div className="baseline-kpi-value">{metric.value}</div><div className="baseline-kpi-note">{metric.note}</div></div>)}</section>
        <div className="baseline-columns">
          <section className="baseline-card" aria-labelledby="activity-heading"><div className="baseline-card-title" id="activity-heading"><Activity size={14}/> ATIVIDADE DOS AGENTES <span>agora · 5 sinais</span></div>{threads.map((thread) => <button key={thread.id} className={`baseline-thread ${selected === thread.id ? "selected" : ""}`} onClick={() => setSelected(thread.id)} aria-pressed={selected === thread.id}><div className="baseline-thread-icon"><thread.icon size={14}/></div><div className="baseline-thread-main"><div className="baseline-thread-line"><span className="baseline-thread-title">{thread.title}</span><span className={`status ${thread.status}`}>{thread.status === "working" ? "● trabalhando" : thread.status === "warning" ? "▲ atenção" : thread.status === "paused" ? "Ⅱ pausado" : "✓ concluído"}</span></div><div className="baseline-eyebrow" style={{marginTop:5}}>{thread.agent}</div><div className="baseline-thread-detail">{thread.detail}</div></div></button>)}</section>
          <div>
            {alertVisible && <div className="baseline-alert" role="alert"><AlertTriangle size={15}/><div><strong>ATENÇÃO NECESSÁRIA · Google Search</strong><p>CPL acima do limite após aumento de 26%. O agente pausou a fonte para proteger o orçamento.</p></div><button onClick={() => setAlertVisible(false)} aria-label="Dispensar alerta"><X size={14}/></button></div>}
            <section className="baseline-card"><div className="baseline-card-title"><Sparkles size={14}/> PRÓXIMA AÇÃO <span>recomendação do sistema</span></div><div className="baseline-action"><div className="baseline-action-icon"><ArrowRight size={18}/></div><div><h3>Validar a realocação de verba</h3><p>Nicholas encontrou 12% de orçamento para mover aos vencedores. Sua aprovação libera a execução em Meta.</p><div className="baseline-actions"><button className="baseline-primary" onClick={() => setApproved(true)}>{approved ? "✓ Realocação aprovada" : "Aprovar realocação"}</button><button className="baseline-secondary" onClick={() => setHandoff(!handoff)}><Hand size={12}/> {handoff ? "Handoff enviado" : "Assumir controle"}</button></div></div></div>{handoff && <div className="baseline-trace"><b>HANDOFF REGISTRADO</b> · Você assumiu a decisão. O time de Mídia aguarda sua instrução.</div>}</section>
            <section className="baseline-card" style={{marginTop:16}}><button className="baseline-card-title" onClick={() => setDetails(!details)} style={{background:"transparent",border:0,width:"100%",padding:0,textAlign:"left"}}><MoreHorizontal size={14}/> CONTEXTO DA DECISÃO <span>{details ? "ocultar" : "ver detalhes"} <ChevronRight size={12}/></span></button>{details && <div className="baseline-trace"><b>POR QUÊ</b> · Meta entrega CPL R$ 5,92 com ROAS 5,4x.<br/><b>PESO</b> · Performance 70% · Aprendizado 20% · Segurança 10%.<br/><b>DEPOIS</b> · Atlas publica a nova distribuição e monitora por 24h.</div>}</section>
          </div>
        </div>
        <div className="baseline-mode-copy">{mode === "fundador" ? "Modo Fundador · resultados primeiro. O sistema traduz decisões técnicas em próximos passos claros." : "Modo Arquiteto · trace ativo: 7 agentes · 12% peso de realocação · herança Master Plan v12 · supervisão humana disponível."}</div>
      </main>
    </div>
  );
}