import { useState } from "react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Activity, BarChart2, Check, CheckCircle2, Clock, Copy, Info, Loader2, MapPin, QrCode, Receipt, Search, Shield, Users } from "lucide-react";
import { useGetCampaigns, useRadarPayment, useRegionalCatalog, useRegionalEntitlement, useRequestRegionalUpgrade, useSelectNoRadar, useStartRadarCheckout } from "@/hooks/use-regional-intel";
import { toast } from "sonner";
import { intlLocale, useUiLocale, useUiText } from "@/lib/i18n";

interface Props { className?: string }
const key = () => crypto.randomUUID?.() ?? `${Date.now()}-${Math.random().toString(36).slice(2)}`;
const date = (value?: string | Date | null, locale = "pt-BR") => value ? new Date(value).toLocaleDateString(locale) : "—";
const price = (value: number, currency: "BRL" | "USD", locale: string) => (value / 100).toLocaleString(locale, { style: "currency", currency });
const cadence = (minutes: number, t: ReturnType<typeof useUiText>) => minutes >= 1440 ? t("Diária", "Daily", "Diaria") : minutes >= 360 ? t("A cada 6 horas", "Every 6 hours", "Cada 6 horas") : `${minutes} min`;

export function CapacityTab({ className = "" }: Props) {
  const t = useUiText();
  const { locale } = useUiLocale();
  const numberLocale = intlLocale(locale);
  const [currency, setCurrency] = useState<"BRL" | "USD">("BRL");
  const [checkout, setCheckout] = useState<{ package: string; name: string; campaignId?: string } | null>(null);
  const [payment, setPayment] = useState<any>(null);
  const { data: catalogData, isLoading: catalogLoading } = useRegionalCatalog();
  const { data, isLoading: entitlementLoading, refetch } = useRegionalEntitlement();
  const commercial = useRequestRegionalUpgrade();
  const startCheckout = useStartRadarCheckout();
  const { data: campaignsData, isLoading: campaignsLoading } = useGetCampaigns();
  const noRadar = useSelectNoRadar();
  const paid = useRadarPayment(payment?.id ?? null);
  const entitlement = data?.entitlement;
  const subscription = entitlement?.subscription;
  const limits = entitlement?.limits;
  const isTrial = subscription?.source === "subscription_included" || subscription?.entitlementSource === "subscription_included";
  const trialStart = subscription?.periodStartsAt;
  const trialEnd = subscription?.periodEndsAt;
  const daysRemaining = trialEnd ? Math.max(0, Math.ceil((new Date(trialEnd).getTime() - Date.now()) / 86_400_000)) : null;
  const fulfillment = paid.data?.fulfillmentStatus ?? paid.data?.payment?.fulfillmentStatus ?? payment?.fulfillmentStatus;
  const activePayment = paid.data?.payment ?? payment;

  if (catalogLoading || entitlementLoading) return <div className="py-20 text-center"><Loader2 className="h-8 w-8 animate-spin mx-auto text-primary" /><p className="mt-4 font-mono text-sm uppercase tracking-wider text-muted-foreground">{t("Carregando Radar de Mercado…", "Loading Market Radar…", "Cargando Radar de mercado…")}</p></div>;

  const begin = (pkg: any) => {
    if (currency === "USD") {
      commercial.mutate({ package: pkg.package, currency, idempotencyKey: key() }, {
        onSuccess: () => toast.success(t("Solicitação comercial registrada. O checkout Asaas opera apenas em BRL.", "Commercial request recorded. Asaas checkout only supports BRL.", "Solicitud comercial registrada. El pago de Asaas solo admite BRL.")),
        onError: (error: Error) => toast.error(error.message || t("Não foi possível registrar a solicitação.", "Could not record the request.", "No se pudo registrar la solicitud.")),
      });
      return;
    }
    setCheckout({ package: pkg.package, name: pkg.name });
  };
  const pay = (method: "pix" | "boleto") => {
    if (!checkout) return;
    if (checkout.package === "WAR_ROOM" && !checkout.campaignId) {
      toast.error(t("Selecione a campanha da janela War Room.", "Select the campaign for the War Room window.", "Selecciona la campaña de la ventana War Room."));
      return;
    }
    startCheckout.mutate({ package: checkout.package, method, idempotencyKey: key(), campaignId: checkout.campaignId }, {
      onSuccess: ({ payment: created }) => { setPayment(created); setCheckout(null); },
      onError: (error: Error) => toast.error(error.message || t("Não foi possível criar o checkout Asaas.", "Could not create the Asaas checkout.", "No se pudo crear el pago de Asaas.")),
    });
  };
  const selectNoRadar = () => noRadar.mutate(key(), {
    onSuccess: () => toast.success(t("Preferência salva. O histórico continua disponível; novas varreduras e Councils ficam pausados.", "Preference saved. History remains available; new scans and Councils are paused.", "Preferencia guardada. El historial sigue disponible; las nuevas exploraciones y Councils quedan pausados.")),
    onError: (error: Error) => toast.error(error.message || t("Não foi possível salvar sua escolha.", "Could not save your choice.", "No se pudo guardar tu elección.")),
  });
  const pix = activePayment?.pixData;
  const boleto = activePayment?.boletoData;

  return <div className={`space-y-8 ${className}`}>
    <section className="grid lg:grid-cols-2 gap-6 border border-border/50 bg-card/30 p-6 rounded-sm">
      <div className="space-y-4">
        <h2 className="font-mono text-lg uppercase tracking-wider flex items-center gap-2"><Shield className="h-5 w-5 text-primary" /> {t("Radar de Mercado", "Market Radar", "Radar de mercado")}</h2>
        <p className="text-sm text-muted-foreground leading-relaxed">{t("Inteligência contínua para acompanhar concorrentes e mercado com velocidade e fluidez. O Radar reduz testes e mídia desperdiçados ao transformar evidências em decisões adaptadas ao idioma e à região.", "Continuous intelligence to track competitors and the market quickly and smoothly. Radar reduces wasted testing and media spend by turning evidence into decisions adapted to language and region.", "Inteligencia continua para seguir a competidores y al mercado con rapidez. Radar reduce las pruebas y la inversión publicitaria desperdiciadas al convertir evidencia en decisiones adaptadas al idioma y la región.")}</p>
        <ul className="space-y-2 text-sm text-muted-foreground">
          <li className="flex gap-2"><Check className="h-4 w-4 text-primary shrink-0" />{t("Monitora movimentos concorrenciais e oportunidades de mercado continuamente.", "Continuously monitors competitor movements and market opportunities.", "Supervisa continuamente los movimientos de la competencia y las oportunidades de mercado.")}</li>
          <li className="flex gap-2"><Check className="h-4 w-4 text-primary shrink-0" />{t("Acompanha oportunidades conquistadas no ciclo de vida autorizado, com linguagem adaptativa.", "Tracks opportunities throughout the authorized lifecycle, using adaptive language.", "Sigue oportunidades durante el ciclo de vida autorizado, con lenguaje adaptable.")}</li>
          <li className="flex gap-2"><Check className="h-4 w-4 text-primary shrink-0" />{t("Execução autônoma integralmente governada: sinais e recomendações não enviam contatos sem autorização.", "Fully governed autonomous execution: signals and recommendations never contact people without authorization.", "Ejecución autónoma totalmente gobernada: las señales y recomendaciones no contactan a nadie sin autorización.")}</li>
        </ul>
      </div>
      <div className="border border-primary/30 bg-primary/5 p-5 space-y-3">
        <h3 className="font-mono text-xs uppercase tracking-wider text-primary">{t("Como funciona", "How it works", "Cómo funciona")}</h3>
        <p className="text-xs text-muted-foreground leading-relaxed">{t("A capacidade ativa define cadência, limites e retenção. Após o período incluído, escolha um pacote base ou No Radar. Sem pacote, não há novas varreduras custosas ou Councils; o histórico permanece somente para leitura.", "Active capacity sets cadence, limits, and retention. After the included period, choose a base package or No Radar. Without a package, no costly scans or Councils run; history remains read-only.", "La capacidad activa define la frecuencia, los límites y la retención. Tras el periodo incluido, elige un paquete base o No Radar. Sin paquete, no se ejecutan nuevas exploraciones costosas ni Councils; el historial queda disponible en modo de solo lectura.")}</p>
        <p className="text-xs text-muted-foreground leading-relaxed"><strong>War Room</strong> {t("é um adicional de 30 dias para uma campanha/janela de lançamento — não substitui o pacote base.", "is a 30-day add-on for one campaign/launch window—it does not replace the base package.", "es un complemento de 30 días para una campaña/ventana de lanzamiento; no sustituye al paquete base.")}</p>
      </div>
    </section>

    {isTrial && <section className="border border-success/40 bg-success/5 p-5 space-y-3">
      <div className="flex flex-wrap justify-between gap-3"><div><Badge variant="outline" className="border-success/40 text-success">{t("INCLUÍDO NA ASSINATURA NEXOS", "INCLUDED WITH NEXOS SUBSCRIPTION", "INCLUIDO EN LA SUSCRIPCIÓN NEXOS")}</Badge><h3 className="font-mono mt-2 text-base">{t("Radar Pro incluído por 3 meses", "Radar Pro included for 3 months", "Radar Pro incluido durante 3 meses")}</h3></div><div className="text-right font-mono text-xs"><div>{daysRemaining} {t("dias restantes", "days remaining", "días restantes")}</div><div className="text-muted-foreground">{date(trialStart, numberLocale)} — {date(trialEnd, numberLocale)}</div></div></div>
      <p className="text-sm text-muted-foreground">{t("Sem cobrança de Radar neste período: 3 campanhas, 10 concorrentes, varreduras diárias, 3 regiões/idiomas, 100 Council runs por período de 30 dias, retenção de 180 dias e Centro de Interação.", "No Radar charges during this period: 3 campaigns, 10 competitors, daily scans, 3 regions/languages, 100 Council runs per 30-day period, 180-day retention, and the Interaction Hub.", "Sin cargos de Radar durante este periodo: 3 campañas, 10 competidores, exploraciones diarias, 3 regiones/idiomas, 100 ejecuciones de Council por periodo de 30 días, retención de 180 días y centro de interacción.")}</p>
    </section>}

    <section className="space-y-4"><div className="flex justify-between border-b border-border/50 pb-2"><div><h3 className="font-mono text-base uppercase tracking-wider">{t("Capacidade atual", "Current capacity", "Capacidad actual")}</h3><p className="text-xs text-muted-foreground mt-1">{t("Consumo do período ativo.", "Usage for the active period.", "Consumo del periodo activo.")}</p></div><Button variant="ghost" size="sm" onClick={() => refetch()}>{t("Atualizar", "Refresh", "Actualizar")}</Button></div>
      {entitlement?.active && limits ? <><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4"><Usage icon={BarChart2} label={t("Campanhas", "Campaigns", "Campañas")} used={data?.usage?.monitored_campaign || 0} total={limits.monitoredCampaigns}/><Usage icon={Users} label={t("Concorrentes", "Competitors", "Competidores")} used={data?.usage?.competitor || 0} total={limits.competitors}/><Usage icon={MapPin} label={t("Regiões / idiomas", "Regions / languages", "Regiones / idiomas")} used={data?.usage?.region || 0} total={limits.regions}/><Usage icon={Search} label={t("Council runs", "Council runs", "Ejecuciones de Council")} used={data?.usage?.council_run || 0} total={limits.councilRuns}/></div><div className="grid sm:grid-cols-3 gap-3 text-xs"><Stat label={t("Varredura", "Scan", "Exploración")} value={cadence(limits.scanCadenceMinutes, t)}/><Stat label={t("Retenção", "Retention", "Retención")} value={`${limits.retentionDays} ${t("dias", "days", "días")}`}/><Stat label={t("Vigência", "Validity", "Vigencia")} value={`${t("até", "until", "hasta")} ${date(subscription?.windowEndsAt ?? subscription?.periodEndsAt, numberLocale)}`}/></div></> : <div className="border border-border/50 p-8 text-center"><Activity className="h-8 w-8 mx-auto text-muted-foreground mb-3"/><p className="font-mono text-sm">{t("SEM PACOTE ATIVO", "NO ACTIVE PACKAGE", "SIN PAQUETE ACTIVO")}</p><p className="text-xs text-muted-foreground mt-2">{t("Seu histórico está preservado para consulta. Selecione um pacote para retomar novas varreduras e Councils.", "Your history is preserved for reference. Select a package to resume new scans and Councils.", "Tu historial se conserva para consultarlo. Selecciona un paquete para reanudar las exploraciones y Councils.")}</p></div>}
    </section>

    {activePayment && <section className="border border-primary/40 bg-card/50 p-5 space-y-3"><div className="flex items-center gap-2 font-mono text-sm"><Receipt className="h-4 w-4 text-primary"/> {t("Checkout Radar", "Radar Checkout", "Pago de Radar")} · {activePayment.method === "pix" ? "PIX" : t("Boleto", "Bank slip", "Boleta")}</div>
      {fulfillment === "fulfilled" || activePayment.status === "fulfilled" ? <p className="text-sm text-success flex gap-2"><CheckCircle2 className="h-4 w-4"/>{t("Pagamento confirmado e capacidade ativada.", "Payment confirmed and capacity activated.", "Pago confirmado y capacidad activada.")}</p> : ["overdue", "expired"].includes(activePayment.status) ? <p className="text-sm text-destructive">{t("Este pagamento venceu/expirou e não ativou o Radar. Gere um novo checkout para continuar.", "This payment expired and did not activate Radar. Create a new checkout to continue.", "Este pago venció o caducó y no activó el Radar. Genera un nuevo pago para continuar.")}</p> : <><p className="text-xs text-muted-foreground">{t("Aguardando confirmação do Asaas e cumprimento da capacidade. O Radar só fica ativo após essa confirmação.", "Waiting for Asaas confirmation and capacity fulfillment. Radar activates only after confirmation.", "Esperando la confirmación de Asaas y la activación de la capacidad. El Radar se activa solo después de confirmarlo.")}</p>{pix?.qrCode && <img className="w-40 bg-white p-2" src={`data:image/png;base64,${pix.qrCode}`} alt={t("QR Code PIX", "PIX QR code", "Código QR de PIX")} />}{pix?.copiaECola && <Button variant="outline" size="sm" onClick={() => navigator.clipboard.writeText(pix.copiaECola).then(() => toast.success(t("PIX copiado.", "PIX copied.", "PIX copiado.")))}><Copy className="h-3.5 w-3.5 mr-1"/>{t("Copiar PIX", "Copy PIX", "Copiar PIX")}</Button>}{boleto?.barcodeUrl && <Button variant="outline" size="sm" onClick={() => window.open(boleto.barcodeUrl, "_blank", "noopener,noreferrer")}>{t("Abrir boleto", "Open bank slip", "Abrir boleta")}</Button>}<p className="text-[11px] text-muted-foreground flex gap-1"><Clock className="h-3 w-3"/>{t("Status:", "Status:", "Estado:")} {paymentStatusLabel(activePayment.status, t)} {paid.isFetching ? `· ${t("atualizando…", "refreshing…", "actualizando…")}` : ""}</p></>}</section>}

    {checkout && <section className="border border-primary/40 bg-primary/5 p-5 flex flex-wrap items-center gap-3"><div className="mr-auto"><p className="font-mono text-sm">{checkout.name}</p><p className="text-xs text-muted-foreground">{t("Checkout Asaas em BRL", "Asaas checkout in BRL", "Pago de Asaas en BRL")}</p></div>
      {checkout.package === "WAR_ROOM" && <div className="w-full border border-amber-500/30 bg-amber-500/5 p-3 space-y-2"><p className="text-xs text-muted-foreground">{t("A janela War Room dura 30 dias e fica vinculada somente à campanha selecionada; ela não substitui seu pacote Radar base.", "The War Room window lasts 30 days and is linked only to the selected campaign; it does not replace your base Radar package.", "La ventana War Room dura 30 días y se vincula solo a la campaña seleccionada; no sustituye tu paquete Radar base.")}</p><label className="block font-mono text-[10px] uppercase tracking-widest text-muted-foreground">{t("Campanha da janela", "Window campaign", "Campaña de la ventana")}</label><select value={checkout.campaignId ?? ""} onChange={(event) => setCheckout(current => current ? { ...current, campaignId: event.target.value || undefined } : current)} disabled={campaignsLoading} className="w-full max-w-md border border-border/50 bg-background px-3 py-2 text-sm"><option value="">{campaignsLoading ? t("Carregando campanhas…", "Loading campaigns…", "Cargando campañas…") : t("Selecione uma campanha", "Select a campaign", "Selecciona una campaña")}</option>{campaignsData?.campaigns.map((campaign) => <option key={campaign.id} value={campaign.id}>{campaign.title}</option>)}</select>{!campaignsLoading && !campaignsData?.campaigns.length && <p className="text-xs text-destructive">{t("Crie uma campanha antes de contratar uma janela War Room.", "Create a campaign before purchasing a War Room window.", "Crea una campaña antes de contratar una ventana War Room.")}</p>}</div>}
      <Button onClick={() => pay("pix")} disabled={startCheckout.isPending || (checkout.package === "WAR_ROOM" && !checkout.campaignId)}><QrCode className="h-4 w-4 mr-1"/>{t("Pagar com PIX", "Pay with PIX", "Pagar con PIX")}</Button><Button variant="outline" onClick={() => pay("boleto")} disabled={startCheckout.isPending || (checkout.package === "WAR_ROOM" && !checkout.campaignId)}>{t("Boleto", "Bank slip", "Boleta")}</Button><Button variant="ghost" onClick={() => setCheckout(null)}>{t("Cancelar", "Cancel", "Cancelar")}</Button></section>}

    <section className="space-y-4 pt-3 border-t border-border/50"><div className="flex justify-between items-end"><div><h3 className="font-mono text-base uppercase tracking-wider">{t("Escolha após o período incluído", "Choose after the included period", "Elige después del periodo incluido")}</h3><p className="text-xs text-muted-foreground mt-1">{t("Valores atuais. Asaas processa somente BRL; USD solicita atendimento comercial.", "Current prices. Asaas processes BRL only; USD requests commercial support.", "Precios actuales. Asaas procesa solo BRL; USD requiere atención comercial.")}</p></div><div className="border border-border/50 p-1"><button onClick={() => setCurrency("BRL")} className={`px-3 py-1 text-xs ${currency === "BRL" ? "bg-primary/20 text-primary" : ""}`}>BRL</button><button onClick={() => setCurrency("USD")} className={`px-3 py-1 text-xs ${currency === "USD" ? "bg-primary/20 text-primary" : ""}`}>USD</button></div></div>
       <div className="grid md:grid-cols-2 xl:grid-cols-4 gap-4">{(catalogData?.packages || []).map((pkg: any) => <Package key={pkg.package} pkg={pkg} currency={currency} active={subscription?.package === pkg.package} onChoose={() => begin(pkg)} loading={startCheckout.isPending || commercial.isPending} locale={numberLocale} t={t}/>)}
         <div className="border border-border/50 p-5 flex flex-col"><h4 className="font-mono text-sm">NO RADAR</h4><p className="text-xs text-muted-foreground mt-3 flex-1">{t("Não renovar o Radar. Sem novas varreduras custosas ou Councils; histórico legível.", "Do not renew Radar. No costly scans or Councils; history remains readable.", "No renovar Radar. Sin exploraciones costosas ni Councils; el historial sigue disponible.")}</p><Button variant="outline" className="mt-5" onClick={selectNoRadar} disabled={noRadar.isPending}>{t("Continuar sem Radar", "Continue without Radar", "Continuar sin Radar")}</Button></div></div>
      <p className="text-[10px] text-muted-foreground flex gap-1"><Info className="h-3 w-3"/>{t("O adicional War Room mantém sua natureza de janela separada de 30 dias e não troca o pacote base.", "The War Room add-on remains a separate 30-day window and does not replace the base package.", "El complemento War Room sigue siendo una ventana independiente de 30 días y no sustituye el paquete base.")}</p>
    </section>
  </div>;
}

function Usage({ icon: Icon, label, used, total }: any) { const pct = Math.min(100, Math.round((used / total) * 100)); return <div className="border border-border/50 p-4"><div className="flex gap-2 text-xs text-muted-foreground"><Icon className="h-4 w-4 text-primary"/>{label}</div><div className="mt-3 font-mono text-xl">{used}<span className="text-xs text-muted-foreground"> / {total}</span></div><div className="h-1 mt-2 bg-muted"><div className="h-full bg-primary" style={{ width: `${pct}%` }}/></div></div> }
function paymentStatusLabel(value: string, t: ReturnType<typeof useUiText>) { const labels: Record<string, [string, string, string]> = { pending: ["Pendente", "Pending", "Pendiente"], processing: ["Processando", "Processing", "Procesando"], confirmed: ["Confirmado", "Confirmed", "Confirmado"], fulfilled: ["Concluído", "Fulfilled", "Completado"], overdue: ["Vencido", "Overdue", "Vencido"], expired: ["Expirado", "Expired", "Caducado"], cancelled: ["Cancelado", "Cancelled", "Cancelado"] }; return labels[value] ? t(...labels[value]!) : value; }
function Stat({ label, value }: { label: string; value: string }) { return <div className="border border-border/50 p-3 flex justify-between"><span className="text-muted-foreground">{label}</span><span className="font-mono text-right">{value}</span></div> }
function Package({ pkg, currency, active, onChoose, loading, locale, t }: { pkg: any; currency: "BRL" | "USD"; active: boolean; onChoose: () => void; loading: boolean; locale: string; t: ReturnType<typeof useUiText> }) { const war = pkg.package === "WAR_ROOM"; return <div className={`border p-5 flex flex-col ${war ? "border-amber-500/50" : "border-border/50"}`}><div className="flex justify-between"><h4 className="font-mono text-sm">{pkg.name}</h4>{war && <Badge variant="outline" className="text-amber-500 border-amber-500/30">{t("ADICIONAL", "ADD-ON", "COMPLEMENTO")}</Badge>}</div><p className="font-mono text-xl mt-3">{price(pkg.prices[currency], currency, locale)}</p><p className="text-[10px] text-muted-foreground">{war ? t("por janela de 30 dias", "per 30-day window", "por ventana de 30 días") : t("por 30 dias", "per 30 days", "por 30 días")}</p><ul className="text-xs text-muted-foreground mt-4 space-y-1 flex-1"><li>{pkg.limits.monitoredCampaigns} {t("campanhas", "campaigns", "campañas")} · {pkg.limits.competitors} {t("concorrentes", "competitors", "competidores")}</li><li>{pkg.limits.regions} {t("regiões", "regions", "regiones")} · {pkg.limits.councilRuns} {t("Councils", "Councils", "Councils")}</li><li>{cadence(pkg.limits.scanCadenceMinutes, t)} · {pkg.limits.retentionDays} {t("dias de retenção", "days retention", "días de retención")}</li></ul><Button className="mt-5" variant={war ? "default" : "outline"} disabled={active || loading} onClick={onChoose}>{active ? t("Pacote atual", "Current package", "Paquete actual") : currency === "BRL" ? t("Escolher e pagar", "Choose and pay", "Elegir y pagar") : t("Solicitar comercial", "Contact sales", "Solicitar atención comercial")}</Button></div> }