import { Router, type IRouter } from "express";
import healthRouter from "./health.js";
import authRouter from "../modules/auth/auth.routes.js";
import creditsRouter from "../modules/credits/credits.routes.js";
import plansRouter from "../modules/plans/plans.routes.js";
import workspacesRouter from "../modules/workspaces/workspaces.routes.js";
import campaignsRouter from "../modules/campaigns/campaigns.routes.js";
import intakeRouter from "../modules/intake/intake.routes.js";
import agentsRouter from "../modules/agents/agents.routes.js";
import directChatRouter from "../modules/agents/direct-chat.routes.js";
import contentRouter from "../modules/content/content.routes.js";
import metricsRouter from "../modules/metrics/metrics.routes.js";
import executionRouter from "../modules/orchestration/execution.routes.js";
import memoryRouter from "../modules/memory/memory.routes.js";
import socialRouter from "../modules/social/social.routes.js";
import billingRouter from "../modules/billing/billing.routes.js";
import revenueRouter from "../modules/revenue/revenue.routes.js";
import agencyRouter from "../modules/agency/agency.routes.js";
import whitelabelRouter from "../modules/whitelabel/whitelabel.routes.js";
import complianceRouter from "../modules/compliance/compliance.routes.js";
import launchSequenceRouter from "../modules/launch-sequence/launch-sequence.routes.js";
import vslRouter from "../modules/vsl/vsl.routes.js";
import emailDispatchRouter from "../modules/email-dispatch/email-dispatch.routes.js";
import whatsappRouter from "../modules/whatsapp/whatsapp.routes.js";
import leadCaptureRouter from "../modules/launch-sequence/lead-capture.routes.js";
import waitlistRouter from "../modules/waitlist/waitlist.routes.js";
import checkoutRouter from "../modules/checkout/checkout.routes.js";
import recordingRouter from "../modules/recording/recording.routes.js";
import adminRouter from "../modules/admin/admin.routes.js";
import onboardingRouter from "../modules/onboarding/onboarding.routes.js";
import weeklyReportRouter from "../modules/weekly-report/weekly-report.routes.js";
import demoRouter from "../modules/demo/demo.routes.js";
import clientProfilesRouter from "../modules/client-profiles/client-profiles.routes.js";
import simulatorRouter from "../modules/simulator/simulator.routes.js";
import serverEventsRouter from "../modules/server-events/server-events.routes.js";
import oauthRouter from "../modules/integrations/oauth.routes.js";
import socialModerationRouter from "../modules/social-moderation/social-moderation.routes.js";
import creativesRouter from "../modules/creatives/creatives.routes.js";
import productCheckoutRouter from "../modules/product-checkout/product-checkout.routes.js";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/auth", authRouter);
router.use("/credits", creditsRouter);
router.use("/plans", plansRouter);
router.use("/workspaces", workspacesRouter);
router.use("/campaigns", campaignsRouter);
router.use("/intake", intakeRouter);
router.use("/campaigns", agentsRouter);
router.use("/agents", directChatRouter);
router.use("/campaigns", contentRouter);
router.use("/campaigns", metricsRouter);
router.use("/campaigns", executionRouter);
router.use("/memory", memoryRouter);
router.use("/social", socialRouter);
router.use("/billing", billingRouter);
router.use("/revenue", revenueRouter);
router.use("/agency", agencyRouter);
router.use("/whitelabel", whitelabelRouter);
router.use("/compliance", complianceRouter);
router.use("/launch-sequences", launchSequenceRouter);
router.use("/vsls", vslRouter);
router.use("/email-dispatch", emailDispatchRouter);
router.use("/whatsapp", whatsappRouter);
router.use("/lead-capture", leadCaptureRouter);
router.use("/waitlist", waitlistRouter);
router.use("/checkout", checkoutRouter);
router.use("/recordings", recordingRouter);
router.use("/admin", adminRouter);
router.use("/onboarding", onboardingRouter);
router.use("/reports", weeklyReportRouter);
router.use("/demo", demoRouter);
router.use("/client-profiles", clientProfilesRouter);
router.use("/simulator", simulatorRouter);
router.use("/events", serverEventsRouter);
router.use("/integrations/oauth", oauthRouter);
router.use("/social-moderation", socialModerationRouter);
router.use("/campaigns", creativesRouter);
router.use("/products", productCheckoutRouter);

export default router;
