import { eq, desc, and, gte, lte, ilike, sql, type SQL } from "drizzle-orm";
import {
  db,
  campaignAgentsTable,
  approvalCheckpointsTable,
  creditTransactionsTable,
  workspacesTable,
  usersTable,
  auditLogsTable,
  agentExecutionLogsTable,
  agentClarificationRequestsTable,
  type CampaignAgent,
} from "@workspace/db";
import { completeWithAgent, type AgentRole, type AIMessage } from "../ai-gateway/ai-gateway.service.js";
import { routedComplete } from "../ai-gateway/llm-router.js";
import {
  emitAgentStarted,
  emitAgentThinking,
  emitAgentCompleted,
  emitCheckpointCreated,
  emitCampaignEvent,
  emitClarificationNeeded,
} from "../realtime/realtime.service.js";
import { InsufficientCreditsError } from "../../lib/errors.js";
import { env } from "../../lib/env.js";
import { DOMINO_CORE_PREAMBLE, DOMINO_SELF_CRITIC, DOMINO_PLF_SUPREMACY, DOMINO_APPLIED_FRAMEWORKS, NEXOS_AI_IDENTITY } from "./domino-core.js";
import { NEXOS_COGNITIVE_FOUNDATIONS } from "./cognitive-foundations.js";
import { NEXOS_CONSTRAINT_RESOLUTION_PROTOCOL } from "./constraint-reasoning.js";
import { EMOTIONAL_COPY_VOICE_DOCTRINE } from "./emotional-copy-voice.js";
import type { Logger } from "pino";

export interface RunAgentOptions {
  campaignId: string | null | undefined;
  workspaceId: string;
  agentRole: AgentRole;
  systemPrompt: string;
  messages: AIMessage[];
  log: Logger;
  requiresApproval?: boolean;
  checkpointType?: string;
  thinkingMessages?: string[];
  /** Campaign Memory Layer context — injected before system prompt when provided. */
  memoryContext?: string;
  /**
   * Psychological Profile block — formatted output of buildPsychologicalProfileBlock().
   * Injected between the memory layer and the agent-specific system prompt.
   * Provides the 6-map avatar synthesis (linguagem, desejo, objeção, identidade, emoção, mercado)
   * so every agent operates with full psychological context, not just raw intake fields.
   */
  profileContext?: string;
  /**
   * Dynamic Avatar State block — phase-specific emotional state for this content piece.
   * Generated by buildPhaseStateBlock() (single phase) or buildArcOverviewBlock() (all phases).
   * Injected between the psychological profile and the agent system prompt.
   * Tells the agent exactly WHERE in the funnel the avatar is right now — belief level,
   * resistance, dominant emotion, voice fragment, and copy directives for this phase only.
   */
  phaseContext?: string;
  /**
   * Pipeline mode: when true, drops NEXOS_COGNITIVE_FOUNDATIONS (27KB) from the
   * enriched system prompt to reduce heap usage across sequential pipeline steps.
   * DOMINO CORE and PLF SUPREMACY remain intact — only the 16-thinkers layer is omitted.
   * Use for all agents inside orchestrateCampaign(). Never use for interactive/chat agents.
   */
  pipelineMode?: boolean;
  /**
   * Skip all static layers (DOMINO, PLF, Cognitive Foundations, Constraint Reasoning,
   * Master Evolution Prompt). Reduces system prompt by ~110KB. Use ONLY for mechanical
   * JSON-output agents (e.g. sequence builder, calendar generator) that don't need
   * persuasion philosophy — just the agent's own systemPrompt and user message.
   */
  skipAllStaticLayers?: boolean;
}

export interface RunAgentResult {
  agentRecord: CampaignAgent;
  content: string;
  creditsCharged: number;
  checkpointId?: string;
}

const CHECKPOINT_TYPE_MAP: Record<string, string> = {
  strategy_approval: "strategy_approval",
  launch_plan_approval: "timeline_approval",
  creative_concept_approval: "creative_concept_approval",
  video_concept_approval: "video_concept_approval",
  landing_page_approval: "landing_page_approval",
  ad_set_approval: "ad_set_approval",
  offer_approval: "offer_approval",
  execution_approval: "execution_approval",
  budget_approval: "budget_approval",
};

/**
 * NEXOS AI — Master Evolution Prompt
 * Injetado UNIVERSALMENTE em todos os agentes antes do system prompt específico.
 * O DOMINO CORE (filosofia persuasiva central) é injetado separadamente e precede este bloco.
 * Este bloco cobre: contexto variável de mercado, critérios de qualidade, anti-alucinação,
 * pensamento sistêmico e ética operacional.
 */
const NEXOS_MASTER_EVOLUTION_PROMPT = `## NEXOS AI — PROTOCOLO DE OPERAÇÃO ESTRATÉGICA

## FÓRMULA DE LANÇAMENTO / PLF — ARQUITETURA SOBERANA

Você opera dentro da Fórmula de Lançamento (Érico Rocha) + Product Launch Formula (Jeff Walker).
Essa é a ARQUITETURA-MÃE de toda operação da NEXOS AI.

TODA literatura, framework e técnica existe para fortalecer uma etapa específica do lançamento.
Nenhum framework cria estrutura paralela ao PLF. Todos servem ao PLF.

Antes de qualquer output estratégico, identifique:
→ Qual etapa PLF está sendo servida?
→ Qual objetivo psicológico dessa etapa?
→ Qual literatura é mais eficaz para ESTA etapa específica?

Hierarquia de governança:
NÍVEL 0: Fórmula de Lançamento / PLF (governa tudo)
NÍVEL 1: Estratégia (Schwartz, Hormozi, Miller, Sutherland, Jay Abraham)
NÍVEL 2: Psicologia (Kahneman, Cialdini, Zaltman, Voss, Miner, Shotton)
NÍVEL 3: Copy/VSL/Criativos (Sugarman, Halbert, Bencivenga, Hauge, Albuquerque)
NÍVEL 4: Vendas com Impacto (Belfort, Keenan, Challenger, SPIN)
NÍVEL 5: UX/Conversão (Gardner, Laja, Fogg, Yablonski, Berger)

---

Você faz parte do sistema operacional estratégico da NEXOS AI.

Sua função NÃO é apenas responder corretamente.
Sua função é operar como um especialista estratégico real sob cenários imprevisíveis, complexos e emocionalmente variados.

### CONTEXTO VARIÁVEL — VOCÊ OPERA EM MÚLTIPLOS MERCADOS

Você pode ser acionado para qualquer combinação de:
- Mercados: fitness, finanças, beleza, SaaS, relacionamento, saúde, educação, carreira, pets, espiritualidade, música, fotografa
- Tickets: R$97 a R$50.000+
- Maturidades: primeiro produto digital / infoprodutor veterano / agência
- Avatares: jovem sem dinheiro / executivo cético / mãe sobrecarregada / especialista arrogante
- Problemas: sem prova social / nicho saturado / produto fraco / budget mínimo / audiência fria / cliente em crise emocional
- Modelos de campanha: lançamento PLF / semente / perpétuo / live de vendas / B2B consultivo

Cada contexto exige raciocínio específico. Generalidade é falha.

### CRITÉRIOS DE QUALIDADE — O QUE TE TORNA EXCELENTE

**Coerência:** Sua resposta deve ser logicamente consistente do início ao fim. Se a fase 1 diz X, a fase 3 não pode contradizer X.

**Anti-alucinação:** Nunca invente:
- Estatísticas específicas sem fonte ("93% dos cases comprovam...")
- Resultados garantidos ("isso vai triplicar suas vendas")
- Dados de conversão precisos que você não tem como saber
- Prova social que não foi fornecida no contexto

**Qualidade emocional:** Copy que parece escrita por robô não converte. Evite:
- Frases de efeito genéricas: "transforme sua vida", "descubra o segredo", "método revolucionário"
- Listas padronizadas sem narrativa
- Entusiasmo artificial desconectado da dor real do avatar

**Adaptação contextual:** Use os dados fornecidos. Mencione o mercado específico, o ticket real, a dor concreta. Uma resposta que poderia servir para qualquer negócio serve para nenhum.

**Executabilidade:** Entregue ações concretas que o usuário pode implementar hoje. Evite:
- Conselhos óbvios sem especificidade de implementação
- Estratégias que requerem 6 meses antes de qualquer resultado
- Recomendações que ignoram as restrições de budget e audiência declaradas

### O QUE VOCÊ NUNCA PODE FAZER

❌ Inventar provas ou resultados que não foram fornecidos
❌ Usar urgência artificial que não é real (vagas limitadas em produto digital sem limite real)
❌ Prometer resultados específicos de receita como garantidos
❌ Ignorar restrições legais ou éticas do mercado do cliente (CFM, OAB, ANVISA, CONAR, LGPD)
❌ Tratar todos os mercados iguais (fitness ≠ financeiro ≠ saúde ≠ B2B)
❌ Gerar copy genérica que poderia ser usada por qualquer concorrente
❌ Ignorar o nível de maturidade e sofisticação do avatar
❌ Criar estratégias que o cliente claramente não tem condições de executar

### O QUE VOCÊ SEMPRE DEVE FAZER

✅ Questionar premissas ruins antes de seguir (produto problemático = recusar e redirecionar)
✅ Detectar gargalos reais no cenário apresentado
✅ Identificar e nomear o risco principal antes de apresentar a solução
✅ Simplificar complexidade sem perder profundidade
✅ Adaptar tom e linguagem ao mercado (técnico para SaaS, emocional para autoconhecimento)
✅ Considerar psicologia do comportamento de compra do avatar específico
✅ Pensar em consequências de longo prazo, não só no resultado imediato

### PENSAMENTO SISTÊMICO OBRIGATÓRIO

Ao gerar qualquer recomendação, pense simultaneamente em:
- **Experiência:** o que o comprador sente em cada etapa?
- **Retenção:** o que faz ele ficar e recomendar?
- **LTV:** como essa ação impacta o valor vitalício do cliente?
- **Sustentabilidade:** isso funciona em 6 meses ou queima a audiência?
- **Risco financeiro:** o cliente tem recursos para executar isso?

### QUANDO EM DÚVIDA

Prefira sempre:
- Clareza > complexidade impressionante
- Verdade > hype que converte no curto prazo
- Lógica > espetáculo emocional
- Estratégia executável > plano perfeito inexequível
- Especificidade > generalidade

---

## SISTEMA DE CLARIFICAÇÃO INTELIGENTE — PROTOCOLO DE FEEDBACK LOOP

Você tem a capacidade de solicitar informações adicionais ao usuário quando o briefing apresentar lacunas que impactem materialmente a qualidade do output.

### QUANDO USAR
Inclua \`__clarifications\` no seu JSON APENAS quando:
- Uma informação ausente mudaria materialmente a estratégia ou copy
- O briefing tem contradições que precisam de resolução
- Um dado específico (preço, data, nome) é crítico e não foi fornecido
- O avatar está vago ao ponto de impossibilitar personalização real

### NUNCA USE quando:
- Você consegue inferir com alta confiança a partir do contexto
- A lacuna é cosmética e não muda o output
- Você já tem informação suficiente para gerar algo de qualidade

### FORMATO — adicione ao JSON do seu output normal:
{
  "seuOutputNormal": "...",
  "__clarifications": [
    {
      "question": "Qual é o preço do produto principal?",
      "options": ["Abaixo de R$197", "R$197–R$497", "R$497–R$997", "Acima de R$997"],
      "context": "O mecanismo de escassez varia significativamente por faixa de preço",
      "isBriefingGap": true,
      "severity": "blocking"
    }
  ]
}

severity: "blocking" = sem isso o output é genérico | "normal" = melhora significativamente | "nice_to_have" = refinamento leve
isBriefingGap: true = informação que deveria estar no intake (lacuna no briefing)
REGRA: Máximo de 3 clarifications por run. Priorize as mais impactantes.

---

`;

/**
 * Self-Critic Mode — sufixo universal injetado em todos os agentes.
 * Instrui o agente a realizar uma revisão mental ANTES de formatar a resposta final.
 * Para agentes JSON: a revisão é mental e não aparece no output.
 * Para agentes de chat direto: pode indicar revisão de forma concisa se relevante.
 */
const NEXOS_SELF_CRITIC_SUFFIX = `

---
## AUTO-REVISÃO OBRIGATÓRIA ANTES DE RESPONDER

Antes de formatar sua resposta final, execute mentalmente este checklist:

□ Minha resposta está adaptada ao contexto específico fornecido (mercado, ticket, avatar, budget)?
□ Afirmei algo que não foi validado pelos dados fornecidos (alucinação)?
□ Usei frases genéricas que qualquer concorrente poderia copiar?
□ Minha recomendação é executável com os recursos declarados (budget, audiência, maturidade)?
□ Há algum risco legal, ético ou regulatório que preciso sinalizar?
□ Minha resposta parece escrita por um humano especialista ou por um template?
□ O que propus é sustentável no longo prazo ou queima o ativo mais valioso do cliente?

Se qualquer resposta for "sim" para os problemas (alucinação, genérico, inexequível, risco ético):
→ Corrija ANTES de entregar.
→ Se o produto ou estratégia tem problema ético real: sinalize explicitamente e proponha alternativa.

A NexOS AI opera com integridade estratégica. Entregue o que você entregaria se seu nome estivesse assinado no resultado.
`;

/** Returns a temporal context block that is prepended to every agent system prompt. */
function buildTemporalContextBlock(): string {
  const now = new Date();
  const dateStr = now.toLocaleDateString("pt-BR", {
    weekday: "long",
    year: "numeric",
    month: "long",
    day: "numeric",
    timeZone: "America/Sao_Paulo",
  });
  // BRT-correct ISO date (en-CA gives YYYY-MM-DD format)
  // Using UTC date causes a 1-day error between 21h–00h BRT (UTC-3)
  const isoDate = now.toLocaleDateString("en-CA", { timeZone: "America/Sao_Paulo" });
  const timeBRT = now.toLocaleTimeString("pt-BR", {
    hour: "2-digit",
    minute: "2-digit",
    timeZone: "America/Sao_Paulo",
  });
  return `## CONTEXTO TEMPORAL OBRIGATÓRIO

**Data de hoje:** ${dateStr} (${isoDate}) — ${timeBRT} BRT
**Fuso horário de referência:** America/Sao_Paulo (BRT = UTC-3)

> REGRA CRÍTICA: Todas as datas, cronogramas, timelines e planos de lançamento que você gerar DEVEM ser iguais ou posteriores a ${isoDate}. NUNCA sugira datas passadas. Se precisar de uma data de início, use a data de hoje como Dia 1.

---

`;
}

/** Extract confidence/risk scores from parsed agent JSON output (best-effort). */
function extractScores(content: string): { confidenceScore?: number; riskScore?: number } {
  try {
    const raw = content.match(/\{[\s\S]*\}/)?.[0] ?? "";
    const parsed = raw ? (JSON.parse(raw) as Record<string, unknown>) : {};
    const conf = typeof parsed["confidenceScore"] === "number" ? parsed["confidenceScore"] : undefined;
    const risk = typeof parsed["riskScore"] === "number" ? parsed["riskScore"] : undefined;
    return { confidenceScore: conf, riskScore: risk };
  } catch {
    return {};
  }
}

/** Build a short plain-text summary of a messages array (≤300 chars). */
function buildInputSummary(messages: AIMessage[]): string {
  const last = messages[messages.length - 1];
  if (!last) return "";
  const text = typeof last.content === "string" ? last.content : JSON.stringify(last.content);
  return text.slice(0, 300).replace(/\s+/g, " ").trim();
}

// ── Agent Clarification: parse __clarifications from LLM output ───────────────
interface ClarificationItem {
  question: string;
  options?: string[];
  context?: string;
  isBriefingGap?: boolean;
  severity?: "blocking" | "normal" | "nice_to_have";
}

async function processClarificationsFromContent(
  content: string,
  campaignId: string | null,
  workspaceId: string,
  agentRole: string,
  log: import("pino").Logger,
): Promise<void> {
  try {
    const raw = content.match(/\{[\s\S]*\}/)?.[0] ?? "";
    if (!raw) return;
    const parsed = JSON.parse(raw) as Record<string, unknown>;
    const clarifications = parsed["__clarifications"];
    if (!Array.isArray(clarifications) || clarifications.length === 0) return;

    for (const item of clarifications as ClarificationItem[]) {
      if (!item?.question) continue;
      const [inserted] = await db
        .insert(agentClarificationRequestsTable)
        .values({
          campaignId: campaignId ?? undefined,
          workspaceId,
          agentRole,
          question: item.question,
          options: item.options ?? null,
          context: item.context ?? null,
          isBriefingGap: item.isBriefingGap ?? false,
          severity: item.severity ?? "normal",
          status: "pending",
        })
        .returning();

      if (inserted && campaignId) {
        emitClarificationNeeded(
          campaignId,
          inserted.id,
          agentRole,
          item.question,
          item.options ?? null,
          item.context ?? null,
          item.isBriefingGap ?? false,
          item.severity ?? "normal",
        );
      }
      log.info({ agentRole, campaignId, question: item.question }, "Clarification request stored");
    }
  } catch {
    // Non-blocking: clarification parsing failures never stop agent execution
  }
}

// ── Build answered-clarifications context block ───────────────────────────────
export async function buildClarificationContextBlock(campaignId: string): Promise<string> {
  try {
    const answered = await db
      .select()
      .from(agentClarificationRequestsTable)
      .where(
        and(
          eq(agentClarificationRequestsTable.campaignId, campaignId),
          eq(agentClarificationRequestsTable.status, "answered"),
        ),
      );
    if (answered.length === 0) return "";
    const lines = answered.map(
      (r) => `- ${r.agentRole} perguntou: "${r.question}" → Usuário respondeu: "${r.answer}"`,
    );
    return `\n## RESPOSTAS DO USUÁRIO ÀS PERGUNTAS DOS AGENTES\n\nOs agentes anteriores solicitaram as seguintes informações e o usuário respondeu:\n\n${lines.join("\n")}\n\nUse estas respostas para aprimorar sua geração. Elas preenchem lacunas do Briefing inicial.\n\n`;
  } catch {
    return "";
  }
}

// ── Global pipeline mode flag ─────────────────────────────────────────────────
// Set to true by command.agent.ts during orchestrateCampaign execution.
// Affects ALL runAgent() calls in this process during the active pipeline window,
// including profile_builder, strategy, offer, and all downstream agents.
let _globalPipelineMode = false;

/** Enable or disable pipeline mode globally for all in-flight agent calls. */
export function setPipelineMode(active: boolean): void {
  _globalPipelineMode = active;
}

// ── Cached static system prompt layers ───────────────────────────────────────
// Computed ONCE at module load. All concurrent agent calls share these string
// references instead of reallocating ~130KB on every runAgent() invocation.
// This alone eliminates the primary source of heap pressure in sequential pipelines.
const _STATIC_PROMPT_LAYERS =
  NEXOS_AI_IDENTITY +          // 0. Identidade central NEXOS — o que somos e nosso diferencial
  DOMINO_PLF_SUPREMACY +
  DOMINO_CORE_PREAMBLE +
  DOMINO_APPLIED_FRAMEWORKS +
  EMOTIONAL_COPY_VOICE_DOCTRINE +
  NEXOS_COGNITIVE_FOUNDATIONS +
  NEXOS_CONSTRAINT_RESOLUTION_PROTOCOL +
  NEXOS_MASTER_EVOLUTION_PROMPT;

// Pipeline-mode variant: drops NEXOS_COGNITIVE_FOUNDATIONS (27KB) per call.
// Saves ~270KB across a 10-agent pipeline. DOMINO + PLF remain fully intact.
const _PIPELINE_PROMPT_LAYERS =
  NEXOS_AI_IDENTITY +          // 0. Identidade central NEXOS — o que somos e nosso diferencial
  DOMINO_PLF_SUPREMACY +
  DOMINO_CORE_PREAMBLE +
  DOMINO_APPLIED_FRAMEWORKS +
  EMOTIONAL_COPY_VOICE_DOCTRINE +
  NEXOS_CONSTRAINT_RESOLUTION_PROTOCOL +
  NEXOS_MASTER_EVOLUTION_PROMPT;

export async function runAgent(opts: RunAgentOptions): Promise<RunAgentResult> {
  const {
    campaignId,
    workspaceId,
    agentRole,
    systemPrompt,
    messages,
    log,
    requiresApproval = false,
    checkpointType,
    thinkingMessages = [],
  } = opts;

  // Always inject current date so agents never suggest past dates.
  // If Campaign Memory Layer context is provided, inject it after the temporal block
  // so every agent reads the source of truth before generating any output.
  const memoryBlock = opts.memoryContext
    ? opts.memoryContext
    : "";
  // Universal injection order:
  // 1. Temporal context (date awareness)
  // 2. PLF SUPREMACY (Fórmula de Lançamento governa toda a arquitetura — NÍVEL 0)
  // 3. DOMINO CORE (philosophical persuasion engine — governs ALL communication)
  // 4. NEXOS Applied Frameworks + Cognitive Foundations (16 thinkers, 5 pillars)
  // 4.5. CONSTRAINT RESOLUTION PROTOCOL (pre-response structural reasoning — camada zero)
  // 5. NEXOS Master Evolution Prompt (quality criteria, anti-hallucination, ethics)
  // 6. Campaign Memory Layer (workspace-specific context)
  // 7. Psychological Profile (6-map avatar synthesis — bridges intake → agent pipeline)
  // 8. Dynamic Avatar State (phase-specific emotional state — where in the funnel right now)
  // 9. Agent-specific system prompt (role expertise)
  // 10. DOMINO Self-Critic (mandatory pre-output review checklist)
  const profileBlock = opts.profileContext ?? "";
  const phaseBlock = opts.phaseContext ?? "";
  // Use cached static layers (pre-computed at module load — avoids 130KB realloc per call).
  // Pipeline mode drops COGNITIVE_FOUNDATIONS (27KB) to reduce heap across 10+ sequential calls.
  // skipAllStaticLayers drops ALL ~110KB philosophy layers for mechanical JSON-output agents.
  let enrichedSystemPrompt: string;
  if (opts.skipAllStaticLayers) {
    // Mechanical agent: just temporal context + optional memory/profile + agent system prompt.
    // No DOMINO, no PLF, no cognitive foundations, no constraint reasoning.
    enrichedSystemPrompt =
      buildTemporalContextBlock() +
      memoryBlock +
      systemPrompt;
  } else {
    const staticLayers = (opts.pipelineMode || _globalPipelineMode) ? _PIPELINE_PROMPT_LAYERS : _STATIC_PROMPT_LAYERS;
    enrichedSystemPrompt =
      buildTemporalContextBlock() +
      staticLayers +
      memoryBlock +
      profileBlock +
      phaseBlock +
      systemPrompt +
      DOMINO_SELF_CRITIC;
  }

  const [ws] = await db
    .select({
      creditsBalance: workspacesTable.creditsBalance,
      ownerId: workspacesTable.ownerId,
    })
    .from(workspacesTable)
    .where(eq(workspacesTable.id, workspaceId))
    .limit(1);

  // Look up owner locale so every agent respects the user's language setting
  let ownerLocale: string | undefined;
  if (ws?.ownerId) {
    const [ownerRow] = await db
      .select({ locale: usersTable.locale })
      .from(usersTable)
      .where(eq(usersTable.id, ws.ownerId))
      .limit(1);
    ownerLocale = ownerRow?.locale ?? undefined;
  }

  const MIN_CREDITS_REQUIRED = 5;
  if (!ws || ws.creditsBalance < MIN_CREDITS_REQUIRED) {
    throw new InsufficientCreditsError(MIN_CREDITS_REQUIRED, ws?.creditsBalance ?? 0);
  }

  // Only insert into campaign_agents when we have a real UUID campaign ID
  const isValidCampaignId = campaignId && /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(campaignId);

  let agentRecord: CampaignAgent | undefined;
  if (isValidCampaignId) {
    const [inserted] = await db
      .insert(campaignAgentsTable)
      .values({
        campaignId: campaignId as string,
        agentType: agentRole as any,
        status: "running",
        startedAt: new Date(),
      })
      .returning();
    agentRecord = inserted;
  }

  // ── Audit Log: insert "started" row ──────────────────────────────────────────
  const execLogStartedAt = new Date();
  let execLogId: string | undefined;
  try {
    const [execLog] = await db
      .insert(agentExecutionLogsTable)
      .values({
        campaignId: isValidCampaignId ? (campaignId as string) : undefined,
        workspaceId,
        userId: ws.ownerId ?? undefined,
        agentName: agentRole,
        actionType: `agent.${agentRole}.run`,
        inputSummary: buildInputSummary(messages),
        approvalRequired: requiresApproval,
        approvalStatus: "not_required",
        executionStatus: "started",
        isDryRun: env.DRY_RUN_MODE,
        startedAt: execLogStartedAt,
      })
      .returning({ id: agentExecutionLogsTable.id });
    execLogId = execLog?.id;
  } catch (logErr) {
    log.error(
      {
        err: logErr,
        agentRole,
        workspaceId,
        campaignId: isValidCampaignId ? campaignId : null,
        stack: logErr instanceof Error ? logErr.stack : undefined,
      },
      "AUDIT_LOG_INSERT_FAILED: exec_log start row insert threw — investigate DB constraint or schema mismatch",
    );
  }

  log.info({ campaignId, workspaceId, agentRole, isDryRun: env.DRY_RUN_MODE }, `Agent ${agentRole} started`);

  emitAgentStarted(campaignId ?? "system", agentRole);

  for (const thought of thinkingMessages) {
    emitAgentThinking(campaignId ?? "system", agentRole, thought);
    await sleep(350);
  }

  let content = "";
  let creditsCharged = 0;

  // Detect provider auth errors (no API key configured) for graceful dev fallback
  function isProviderAuthError(err: unknown): boolean {
    const msg = err instanceof Error ? err.message : String(err);
    return (
      msg.includes("Could not resolve authentication method") ||
      msg.includes("API key") ||
      msg.includes("Incorrect API key") ||
      msg.includes("OPENAI_API_KEY") ||
      msg.includes("ANTHROPIC_API_KEY") ||
      msg.includes("GEMINI_API_KEY")
    );
  }

  // ── DRY_RUN_MODE: skip real AI call ──────────────────────────────────────────
  if (env.DRY_RUN_MODE) {
    content = JSON.stringify({
      _dryRun: true,
      agentRole,
      message: `[DRY_RUN] Agente ${agentRole} simulado — nenhuma chamada real foi feita`,
      confidenceScore: 0.85,
      riskScore: 15,
      timestamp: new Date().toISOString(),
    });

    log.info({ agentRole, campaignId }, `[DRY_RUN] Agent ${agentRole} simulated`);

    if (agentRecord) {
      await db
        .update(campaignAgentsTable)
        .set({
          status: "completed",
          output: { content, metadata: { dryRun: true } },
          completedAt: new Date(),
          creditsUsed: 0,
        })
        .where(eq(campaignAgentsTable.id, agentRecord.id));
    }

    // Persist dry-run execution log
    if (execLogId) {
      await db
        .update(agentExecutionLogsTable)
        .set({
          executionStatus: "dry_run",
          outputSummary: `[DRY_RUN] Simulado com sucesso — sem chamada real`,
          confidenceScore: 0.85,
          riskScore: 15,
          approvalStatus: requiresApproval ? "pending" : "not_required",
          completedAt: new Date(),
        })
        .where(eq(agentExecutionLogsTable.id, execLogId));
    }

    emitAgentCompleted(campaignId ?? "system", agentRole, `${agentRole} simulado (DRY_RUN)`);

    if (agentRecord) {
      const [updated] = await db
        .select()
        .from(campaignAgentsTable)
        .where(eq(campaignAgentsTable.id, agentRecord.id))
        .limit(1);
      return { agentRecord: updated!, content, creditsCharged: 0 };
    }
    return {
      agentRecord: { id: "none", campaignId: null, agentType: agentRole, status: "completed" } as unknown as CampaignAgent,
      content,
      creditsCharged: 0,
    };
  }

  try {
    const result = await routedComplete(
      agentRole,
      enrichedSystemPrompt,
      messages,
      workspaceId,
      log,
      campaignId ?? undefined,
      ownerLocale,
    );

    content = result.content;
    creditsCharged = result.creditsCharged;

    const balanceBefore = ws.creditsBalance;
    const balanceAfter = Math.max(0, balanceBefore - creditsCharged);

    if (creditsCharged > 0) {
      await db
        .update(workspacesTable)
        .set({ creditsBalance: balanceAfter })
        .where(eq(workspacesTable.id, workspaceId));

      await db.insert(creditTransactionsTable).values({
        workspaceId,
        campaignId,
        type: "debit",
        action: "campaign_execution",
        amount: creditsCharged,
        balanceBefore,
        balanceAfter,
        aiProvider: result.provider,
        tokensUsed: result.inputTokens + result.outputTokens,
        costUsd: result.costUsd.toString(),
      });
    }

    const newStatus = requiresApproval ? "waiting_approval" : "completed";

    if (agentRecord) {
      await db
        .update(campaignAgentsTable)
        .set({
          status: newStatus,
          output: {
            content,
            metadata: {
              creditsCharged,
              provider: result.provider,
              model: result.model,
            },
          },
          completedAt: new Date(),
          creditsUsed: creditsCharged,
          tokensUsed: result.inputTokens + result.outputTokens,
          aiProvider: result.provider,
          model: result.model,
        })
        .where(eq(campaignAgentsTable.id, agentRecord.id));

      await db.insert(auditLogsTable).values({
        workspaceId,
        campaignId: isValidCampaignId ? (campaignId as string) : undefined,
        agentId: agentRecord.id,
        action: `agent.${agentRole}.completed`,
        actor: "system",
        data: { creditsCharged, provider: result.provider },
      });
    }

    // ── Audit Log: update execution log with results ──────────────────────────
    const scores = extractScores(content);
    if (execLogId) {
      await db
        .update(agentExecutionLogsTable)
        .set({
          executionStatus: "completed",
          outputSummary: content.slice(0, 500).replace(/\s+/g, " ").trim(),
          confidenceScore: scores.confidenceScore,
          riskScore: scores.riskScore,
          approvalRequired: requiresApproval,
          approvalStatus: requiresApproval ? "pending" : "not_required",
          providerUsed: result.provider,
          modelUsed: result.model,
          tokensUsed: result.inputTokens + result.outputTokens,
          estimatedCostUsd: result.costUsd,
          completedAt: new Date(),
        })
        .where(eq(agentExecutionLogsTable.id, execLogId));
    }

    log.info(
      {
        campaignId,
        agentRole,
        creditsCharged,
        provider: result.provider,
        model: result.model,
        tokens: result.inputTokens + result.outputTokens,
        costUsd: result.costUsd,
        requiresApproval,
        durationMs: Date.now() - execLogStartedAt.getTime(),
      },
      `Agent ${agentRole} completed`,
    );

    let checkpointId: string | undefined;

    if (requiresApproval && checkpointType && isValidCampaignId && agentRecord) {
      const mappedType = (CHECKPOINT_TYPE_MAP[checkpointType] ?? "execution_approval") as
        | "strategy_approval"
        | "timeline_approval"
        | "creative_concept_approval"
        | "video_concept_approval"
        | "video_preview_approval"
        | "landing_page_approval"
        | "ad_set_approval"
        | "targeting_approval"
        | "offer_approval"
        | "execution_approval"
        | "budget_approval";

      const [checkpoint] = await db
        .insert(approvalCheckpointsTable)
        .values({
          campaignId: campaignId as string,
          checkpointType: mappedType,
          status: "pending",
          data: { content: content.slice(0, 4000), agentRole, agentId: agentRecord.id },
        })
        .returning();

      checkpointId = checkpoint.id;

      emitCheckpointCreated(campaignId as string, checkpointType, {
        checkpointId: checkpoint.id,
        agentRole,
        contentPreview: content.slice(0, 300),
      });
    }

    await processClarificationsFromContent(
      content,
      campaignId ?? null,
      workspaceId,
      agentRole,
      log,
    );

    emitAgentCompleted(
      campaignId ?? "system",
      agentRole,
      `${agentRole} concluído — ${creditsCharged} créditos utilizados`,
    );

    if (agentRecord) {
      const [updated] = await db
        .select()
        .from(campaignAgentsTable)
        .where(eq(campaignAgentsTable.id, agentRecord.id))
        .limit(1);
      return { agentRecord: updated, content, creditsCharged, checkpointId };
    }

    // No campaign_agents record (sequence-level agent) — return synthetic record
    return {
      agentRecord: { id: "none", campaignId: null, agentType: agentRole, status: "completed" } as unknown as CampaignAgent,
      content,
      creditsCharged,
      checkpointId,
    };
  } catch (err) {
    // Graceful degradation when AI provider is not configured (dev environment)
    if (isProviderAuthError(err)) {
      log.warn({ agentRole, campaignId }, "AI provider not configured — returning mock response for dev");

      content = `[DEV MODE — ${agentRole}] Resposta simulada. Configure as chaves de API (ANTHROPIC_API_KEY, OPENAI_API_KEY, GEMINI_API_KEY) para respostas reais.`;

      if (agentRecord) {
        await db
          .update(campaignAgentsTable)
          .set({
            status: "completed",
            output: { content, metadata: { mock: true, reason: "no_api_key" } },
            completedAt: new Date(),
            creditsUsed: 0,
          })
          .where(eq(campaignAgentsTable.id, agentRecord.id));
      }

      if (execLogId) {
        await db
          .update(agentExecutionLogsTable)
          .set({
            executionStatus: "completed",
            outputSummary: "[DEV MODE] Resposta simulada — sem API key",
            providerUsed: "mock",
            completedAt: new Date(),
          })
          .where(eq(agentExecutionLogsTable.id, execLogId));
      }

      emitAgentCompleted(campaignId ?? "system", agentRole, `${agentRole} simulado (dev mode — sem API key)`);

      if (agentRecord) {
        const [updated] = await db
          .select()
          .from(campaignAgentsTable)
          .where(eq(campaignAgentsTable.id, agentRecord.id))
          .limit(1);
        return { agentRecord: updated!, content, creditsCharged: 0 };
      }

      return {
        agentRecord: { id: "none", campaignId: null, agentType: agentRole, status: "completed" } as unknown as CampaignAgent,
        content,
        creditsCharged: 0,
      };
    }

    // Real error — update execution log and campaign agent
    const errMsg = err instanceof Error ? err.message : String(err);
    log.error({ err, campaignId, agentRole }, `Agent ${agentRole} failed`);

    if (execLogId) {
      await db
        .update(agentExecutionLogsTable)
        .set({
          executionStatus: "failed",
          errorMessage: errMsg.slice(0, 1000),
          completedAt: new Date(),
        })
        .where(eq(agentExecutionLogsTable.id, execLogId));
    }

    if (agentRecord) {
      await db
        .update(campaignAgentsTable)
        .set({
          status: "failed",
          errorMessage: errMsg,
          completedAt: new Date(),
        })
        .where(eq(campaignAgentsTable.id, agentRecord.id));
    }

    emitCampaignEvent({
      campaignId: campaignId ?? "system",
      type: "agent_failed",
      agentType: agentRole,
      message: `${agentRole} falhou: ${errMsg}`,
      timestamp: new Date().toISOString(),
    });

    throw err;
  }
}

// ─── Query helpers (used by admin audit routes) ───────────────────────────────

export interface AuditLogFilter {
  campaignId?: string;
  agentName?: string;
  executionStatus?: string;
  minRiskScore?: number;
  approvalRequired?: boolean;
  dateFrom?: string;
  dateTo?: string;
  isDryRun?: boolean;
  limit?: number;
  offset?: number;
}

export async function queryAgentExecutionLogs(filter: AuditLogFilter) {
  const conditions: SQL[] = [];

  if (filter.campaignId) {
    conditions.push(eq(agentExecutionLogsTable.campaignId, filter.campaignId));
  }
  if (filter.agentName) {
    conditions.push(ilike(agentExecutionLogsTable.agentName, `%${filter.agentName}%`));
  }
  if (filter.executionStatus) {
    conditions.push(eq(agentExecutionLogsTable.executionStatus, filter.executionStatus as any));
  }
  if (filter.minRiskScore !== undefined) {
    conditions.push(gte(agentExecutionLogsTable.riskScore, filter.minRiskScore));
  }
  if (filter.approvalRequired !== undefined) {
    conditions.push(eq(agentExecutionLogsTable.approvalRequired, filter.approvalRequired));
  }
  if (filter.isDryRun !== undefined) {
    conditions.push(eq(agentExecutionLogsTable.isDryRun, filter.isDryRun));
  }
  if (filter.dateFrom) {
    conditions.push(gte(agentExecutionLogsTable.startedAt, new Date(filter.dateFrom)));
  }
  if (filter.dateTo) {
    conditions.push(lte(agentExecutionLogsTable.startedAt, new Date(filter.dateTo)));
  }

  const where = conditions.length > 0 ? and(...conditions) : undefined;

  const rows = await db
    .select()
    .from(agentExecutionLogsTable)
    .where(where)
    .orderBy(desc(agentExecutionLogsTable.startedAt))
    .limit(filter.limit ?? 50)
    .offset(filter.offset ?? 0);

  return rows;
}

export async function getAgentExecutionLogById(id: string) {
  const [row] = await db
    .select()
    .from(agentExecutionLogsTable)
    .where(eq(agentExecutionLogsTable.id, id))
    .limit(1);
  return row ?? null;
}

export async function getAgentExecutionLogsSummary() {
  const [totals] = await db
    .select({
      total: sql<number>`count(*)::int`,
      completed: sql<number>`count(*) filter (where execution_status = 'completed')::int`,
      failed: sql<number>`count(*) filter (where execution_status = 'failed')::int`,
      dryRun: sql<number>`count(*) filter (where is_dry_run = true)::int`,
      pendingApproval: sql<number>`count(*) filter (where approval_status = 'pending')::int`,
      totalTokens: sql<number>`coalesce(sum(tokens_used), 0)::int`,
      totalCostUsd: sql<number>`coalesce(sum(estimated_cost_usd), 0)`,
      avgRiskScore: sql<number>`coalesce(avg(risk_score), 0)`,
      avgConfidence: sql<number>`coalesce(avg(confidence_score), 0)`,
    })
    .from(agentExecutionLogsTable);

  const byAgent = await db
    .select({
      agentName: agentExecutionLogsTable.agentName,
      runs: sql<number>`count(*)::int`,
      failures: sql<number>`count(*) filter (where execution_status = 'failed')::int`,
      avgCostUsd: sql<number>`coalesce(avg(estimated_cost_usd), 0)`,
    })
    .from(agentExecutionLogsTable)
    .groupBy(agentExecutionLogsTable.agentName)
    .orderBy(desc(sql`count(*)`))
    .limit(20);

  return { totals: totals ?? {}, byAgent };
}

export function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

/**
 * Repairs truncated JSON by auto-closing unclosed objects/arrays/strings.
 * Handles the common case where an LLM response is cut off mid-generation.
 */
function repairTruncatedJson(raw: string): string {
  const start = raw.indexOf("{");
  if (start === -1) return raw;
  let s = raw.slice(start);

  const stack: string[] = [];
  let inString = false;
  let escaped = false;
  let lastValidEnd = 0;

  for (let i = 0; i < s.length; i++) {
    const ch = s[i]!;
    if (escaped) { escaped = false; continue; }
    if (ch === "\\" && inString) { escaped = true; continue; }
    if (ch === '"') {
      inString = !inString;
      if (!inString) lastValidEnd = i + 1;
      continue;
    }
    if (inString) continue;
    if (ch === "{" || ch === "[") { stack.push(ch); continue; }
    if (ch === "}" || ch === "]") {
      stack.pop();
      if (stack.length === 0) lastValidEnd = i + 1;
    }
  }

  // If JSON was complete, return as-is
  if (stack.length === 0) return s;

  // Truncate to last valid position if string is open (avoids broken string values)
  if (inString) s = s.slice(0, lastValidEnd) + '"';

  // Close unclosed structures in reverse order
  for (let i = stack.length - 1; i >= 0; i--) {
    s += stack[i] === "{" ? "}" : "]";
  }
  return s;
}

export function parseAgentJSON<T = Record<string, unknown>>(
  content: string,
  fallback: T,
): T {
  // ── Strategy 1: code block extraction (most reliable when LLM wraps JSON in ```) ──
  const codeBlockMatch =
    content.match(/```json\s*([\s\S]*?)```/) ??
    content.match(/```(?:json)?\s*(\{[\s\S]*)/);

  if (codeBlockMatch) {
    const c = (codeBlockMatch[1] ?? "").trim();
    try { return JSON.parse(c) as T; } catch { /* continue */ }
    try { return JSON.parse(repairTruncatedJson(c)) as T; } catch { /* continue */ }
  }

  // ── Strategy 2: scan for balanced JSON objects, prefer largest valid one ──
  // This handles the common case where the LLM adds narrative text before/after JSON.
  // We look for every `{"` occurrence (strict property start) and find its balanced close.
  let bestCandidate = "";
  let searchFrom = 0;
  while (true) {
    const start = content.indexOf('{"', searchFrom);
    if (start === -1) break;
    searchFrom = start + 1;

    // Walk forward counting braces to find the matching close
    let depth = 0;
    let end = -1;
    for (let i = start; i < content.length; i++) {
      if (content[i] === "{") depth++;
      else if (content[i] === "}") {
        depth--;
        if (depth === 0) { end = i; break; }
      }
    }
    if (end === -1) break; // unclosed — truncated; stop scanning

    const candidate = content.slice(start, end + 1);
    if (candidate.length > bestCandidate.length) {
      try {
        JSON.parse(candidate); // validate
        bestCandidate = candidate;
        // Don't break — keep scanning for a larger valid object
      } catch { /* not valid JSON at this start position */ }
    }
  }

  if (bestCandidate) {
    try { return JSON.parse(bestCandidate) as T; } catch { /* continue */ }
  }

  // ── Strategy 3: original greedy `{...}` match (last resort) ──
  const rawMatch = content.match(/\{[\s\S]*\}/) ?? content.match(/\{[\s\S]*/);
  const raw = rawMatch?.[0] ?? "";

  if (!raw.trim()) return fallback;

  try { return JSON.parse(raw) as T; } catch { /* continue */ }
  try { return JSON.parse(repairTruncatedJson(raw)) as T; } catch { return fallback; }
}

// ── Output-Judged Agent Runner ─────────────────────────────────────────────────

/**
 * runJudgedAgent — Wrapper around runAgent that automatically evaluates the
 * output quality and, if below threshold (score < 70), runs a targeted
 * refinement pass before returning.
 *
 * Only activates judge for the 5 most critical agent roles:
 * copywriter, vsl_script, offer, landing_page, hook_factory
 *
 * Non-blocking on judge/refinement failure — always returns best available result.
 */

const JUDGED_AGENT_ROLES = new Set([
  "copywriter",
  "vsl_script",
  "offer",
  "landing_page",
  "hook_factory",
]);

export interface RunJudgedAgentResult extends RunAgentResult {
  judgeScore?: number;
  wasRefined?: boolean;
  critiqueLogId?: string;
}

export async function runJudgedAgent(
  opts: RunAgentOptions,
): Promise<RunJudgedAgentResult> {
  // Run the agent normally
  const result = await runAgent(opts);

  // Only judge critical roles — skip for lightweight / governance agents
  if (!JUDGED_AGENT_ROLES.has(opts.agentRole)) {
    return result;
  }

  // Lazy-import to avoid circular deps at module load time
  const {
    judgeAgentOutput,
    buildRefinementMessage,
    saveCritiqueLog,
    APPROVAL_THRESHOLD,
    extractContextSummaryForJudge,
  } = await import("./output-judge.agent.js");

  // Build a short context summary for the judge (from memoryContext if available)
  const ctxSummary = opts.memoryContext
    ? extractContextSummaryForJudge(opts.memoryContext)
    : "";

  // ── First evaluation ────────────────────────────────────────────────────────
  const initialScore = await judgeAgentOutput({
    agentRole:             opts.agentRole,
    rawOutput:             result.content,
    campaignContextSummary: ctxSummary,
    workspaceId:           opts.workspaceId,
    campaignId:            opts.campaignId,
    iteration:             1,
    log:                   opts.log,
  });

  opts.log.info(
    { agentRole: opts.agentRole, score: initialScore.overallScore, verdict: initialScore.verdict },
    "runJudgedAgent: initial evaluation",
  );

  // Approved — no refinement needed
  if (initialScore.overallScore >= APPROVAL_THRESHOLD) {
    // Save approved critique log in background
    if (opts.campaignId && /^[0-9a-f-]{36}$/i.test(opts.campaignId)) {
      setImmediate(() => {
        saveCritiqueLog({
          workspaceId:   opts.workspaceId,
          campaignId:    opts.campaignId as string,
          agentRole:     opts.agentRole,
          iteration:     1,
          rawOutput:     result.content,
          refinedOutput: result.content,
          scoreBefore:   initialScore,
          tokensUsed:    0,
          log:           opts.log,
        }).catch(() => {/* non-fatal */});
      });
    }
    return {
      ...result,
      judgeScore:  initialScore.overallScore,
      wasRefined:  false,
    };
  }

  // ── Refinement pass ─────────────────────────────────────────────────────────
  opts.log.info(
    { agentRole: opts.agentRole, score: initialScore.overallScore },
    "runJudgedAgent: score below threshold — running refinement pass",
  );

  try {
    const refinementMessage = buildRefinementMessage(result.content, initialScore);

    // Add the critique as a new user message and re-run the agent
    const refinedMessages: typeof opts.messages = [
      ...opts.messages,
      { role: "assistant", content: result.content },
      { role: "user",      content: refinementMessage },
    ];

    const refinedResult = await runAgent({
      ...opts,
      messages: refinedMessages,
      requiresApproval: false, // No checkpoint for refinement pass
    });

    // Evaluate refined output
    const refinedScore = await judgeAgentOutput({
      agentRole:              opts.agentRole,
      rawOutput:              refinedResult.content,
      campaignContextSummary: ctxSummary,
      workspaceId:            opts.workspaceId,
      campaignId:             opts.campaignId,
      iteration:              2,
      log:                    opts.log,
    });

    opts.log.info(
      {
        agentRole:     opts.agentRole,
        scoreBefore:   initialScore.overallScore,
        scoreAfter:    refinedScore.overallScore,
        improvement:   refinedScore.overallScore - initialScore.overallScore,
      },
      "runJudgedAgent: refinement complete",
    );

    // Save critique log with delta
    let critiqueLogId: string | undefined;
    if (opts.campaignId && /^[0-9a-f-]{36}$/i.test(opts.campaignId)) {
      critiqueLogId = await saveCritiqueLog({
        workspaceId:   opts.workspaceId,
        campaignId:    opts.campaignId as string,
        agentRole:     opts.agentRole,
        iteration:     2,
        rawOutput:     result.content,
        refinedOutput: refinedResult.content,
        scoreBefore:   initialScore,
        scoreAfter:    refinedScore,
        tokensUsed:    0,
        log:           opts.log,
      });
    }

    // Return the better of the two outputs
    const useRefined = refinedScore.overallScore >= initialScore.overallScore;
    return {
      ...(useRefined ? refinedResult : result),
      judgeScore:    useRefined ? refinedScore.overallScore : initialScore.overallScore,
      wasRefined:    true,
      critiqueLogId,
    };
  } catch (refineErr) {
    opts.log.warn(
      { refineErr, agentRole: opts.agentRole },
      "runJudgedAgent: refinement pass failed — returning original output",
    );
    return {
      ...result,
      judgeScore: initialScore.overallScore,
      wasRefined: false,
    };
  }
}
