/**
 * NEXOS AI — Psychological Profile Injector
 *
 * Reads `_psychologicalProfile` from campaign intakeData (generated by
 * `generatePsychologicalProfile()` in intake.ai.ts after briefing completion)
 * and formats it as a rich, structured context block ready for injection into
 * any agent's enrichedSystemPrompt.
 *
 * This is the bridge that closes the pipeline gap:
 *   intake → _psychologicalProfile (DB) → Profile Injector → runAgent()
 */

interface PsychologicalProfile {
  linguagem?: {
    palavrasChave?: string[];
    palavrasBanidas?: string[];
    metaforasDominantes?: string[];
    tomPreferido?: string;
  };
  desejo?: {
    superficial?: string;
    real?: string;
    proibido?: string;
    identitario?: string;
  };
  objecao?: {
    principal?: string;
    secundarias?: string[];
    geradoraDeConfianca?: string;
    destruidoraDeCredibilidade?: string;
  };
  identidade?: {
    querProvar?: string;
    querEvitar?: string;
    querSeTornar?: string;
    querDeixarDeSer?: string;
  };
  emocao?: {
    dominante?: string;
    gatilhoPrincipal?: string;
    acordadaAs23h?: string;
    nuncaAdmiteEmVozAlta?: string;
  };
  mercado?: {
    inimigo?: string;
    mentiraDominante?: string;
    linguagemDominante?: string;
    maturidade?: string;
  };
  incoerencias?: string[];
  insightEstrategico?: string;
  headlinePotencial?: string;
}

/**
 * Formats the psychological profile stored in intakeData as an injected
 * context block. Returns empty string if no profile exists yet.
 */
export function buildPsychologicalProfileBlock(
  intakeData: Record<string, unknown>
): string {
  const raw = intakeData["_psychologicalProfile"];
  if (!raw || typeof raw !== "object") return "";

  const p = raw as PsychologicalProfile;
  const parts: string[] = [];

  parts.push(`## ━━━ PERFIL PSICOLÓGICO DO AVATAR ━━━`);
  parts.push(
    `> Síntese psicológica profunda gerada após o briefing. ` +
    `Representa o perfil real do avatar — não o que o produtor imagina, mas o que os dados revelaram. ` +
    `Este perfil governa TODA decisão de copy, posicionamento e estratégia.`
  );

  if (p.insightEstrategico) {
    parts.push(`\n**Insight estratégico central:** ${p.insightEstrategico}`);
  }
  if (p.headlinePotencial) {
    parts.push(`**Headline potencial derivada do perfil:** "${p.headlinePotencial}"`);
  }

  if (p.linguagem) {
    parts.push(`\n### MAPA DE LINGUAGEM`);
    if (p.linguagem.palavrasChave?.length) {
      parts.push(
        `**Palavras/frases exatas do avatar** (use no copy — são da voz DELE, não da sua): ` +
        p.linguagem.palavrasChave.join(" | ")
      );
    }
    if (p.linguagem.palavrasBanidas?.length) {
      parts.push(
        `**Palavras banidas** (NUNCA use — soam falsas ou irritantes para este avatar): ` +
        p.linguagem.palavrasBanidas.join(" | ")
      );
    }
    if (p.linguagem.metaforasDominantes?.length) {
      parts.push(
        `**Metáforas dominantes do avatar** (como ele pensa sobre o problema): ` +
        p.linguagem.metaforasDominantes.join(" | ")
      );
    }
    if (p.linguagem.tomPreferido) {
      parts.push(`**Tom preferido:** ${p.linguagem.tomPreferido}`);
    }
  }

  if (p.desejo) {
    parts.push(`\n### MAPA DE DESEJO`);
    if (p.desejo.superficial) {
      parts.push(`**Desejo declarado** (o que diz que quer): ${p.desejo.superficial}`);
    }
    if (p.desejo.real) {
      parts.push(`**Desejo real** (motivação raiz por baixo): ${p.desejo.real}`);
    }
    if (p.desejo.proibido) {
      parts.push(`**Desejo proibido** (nunca admite em voz alta — mas aparece nos detalhes): ${p.desejo.proibido}`);
    }
    if (p.desejo.identitario) {
      parts.push(`**Desejo identitário** (em quem quer se tornar através do produto): ${p.desejo.identitario}`);
    }
  }

  if (p.objecao) {
    parts.push(`\n### MAPA DE OBJEÇÃO`);
    if (p.objecao.principal) {
      parts.push(`**Objeção principal** (a que mais bloqueia a compra — destrua-a primeiro): ${p.objecao.principal}`);
    }
    if (p.objecao.secundarias?.length) {
      parts.push(`**Objeções secundárias:** ${p.objecao.secundarias.join(" | ")}`);
    }
    if (p.objecao.geradoraDeConfianca) {
      parts.push(`**O que gera confiança para ESTE avatar especificamente:** ${p.objecao.geradoraDeConfianca}`);
    }
    if (p.objecao.destruidoraDeCredibilidade) {
      parts.push(`**O que destrói credibilidade instantaneamente:** ${p.objecao.destruidoraDeCredibilidade}`);
    }
  }

  if (p.identidade) {
    parts.push(`\n### MAPA DE IDENTIDADE`);
    if (p.identidade.querProvar) {
      parts.push(`**Quer provar para si mesmo:** ${p.identidade.querProvar}`);
    }
    if (p.identidade.querEvitar) {
      parts.push(`**Quer evitar ser chamado de / percebido como:** ${p.identidade.querEvitar}`);
    }
    if (p.identidade.querSeTornar) {
      parts.push(`**Identidade aspiracional** (em quem quer se tornar): ${p.identidade.querSeTornar}`);
    }
    if (p.identidade.querDeixarDeSer) {
      parts.push(`**Identidade atual que quer abandonar:** ${p.identidade.querDeixarDeSer}`);
    }
  }

  if (p.emocao) {
    parts.push(`\n### MAPA EMOCIONAL`);
    if (p.emocao.dominante) {
      parts.push(`**Emoção dominante:** ${p.emocao.dominante}`);
    }
    if (p.emocao.gatilhoPrincipal) {
      parts.push(`**Gatilho que a ativa:** ${p.emocao.gatilhoPrincipal}`);
    }
    if (p.emocao.acordadaAs23h) {
      parts.push(`**O que o mantém acordado às 23h:** ${p.emocao.acordadaAs23h}`);
    }
    if (p.emocao.nuncaAdmiteEmVozAlta) {
      parts.push(`**O que sente mas nunca admite em voz alta:** ${p.emocao.nuncaAdmiteEmVozAlta}`);
    }
  }

  if (p.mercado) {
    parts.push(`\n### MAPA DE MERCADO`);
    if (p.mercado.inimigo) {
      parts.push(`**Inimigo do avatar** (o que/quem culpa pelo problema que ainda tem): ${p.mercado.inimigo}`);
    }
    if (p.mercado.mentiraDominante) {
      parts.push(`**Mentira dominante do mercado** (promessa que ele já aprendeu a desconfiar): ${p.mercado.mentiraDominante}`);
    }
    if (p.mercado.linguagemDominante) {
      parts.push(`**Linguagem dominante no mercado:** ${p.mercado.linguagemDominante}`);
    }
    if (p.mercado.maturidade) {
      parts.push(`**Maturidade do avatar:** ${p.mercado.maturidade}`);
    }
  }

  const validIncoerencias = (p.incoerencias ?? []).filter(Boolean);
  if (validIncoerencias.length) {
    parts.push(`\n### INCOERÊNCIAS DETECTADAS NO BRIEFING`);
    parts.push(
      validIncoerencias.map((i) => `⚠️ ${i}`).join("\n") +
      `\n→ Use essas incoerências para calibrar o posicionamento. Não confronte — clarify através do copy.`
    );
  }

  // Avatar Voice File — the crown jewel: 500-600 words written AS the avatar
  const voiceFile = intakeData["_avatarVoiceFile"];
  if (voiceFile && typeof voiceFile === "string" && voiceFile.length > 100) {
    parts.push(`\n### ARQUIVO DE VOZ DO AVATAR`);
    parts.push(
      `> Este documento foi escrito NA VOZ DO AVATAR — monólogo interno em primeira pessoa.\n` +
      `> Use as frases, expressões e emoções deste documento DIRETAMENTE no copy.\n` +
      `> Frases levantadas daqui têm conversão muito superior à copy inventada.\n` +
      `> Técnica Carlton/Kennedy: o cliente deve ler o copy e pensar "como você sabia exatamente o que eu sinto?"`
    );
    parts.push(`\n${voiceFile}`);
    parts.push(``);
  }

  parts.push(
    `\n> **INSTRUÇÃO CRÍTICA ANTES DE ESCREVER QUALQUER FRASE:**\n` +
    `> 1. Esta frase usa as palavras exatas do avatar (mapa de linguagem ou arquivo de voz)?\n` +
    `> 2. Toca no desejo REAL (não superficial)?\n` +
    `> 3. Endereça ou dissolve a objeção principal?\n` +
    `> 4. Apela para a identidade que ele quer TER, não para quem ele é agora?\n` +
    `> Se não: reescreva antes de entregar.`
  );
  parts.push(`\n---\n`);

  return parts.join("\n");
}
