// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/nexos-redesign/Atual.tsx": () => import("../components/mockups/nexos-redesign/Atual.tsx"),
  "./components/mockups/nexos-redesign/Novo.tsx": () => import("../components/mockups/nexos-redesign/Novo.tsx"),
  "./components/mockups/degraded-cpl-badge/DegradedCPLBadge.tsx": () => import("../components/mockups/degraded-cpl-badge/DegradedCPLBadge.tsx"),
  "./components/mockups/nexos-ui-directions/ConversationalOps.tsx": () => import("../components/mockups/nexos-ui-directions/ConversationalOps.tsx"),
  "./components/mockups/nexos-ui-directions/CurrentBaseline.tsx": () => import("../components/mockups/nexos-ui-directions/CurrentBaseline.tsx"),
  "./components/mockups/nexos-ui-directions/ExecutiveCockpit.tsx": () => import("../components/mockups/nexos-ui-directions/ExecutiveCockpit.tsx"),
  "./components/mockups/nexos-ui-directions/GuidedJourney.tsx": () => import("../components/mockups/nexos-ui-directions/GuidedJourney.tsx")
};
