// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/degraded-cpl-badge/DegradedCPLBadge.tsx": () => import("../components/mockups/degraded-cpl-badge/DegradedCPLBadge.tsx"),
  "./components/mockups/nexos-redesign/Atual.tsx": () => import("../components/mockups/nexos-redesign/Atual.tsx"),
  "./components/mockups/nexos-redesign/Novo.tsx": () => import("../components/mockups/nexos-redesign/Novo.tsx")
};
