services:
  web:
    networks: [default, ingress]
  api:
    secrets: [database_ca]
  db-tools:
    secrets: [database_ca]
networks:
  ingress: {}
  default: { internal: true }
  database:
    external: true
secrets:
  database_ca:
    file: ${DEPLOYMENT_TEST_DIR:?Owned test directory required}/ca.pem
