bind 0.0.0.0
protected-mode yes
port 6379
dir /data
appendonly yes
appendfsync everysec
aof-use-rdb-preamble yes
save 900 1
save 300 10
save 60 10000
stop-writes-on-bgsave-error yes
maxmemory 512mb
maxmemory-policy noeviction
timeout 0
tcp-keepalive 60
loglevel notice
