import {
  pgTable,
  text,
  uuid,
  timestamp,
  integer,
  pgEnum,
  jsonb,
} from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod/v4";
import { campaignsTable } from "./campaigns";

export const agentTypeEnum = pgEnum("agent_type", [
  "command",
  "strategy",
  "offer",
  "copywriter",
  "creative_director",
  "video",
  "video_strategy",
  "media_buyer",
  "targeting",
  "landing_page",
  "analytics",
  "optimization",
  "creator_growth",
  "product_builder",
  "compliance",
  "affiliate_campaign",
  "launch_manager",
  "perpetual_launch_manager",
  "ad_copy",
  "social_media",
  "stories_sequence",
  "media_brief",
  "vsl_script",
  "cpl_script",
  "webinar_script",
  "live_script",
  "financial_projector",
  "launch_sequence_builder",
  "continuous_sales_manager",
  "whatsapp_response",
  "execution_governor",
  "buyer_onboarding",
  "semente_launch",
  "product_validator",
  "sales_warmer",
  "sales_desire",
  "sales_closer",
  "sales_objection",
  "sales_consultant",
  "scene_director",
  "business_intelligence",
  "market_intel",
  "email_architect",
  "pricing_psychologist",
  "organic_traffic",
  "ab_test_designer",
  "hook_factory",
  "content_calendar",
  "domino",
  "upsell_architect",
  "scarcity_engineer",
  "objection_killer",
  "reengagement",
  "crisis_response",
  "testimonial_curator",
  "video_hook",
  "campaign_emotional_arc",
  "launch_debriefing",
  "memory_compression",
  "context_refinement",
  "output_judge",
  "identity_architect",
  "mental_frequency_coach",
  "obstinacy_trainer",
  "ethics_autocorrect",
  "emotional_coherence_checker",
  "strategic_core",
  "strategic_doctrine",
  "ad_critic",
  "dynamic_avatar_state",
  "geographic_targeting",
  "ux_simplification",
  "campaign_memory",
  "item_copy_generator",
  "presence_planner",
  "bio_optimizer",
  "market_validator",
  "offer_price_validator",
  "brand_validator",
  // Agentes com role próprio (corrigido de roles emprestados em #70-B)
  "profile_builder",
  "traffic_intelligence",
  "creative_concept",
  "prelaunch_warming",
]);

export const agentStatusEnum = pgEnum("agent_status", [
  "pending",
  "running",
  "waiting_approval",
  "approved",
  "rejected",
  "completed",
  "failed",
  "skipped",
]);

export const campaignAgentsTable = pgTable("campaign_agents", {
  id: uuid("id").primaryKey().defaultRandom(),
  campaignId: uuid("campaign_id")
    .notNull()
    .references(() => campaignsTable.id, { onDelete: "cascade" }),
  agentType: agentTypeEnum("agent_type").notNull(),
  status: agentStatusEnum("status").notNull().default("pending"),
  input: jsonb("input").notNull().default({}),
  output: jsonb("output").notNull().default({}),
  thoughts: text("thoughts"),
  aiProvider: text("ai_provider"),
  model: text("model"),
  tokensUsed: integer("tokens_used"),
  creditsUsed: integer("credits_used").notNull().default(0),
  errorMessage: text("error_message"),
  retryCount: integer("retry_count").notNull().default(0),
  startedAt: timestamp("started_at", { withTimezone: true }),
  completedAt: timestamp("completed_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
});

export const insertCampaignAgentSchema = createInsertSchema(
  campaignAgentsTable,
).omit({ id: true, createdAt: true });

export type InsertCampaignAgent = z.infer<typeof insertCampaignAgentSchema>;
export type CampaignAgent = typeof campaignAgentsTable.$inferSelect;
