import { boolean, check, index, jsonb, pgEnum, pgTable, text, timestamp, uuid, uniqueIndex, foreignKey } from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";
import { workspacesTable } from "./workspaces";
import { campaignsTable } from "./campaigns";
import { usersTable } from "./users";
import { masterplanVersionsTable } from "./masterplan-versions";
import { realizationContractsTable } from "./realization";

export const councilCycleStatus = pgEnum("council_cycle_status", ["open", "closed"]);
export const councilDecisionStatus = pgEnum("council_decision_status", ["proposed", "superseded"]);
export const councilOutcomeStatus = pgEnum("council_outcome_status", ["verified", "inconclusive", "unsupported", "exception"]);
export const councilActionFamily = pgEnum("council_action_family", ["paid_media_pause", "paid_media_launch", "unsupported"]);

export const councilCyclesTable = pgTable("council_cycles", {
  id: uuid("id").primaryKey().defaultRandom(), workspaceId: uuid("workspace_id").notNull().references(() => workspacesTable.id), campaignId: uuid("campaign_id").notNull().references(() => campaignsTable.id),
  masterplanVersionId: uuid("masterplan_version_id").notNull().references(() => masterplanVersionsTable.id), contextFingerprint: text("context_fingerprint").notNull(), snapshotHash: text("snapshot_hash").notNull(),
  ownerUserId: uuid("owner_user_id").notNull().references(() => usersTable.id), status: councilCycleStatus("status").notNull().default("open"), idempotencyKey: text("idempotency_key").notNull(), createdAt: timestamp("created_at",{withTimezone:true}).notNull().defaultNow(),
}, t => [uniqueIndex("council_cycles_scope_idempotency_uidx").on(t.workspaceId,t.campaignId,t.idempotencyKey), uniqueIndex("council_cycles_scope_uidx").on(t.workspaceId,t.id), foreignKey({columns:[t.workspaceId,t.campaignId,t.masterplanVersionId],foreignColumns:[masterplanVersionsTable.workspaceId,masterplanVersionsTable.campaignId,masterplanVersionsTable.id],name:"council_cycle_plan_scope_fk"}), index("council_cycles_campaign_idx").on(t.workspaceId,t.campaignId,t.createdAt)]);

export const councilMinutesTable = pgTable("council_minutes", {
  id: uuid("id").primaryKey().defaultRandom(), workspaceId: uuid("workspace_id").notNull().references(() => workspacesTable.id), cycleId: uuid("cycle_id").notNull().references(() => councilCyclesTable.id), authorUserId: uuid("author_user_id").notNull().references(() => usersTable.id), summary: text("summary").notNull(), evidenceRefs: jsonb("evidence_refs").notNull().default([]), createdAt: timestamp("created_at",{withTimezone:true}).notNull().defaultNow(),
}, t => [index("council_minutes_cycle_idx").on(t.workspaceId,t.cycleId,t.createdAt), foreignKey({columns:[t.workspaceId,t.cycleId],foreignColumns:[councilCyclesTable.workspaceId,councilCyclesTable.id],name:"council_minutes_cycle_scope_fk"})]);
export const councilDecisionsTable = pgTable("council_decisions", {
  id: uuid("id").primaryKey().defaultRandom(), workspaceId: uuid("workspace_id").notNull().references(() => workspacesTable.id), cycleId: uuid("cycle_id").notNull().references(() => councilCyclesTable.id), ownerUserId: uuid("owner_user_id").notNull().references(() => usersTable.id), rationaleSummary: text("rationale_summary").notNull(), evidenceRefs: jsonb("evidence_refs").notNull().default([]), target: jsonb("target").notNull(), baseline: jsonb("baseline").notNull(), threshold: jsonb("threshold").notNull(), window: jsonb("window").notNull(), dueAt: timestamp("due_at",{withTimezone:true}), actionRequired: boolean("action_required").notNull().default(false), status: councilDecisionStatus("status").notNull().default("proposed"), supersedesId: uuid("supersedes_id"), createdAt: timestamp("created_at",{withTimezone:true}).notNull().defaultNow(),
}, t => [uniqueIndex("council_decisions_scope_uidx").on(t.workspaceId,t.id), index("council_decisions_cycle_idx").on(t.workspaceId,t.cycleId,t.createdAt), foreignKey({columns:[t.workspaceId,t.cycleId],foreignColumns:[councilCyclesTable.workspaceId,councilCyclesTable.id],name:"council_decisions_cycle_scope_fk"})]);
export const councilActionsTable = pgTable("council_actions", {
  id: uuid("id").primaryKey().defaultRandom(), workspaceId: uuid("workspace_id").notNull().references(() => workspacesTable.id), decisionId: uuid("decision_id").notNull().references(() => councilDecisionsTable.id), family: councilActionFamily("family").notNull(), realizationContractId: uuid("realization_contract_id").references(() => realizationContractsTable.id), idempotencyKey: text("idempotency_key").notNull(), createdAt: timestamp("created_at",{withTimezone:true}).notNull().defaultNow(),
}, t => [uniqueIndex("council_actions_scope_idempotency_uidx").on(t.workspaceId,t.idempotencyKey), uniqueIndex("council_actions_scope_uidx").on(t.workspaceId,t.id), index("council_actions_decision_idx").on(t.workspaceId,t.decisionId), foreignKey({columns:[t.workspaceId,t.decisionId],foreignColumns:[councilDecisionsTable.workspaceId,councilDecisionsTable.id],name:"council_actions_decision_scope_fk"}), check("council_actions_supported_family_check", sql`${t.family} <> 'unsupported'`)]);
export const councilOutcomesTable = pgTable("council_outcomes", {
  id: uuid("id").primaryKey().defaultRandom(), workspaceId: uuid("workspace_id").notNull().references(() => workspacesTable.id), decisionId: uuid("decision_id").notNull().references(() => councilDecisionsTable.id), actionId: uuid("action_id").references(() => councilActionsTable.id), nextCycleId: uuid("next_cycle_id"), status: councilOutcomeStatus("status").notNull(), verificationFingerprint: text("verification_fingerprint").notNull(), verification: jsonb("verification").notNull(), createdAt: timestamp("created_at",{withTimezone:true}).notNull().defaultNow(),
}, t => [uniqueIndex("council_outcomes_action_evidence_uidx").on(t.workspaceId,t.actionId,t.nextCycleId,t.verificationFingerprint), check("council_outcomes_next_cycle_required", sql`${t.nextCycleId} IS NOT NULL`), index("council_outcomes_decision_idx").on(t.workspaceId,t.decisionId,t.createdAt), foreignKey({columns:[t.workspaceId,t.decisionId],foreignColumns:[councilDecisionsTable.workspaceId,councilDecisionsTable.id],name:"council_outcomes_decision_scope_fk"}), foreignKey({columns:[t.workspaceId,t.actionId],foreignColumns:[councilActionsTable.workspaceId,councilActionsTable.id],name:"council_outcomes_action_scope_fk"}), foreignKey({columns:[t.workspaceId,t.nextCycleId],foreignColumns:[councilCyclesTable.workspaceId,councilCyclesTable.id],name:"council_outcomes_next_cycle_scope_fk"})]);