export interface BibliographyEntry {
  id: string;
  title: string;
  author: string;
  year: number;
  publisher: string;
  language: "pt" | "en" | "both";
  difficulty: 1 | 2 | 3;
  why: string;
  topics: string[];
  amazonBr?: string;
}

export const BIBLIOGRAPHY: BibliographyEntry[] = [
  {
    id: "launch-walker",
    title: "Launch: O Método Definitivo para Criar, Explodir e Vender Online",
    author: "Jeff Walker",
    year: 2014,
    publisher: "Portfolio / Alta Books (PT-BR)",
    language: "both",
    difficulty: 1,
    why: "O livro que criou a PLF — Product Launch Formula. Walker documenta o método que gerou mais de US$1 bilhão em vendas para seus alunos. Leitura obrigatória para entender a estrutura de lançamento do zero.",
    topics: ["plf-1", "plf-2", "semente", "interno-externo", "perpetuo"],
  },
  {
    id: "influence-cialdini",
    title: "As Armas da Persuasão",
    author: "Robert B. Cialdini",
    year: 1984,
    publisher: "Sextante (PT-BR)",
    language: "both",
    difficulty: 1,
    why: "O livro mais citado em marketing de todos os tempos. Os 7 princípios de influência de Cialdini são a base de todo gatilho mental bem aplicado. Leitura fundamental antes de qualquer campanha.",
    topics: ["triggers-1", "triggers-2", "triggers-3", "triggers-4", "copy-1"],
  },
  {
    id: "presuasion-cialdini",
    title: "Pré-Suasão: Como Influenciar Antes Mesmo de Começar",
    author: "Robert B. Cialdini",
    year: 2016,
    publisher: "Sextante (PT-BR)",
    language: "both",
    difficulty: 2,
    why: "A sequela de As Armas da Persuasão. Cialdini revela que o que acontece ANTES da mensagem persuasiva é tão importante quanto a mensagem em si — conceito que muda completamente a arquitetura do pré-lançamento.",
    topics: ["plf-1", "triggers-1", "triggers-2"],
  },
  {
    id: "thinking-kahneman",
    title: "Rápido e Devagar: Duas Formas de Pensar",
    author: "Daniel Kahneman",
    year: 2011,
    publisher: "Objetiva (PT-BR)",
    language: "both",
    difficulty: 3,
    why: "O livro fundamental sobre como o cérebro toma decisões. Kahneman (Nobel de Economia 2002) prova que compramos com o Sistema 1 (emocional, rápido) e justificamos com o Sistema 2 (racional, lento). Muda completamente a forma de estruturar argumentos de venda.",
    topics: ["psi-kahneman-1", "triggers-1", "copy-1"],
  },
  {
    id: "irrational-ariely",
    title: "Previsivelmente Irracional",
    author: "Dan Ariely",
    year: 2008,
    publisher: "Elsevier / Campus (PT-BR)",
    language: "both",
    difficulty: 2,
    why: "Ariely desmonta com experimentos reais o mito do consumidor racional. Âncoragem de preço, efeito do gratuito, decoy — são todos explicados com dados, não teoria. Essencial para precificação e engenharia de oferta.",
    topics: ["psi-kahneman-1", "escada-1", "upsell-downsell", "monetizacao-quiz"],
  },
  {
    id: "breakthrough-schwartz",
    title: "Breakthrough Advertising",
    author: "Eugene M. Schwartz",
    year: 1966,
    publisher: "Bottom Line Books",
    language: "en",
    difficulty: 3,
    why: "O livro de copy mais estudado pelos maiores copywriters do mundo. Schwartz introduz os 5 níveis de sofisticação do mercado — conceito que determina qual promessa e headline usar em cada nicho. Raro e valioso. Exemplares usados chegam a custar US$500.",
    topics: ["copy-1", "copy-2", "casos-ogilvy-halbert"],
  },
  {
    id: "ogilvy-advertising",
    title: "Ogilvy on Advertising",
    author: "David Ogilvy",
    year: 1983,
    publisher: "Vintage Books",
    language: "en",
    difficulty: 1,
    why: "O manifesto de Ogilvy sobre o que funciona em propaganda — escrito depois de décadas medindo resultados reais. Não é teórico. É um manual prático do homem que criou as campanhas mais eficazes do século XX.",
    topics: ["copy-1", "copy-2", "casos-ogilvy-halbert"],
  },
  {
    id: "confessions-ogilvy",
    title: "Confissões de um Publicitário",
    author: "David Ogilvy",
    year: 1963,
    publisher: "Bertrand Brasil (PT-BR)",
    language: "both",
    difficulty: 1,
    why: "A autobiografia de Ogilvy e sua filosofia de negócios. Revela como ele construiu a maior agência de publicidade do mundo tendo começado como cozinheiro e vendedor porta-a-porta. Inspiração e método em partes iguais.",
    topics: ["copy-1", "casos-ogilvy-halbert"],
  },
  {
    id: "boron-letters-halbert",
    title: "The Boron Letters",
    author: "Gary Halbert",
    year: 1984,
    publisher: "Self-published",
    language: "en",
    difficulty: 2,
    why: "Cartas escritas por Gary Halbert para o filho enquanto estava preso. São o curso de copywriting mais honesto e direto já escrito. Halbert revela padrões que ainda hoje nenhum curso digital ensina. Disponível gratuitamente online.",
    topics: ["copy-2", "casos-ogilvy-halbert", "copy-email-whatsapp"],
  },
  {
    id: "ultimate-letter-kennedy",
    title: "The Ultimate Sales Letter",
    author: "Dan Kennedy",
    year: 1990,
    publisher: "Adams Media",
    language: "en",
    difficulty: 2,
    why: "O método de Kennedy para escrever cartas de vendas que convertem. Mesmo escrito na era do correio físico, os princípios são mais relevantes do que nunca para emails, landing pages e VSLs. Kennedy foi o professor de copy de uma geração inteira de empreendedores americanos.",
    topics: ["copy-2", "copy-landing-page", "casos-ogilvy-halbert"],
  },
  {
    id: "scientific-hopkins",
    title: "A Publicidade Científica",
    author: "Claude C. Hopkins",
    year: 1923,
    publisher: "Madras (PT-BR)",
    language: "both",
    difficulty: 2,
    why: "O avô do marketing de performance escreveu este livro em 1923 — e ainda é obrigatório. Hopkins foi o primeiro a medir resultados de campanhas e basear decisões em dados. David Ogilvy disse que qualquer pessoa que trabalhe com publicidade deve ler este livro 7 vezes.",
    topics: ["copy-1", "meta-otimizacao", "casos-ogilvy-halbert"],
  },
  {
    id: "way-up-abraham",
    title: "Getting Everything You Can Out of All You've Got",
    author: "Jay Abraham",
    year: 2000,
    publisher: "St. Martin's Press",
    language: "en",
    difficulty: 2,
    why: "Jay Abraham revela os 3 únicos jeitos de crescer um negócio: mais clientes, maior ticket médio, mais compras por cliente. A Strategy of Preeminence — posicionar-se como o único conselheiro confiável, não como vendedor — é um dos conceitos mais transformadores do marketing moderno.",
    topics: ["escada-1", "upsell-downsell", "recorrencia", "afiliado"],
  },
  {
    id: "dotcom-brunson",
    title: "Dotcom Secrets",
    author: "Russell Brunson",
    year: 2015,
    publisher: "Morgan James Publishing",
    language: "en",
    difficulty: 1,
    why: "Brunson descreve os funis de marketing que construíram a ClickFunnels. A Value Ladder (Escada de Valor) apresentada neste livro é o modelo que a NexOS usa como arquitetura de monetização. Prático e direto.",
    topics: ["escada-1", "upsell-downsell", "perpetuo", "monetizacao-quiz"],
  },
  {
    id: "expert-secrets-brunson",
    title: "Expert Secrets",
    author: "Russell Brunson",
    year: 2017,
    publisher: "Morgan James Publishing",
    language: "en",
    difficulty: 1,
    why: "Como transformar conhecimento em movimento. Brunson ensina a estrutura do webinar perfeito, a criação de crença (Epiphany Bridge), e como posicionar qualquer produto como solução única para uma audiência específica.",
    topics: ["perpetuo", "plf-2", "copy-1"],
  },
  {
    id: "positioning-ries",
    title: "Posicionamento: A Batalha por Sua Mente",
    author: "Al Ries & Jack Trout",
    year: 1981,
    publisher: "M. Books (PT-BR)",
    language: "both",
    difficulty: 2,
    why: "O livro que definiu 'posicionamento' como conceito de marketing. Ries e Trout argumentam que o marketing não é uma batalha de produtos, mas uma batalha de percepções. Essencial para entender por que o mecanismo único de uma oferta importa mais do que suas features.",
    topics: ["copy-1", "comparativo-modelos", "casos-ogilvy-halbert"],
  },
  {
    id: "story-brand-miller",
    title: "Marketing: A História que Vende",
    author: "Donald Miller",
    year: 2017,
    publisher: "Thomas Nelson / Gente (PT-BR)",
    language: "both",
    difficulty: 1,
    why: "Miller aplica a estrutura do monomito (herói) ao marketing. O cliente é o herói — não o produto. O produto é o guia (Gandalf, não Frodo). Essa inversão de perspectiva transforma completamente como se escreve landing page e VSL.",
    topics: ["copy-landing-page", "copy-1", "plf-1"],
  },
  {
    id: "made-stick-heath",
    title: "Feitas Para Durar — Por Que Algumas Ideias Sobrevivem e Outras Morrem",
    author: "Chip Heath & Dan Heath",
    year: 2007,
    publisher: "Alta Books (PT-BR)",
    language: "both",
    difficulty: 1,
    why: "Os irmãos Heath identificam 6 características de ideias que grudam na memória: Simple, Unexpected, Concrete, Credible, Emotional, Stories (SUCCES). Diretamente aplicável à construção de hooks, headlines e mensagens de lançamento memoráveis.",
    topics: ["copy-anuncio-avancado", "triggers-1", "copy-redes-sociais"],
  },
  {
    id: "contagious-berger",
    title: "Contágio: Por Que as Coisas Pegam",
    author: "Jonah Berger",
    year: 2013,
    publisher: "LeYa (PT-BR)",
    language: "both",
    difficulty: 1,
    why: "Berger pesquisou o que faz conteúdo e ideias se espalharem viralmente. Os 6 princípios STEPPS (Social Currency, Triggers, Emotion, Public, Practical Value, Stories) explicam por que alguns posts explodem e outros morrem com 12 curtidas.",
    topics: ["organico-1", "copy-redes-sociais", "triggers-1"],
  },
  {
    id: "hooked-eyal",
    title: "Hooked: Como Construir Produtos e Serviços Que Criam Hábitos",
    author: "Nir Eyal",
    year: 2014,
    publisher: "Alta Books (PT-BR)",
    language: "both",
    difficulty: 2,
    why: "O modelo Hook (Trigger → Action → Variable Reward → Investment) explica como as grandes plataformas criam hábito. Para lançamentos, o conceito é diretamente aplicável ao design de sequências de conteúdo que fazem a audiência voltar.",
    topics: ["triggers-1", "plf-1", "onboarding"],
  },
  {
    id: "innovators-dilemma",
    title: "O Dilema da Inovação",
    author: "Clayton M. Christensen",
    year: 1997,
    publisher: "M. Books (PT-BR)",
    language: "both",
    difficulty: 3,
    why: "Christensen criou o conceito de Jobs to Be Done — as pessoas não compram produtos, contratam soluções para um trabalho. Essa perspectiva muda radicalmente como se pesquisa a dor do avatar e como se posiciona qualquer produto digital.",
    topics: ["escada-1", "monetizacao-quiz", "copy-1"],
  },
  {
    id: "war-of-art-pressfield",
    title: "A Guerra da Arte",
    author: "Steven Pressfield",
    year: 2002,
    publisher: "Campus/Elsevier (PT-BR)",
    language: "both",
    difficulty: 1,
    why: "O livro mais honesto sobre o que impede empreendedores de executar: a Resistência. Pressfield nomeia o inimigo interno que sabota lançamentos não por falta de técnica, mas por medo de visibilidade, julgamento e fracasso.",
    topics: ["semente", "plf-1"],
  },
  {
    id: "blue-ocean-kim",
    title: "A Estratégia do Oceano Azul",
    author: "W. Chan Kim & Renée Mauborgne",
    year: 2005,
    publisher: "Campus/Elsevier (PT-BR)",
    language: "both",
    difficulty: 2,
    why: "Como criar novos mercados em vez de competir em mercados saturados. O conceito de Oceano Azul é o antídoto para commoditização — diretamente relevante para produtores digitais que querem sair da guerra de preço.",
    topics: ["comparativo-modelos", "copy-1", "casos-ogilvy-halbert"],
  },
  {
    id: "influence-new-cialdini",
    title: "Influence, New and Expanded",
    author: "Robert B. Cialdini",
    year: 2021,
    publisher: "Harper Business",
    language: "en",
    difficulty: 2,
    why: "Edição expandida dos 7 princípios com um sétimo princípio adicionado: Unidade (Unity) — a identidade compartilhada. Cialdini atualiza os exemplos para o mundo digital e detalha como cada princípio funciona em redes sociais e email.",
    topics: ["triggers-3", "triggers-4", "copy-email-whatsapp"],
  },
];

export function getBibliographyForLesson(lessonId: string): BibliographyEntry[] {
  return BIBLIOGRAPHY.filter(b => b.topics.includes(lessonId));
}

export const DIFFICULTY_LABEL: Record<number, string> = {
  1: "Leitura Acessível",
  2: "Intermediário",
  3: "Denso / Técnico",
};

export const DIFFICULTY_COLOR: Record<number, string> = {
  1: "hsl(168 100% 42%)",
  2: "hsl(45 100% 55%)",
  3: "hsl(10 100% 60%)",
};
