export interface GlossaryTerm {
  id: string;
  term: string;
  category: string;
  definition: string;
  example?: string;
  related?: string[];
  lessonIds?: string[];
}

export const GLOSSARY_CATEGORIES = [
  "Lançamentos",
  "Meta Ads & Tráfego Pago",
  "Algoritmos & Plataformas",
  "Copywriting & Persuasão",
  "Email & WhatsApp Marketing",
  "Analytics & Métricas",
  "Monetização & Funis",
  "Automação & Ferramentas",
  "Negócio & Estratégia",
  "SEO & Busca Orgânica",
];

export const GLOSSARY: GlossaryTerm[] = [
  // ─── LANÇAMENTOS ───────────────────────────────────────────────
  {
    id: "lancamento-semente",
    term: "Lançamento Semente",
    category: "Lançamentos",
    definition: "Modelo de lançamento onde o produto é vendido antes de ser criado. O produtor apresenta a ideia para uma audiência pequena e oferece acesso a um preço de fundador reduzido. A receita da venda financia a produção e os primeiros compradores se tornam co-criadores com influência sobre o conteúdo final. Elimina o risco de criar um produto sem demanda validada.",
    example: "Você tem a ideia de um curso de copywriting. Antes de gravar uma aula sequer, abre uma lista de espera e oferece acesso por R$297 (preço de fundador) para as primeiras 30 pessoas. Com 18 compradores, você valida a demanda e tem R$5.346 para produzir com qualidade.",
    related: ["Preço de Fundador", "Validação de Mercado", "Co-criação"],
  },
  {
    id: "lancamento-perpetuo",
    term: "Lançamento Perpétuo (Evergreen)",
    category: "Lançamentos",
    definition: "Sistema de vendas automatizado que roda continuamente, sem janelas de abertura e fechamento de carrinho. O visitante entra no funil, passa por uma sequência de emails e webinar, e recebe uma oferta com deadline individual (geralmente 48-72h após o primeiro contato). Gera receita previsível e crescente sem depender de lançamentos pontuais.",
    example: "Um funil perpétuo com anúncios de R$200/dia gerando 50 leads/dia, com taxa de conversão de 3%, produz 1,5 vendas por dia. Com ticket de R$997, isso representa R$1.495/dia ou R$44.850/mês em receita previsível.",
    related: ["Webinar Evergreen", "Deadline Funnel", "Funil de Vendas", "Sequência de Email"],
  },
  {
    id: "lancamento-plf",
    term: "PLF (Product Launch Formula)",
    category: "Lançamentos",
    definition: "Metodologia de lançamento criada por Jeff Walker em 2005. Estruturada em torno de uma sequência de 3-4 'Vídeos de Pré-Lançamento' (VPLs) entregues gratuitamente nos dias anteriores à abertura do carrinho, cada um construindo um elemento da venda: oportunidade, transformação, prova social e oferta. É o framework base da maioria dos grandes lançamentos digitais do Brasil.",
    example: "VPL1: 'A Grande Oportunidade' (mostra o problema e a possibilidade). VPL2: 'A Transformação' (ensina mecanismo central e apresenta casos de sucesso). VPL3: 'A Oferta' (apresenta o produto, bônus, garantia e preço). Carrinho abre 24h depois.",
    related: ["VSL", "Sequência de Pré-Lançamento", "Lista de Espera", "Jeff Walker"],
  },
  {
    id: "lancamento-interno",
    term: "Lançamento Interno",
    category: "Lançamentos",
    definition: "Lançamento realizado exclusivamente para a própria audiência do produtor — lista de email, seguidores nas redes sociais, grupo de WhatsApp. O produtor controla totalmente o timing, a mensagem e a frequência. Sem comissões para parceiros. O teto de receita é limitado pelo tamanho da audiência própria.",
    related: ["Lista de Email", "Lançamento Externo", "Joint Venture"],
  },
  {
    id: "lancamento-externo",
    term: "Lançamento Externo",
    category: "Lançamentos",
    definition: "Lançamento onde o produto é apresentado para a audiência de um ou mais parceiros (JVs — Joint Ventures). O parceiro promove o produto para sua lista em troca de comissão sobre as vendas (geralmente 30-50%). Permite alcançar audiências novas sem construí-las do zero. Exige produto validado, material de divulgação pronto e acordo claro sobre tracking de vendas.",
    related: ["Joint Venture", "Afiliado", "Comissão", "Lançamento Interno"],
  },
  {
    id: "lancamento-afiliado",
    term: "Lançamento de Afiliado",
    category: "Lançamentos",
    definition: "Modelo onde o afiliado promove o produto de outro produtor para sua audiência em troca de comissão, sem criar produto próprio. Ideal para quem está começando — gera receita enquanto aprende o mercado. A estratégia mais avançada inclui criação de bônus exclusivos para diferenciar o link do afiliado.",
    example: "Um influenciador de finanças pessoais com 10.000 seguidores promove um curso de investimentos de R$1.497 com 40% de comissão. Cada venda gera R$598,80 para o afiliado. Com 30 vendas no lançamento, receita de R$17.964.",
    related: ["Hotmart", "Kiwify", "Eduzz", "Comissão", "Bônus de Afiliado"],
  },
  {
    id: "lancamento-co-criacao",
    term: "Lançamento de Co-criação",
    category: "Lançamentos",
    definition: "Modelo híbrido onde dois produtores com especialidades complementares criam um produto juntos, unindo suas audiências e dividindo a receita. Cada parceiro contribui com conhecimento específico e acessa a audiência do outro. A divisão de receita mais comum é 50/50, mas pode variar conforme a contribuição de cada parte.",
    example: "Nutricionista + personal trainer criam o 'Programa Transformação Total 90 dias'. A nutricionista cuida do módulo de alimentação e promove para sua lista. O personal cria o módulo de treino e promove para a sua. A receita é dividida igualmente.",
    related: ["Joint Venture", "Parceria", "Lançamento Externo"],
  },
  {
    id: "preco-fundador",
    term: "Preço de Fundador",
    category: "Lançamentos",
    definition: "Preço especial e reduzido oferecido aos primeiros compradores de um produto, geralmente durante um lançamento semente. Normalmente 30-60% abaixo do preço definitivo. Em troca, o comprador aceita adquirir algo em desenvolvimento e tem a oportunidade de influenciar o produto final com feedback.",
    related: ["Lançamento Semente", "Early Adopter"],
  },
  {
    id: "lista-de-espera",
    term: "Lista de Espera (Waitlist)",
    category: "Lançamentos",
    definition: "Lista de pessoas que se cadastraram para receber notificação de abertura de um produto antes do lançamento público. Serve como pré-aquecimento de audiência, validação de demanda e canal de comunicação prioritário. Membros da waitlist recebem frequentemente preço especial, bônus exclusivos ou acesso antecipado.",
    related: ["Pré-lançamento", "Lead Magnet", "Funil de Lançamento"],
  },
  {
    id: "carrinho-aberto",
    term: "Carrinho Aberto",
    category: "Lançamentos",
    definition: "Período durante o qual o produto está disponível para compra. Em lançamentos pontuais, esse período é limitado (tipicamente 5-7 dias) para criar escassez e urgência. A distribuição histórica de vendas: ~30% no dia 1 (abertura), ~20% nos dias intermediários, ~45% nas últimas 24h (fechamento).",
    related: ["Fechamento de Carrinho", "Escassez", "Urgência", "Scarcity"],
  },
  {
    id: "pré-lançamento",
    term: "Pré-Lançamento",
    category: "Lançamentos",
    definition: "Fase anterior à abertura do carrinho, geralmente 7-21 dias. Objetivo: aquecer a audiência com conteúdo de valor gratuito, construir relacionamento e criar antecipação. Inclui VPLs (vídeos de pré-lançamento), emails de preparação, posts de conteúdo, capturas de lead para a lista de espera.",
    related: ["VPL", "Aquecimento de Audiência", "PLF", "Lista de Espera"],
  },
  {
    id: "sequência-de-fechamento",
    term: "Sequência de Fechamento",
    category: "Lançamentos",
    definition: "Série de emails e mensagens enviadas nas últimas 24-48h antes do fechamento do carrinho. Cada mensagem usa um ângulo diferente para motivar a decisão: urgência de prazo, medo de perder, prova social recente, destruição de objeção. A regra de ouro é nunca repetir o mesmo copy nas mensagens de fechamento.",
    example: "H-48: 'Amanhã é o último dia'. H-24: 'Hoje fecha'. H-12: 'Últimas 12h — [depoimento de aluno]'. H-6: 'Últimas 6h'. H-3: '3h — destruindo a principal objeção'. H-1: 'Última chance'. H-0: 'Carrinho fechado'.",
    related: ["Urgência", "Escassez", "Copywriting de Fechamento"],
  },
  {
    id: "vsl",
    term: "VSL (Video Sales Letter)",
    category: "Lançamentos",
    definition: "Vídeo de vendas longo (geralmente 20-60 min) que substitui a tradicional carta de vendas em texto. Segue uma estrutura narrativa específica: gancho → história → problema → solução → mecanismo único → prova social → oferta → bônus → garantia → CTA. É o principal ativo de conversão de um lançamento digital.",
    related: ["Copywriting", "Script de VSL", "Carta de Vendas", "Mecanismo Único"],
  },
  {
    id: "vpl",
    term: "VPL (Vídeo de Pré-Lançamento)",
    category: "Lançamentos",
    definition: "Vídeos gratuitos de conteúdo entregues na fase de pré-lançamento da PLF. Geralmente são 3-4 vídeos, cada um com um papel específico na jornada de compra: VPL1 (oportunidade), VPL2 (transformação e mecanismo), VPL3 (prova social e cases), VPL4 (oferta). Substituem a necessidade de webinar ao vivo em muitos lançamentos.",
    related: ["PLF", "Pré-lançamento", "VSL"],
  },

  // ─── META ADS & TRÁFEGO PAGO ───────────────────────────────────
  {
    id: "roas",
    term: "ROAS (Return on Ad Spend)",
    category: "Meta Ads & Tráfego Pago",
    definition: "Métrica que mede o retorno sobre o investimento em publicidade. Calculado como: Receita gerada pelos anúncios ÷ Gasto total em anúncios. ROAS de 3x significa que cada R$1 investido gerou R$3 em receita. O ponto de equilíbrio varia conforme a margem do produto — para um produto digital com margem de 80%, ROAS de 1,25x já é lucrativo.",
    example: "R$10.000 gastos em anúncios gerou R$35.000 em receita. ROAS = 35.000 ÷ 10.000 = 3,5x.",
    related: ["CPL", "CPA", "CAC", "Margem de Lucro"],
  },
  {
    id: "cpm",
    term: "CPM (Custo por Mil Impressões)",
    category: "Meta Ads & Tráfego Pago",
    definition: "Quanto você paga para que seu anúncio seja exibido 1.000 vezes. Reflete a competitividade do leilão de anúncios para aquela audiência e período. CPM alto não é necessariamente ruim se a conversão compensar. Médias PT-BR por nicho: educação R$15-R$35, finanças R$40-R$80, saúde/fitness R$12-R$25.",
    related: ["CPC", "CTR", "Leilão de Anúncios", "Frequência"],
  },
  {
    id: "cpc",
    term: "CPC (Custo por Clique)",
    category: "Meta Ads & Tráfego Pago",
    definition: "Valor médio pago por cada clique no anúncio. Calculado como CPM ÷ (CTR × 10). Um CPC alto com alta taxa de conversão na landing page pode ser mais lucrativo que um CPC baixo com baixa conversão. Deve sempre ser analisado em conjunto com o CPL e o ROAS, nunca isoladamente.",
    related: ["CPM", "CTR", "CPL", "Landing Page"],
  },
  {
    id: "ctr",
    term: "CTR (Click-Through Rate)",
    category: "Meta Ads & Tráfego Pago",
    definition: "Porcentagem de pessoas que viram o anúncio e clicaram nele. Calculado como: Cliques ÷ Impressões × 100. Benchmarks para Meta Ads: CTR no link acima de 1% é bom, acima de 2% é excelente. CTR baixo (abaixo de 0,5%) indica problema no criativo ou no público.",
    related: ["CPM", "CPC", "Criativo", "Hook Rate"],
  },
  {
    id: "cpl",
    term: "CPL (Custo por Lead)",
    category: "Meta Ads & Tráfego Pago",
    definition: "Custo médio para adquirir um lead (contato de potencial comprador). Calculado como: Gasto em anúncios ÷ Número de leads gerados. Um CPL saudável deve ser inferior a 10-15% do ticket do produto. Para produto de R$1.000, CPL máximo aceitável é R$100-R$150.",
    related: ["Lead", "CPM", "ROAS", "CAC"],
  },
  {
    id: "cpa",
    term: "CPA (Custo por Aquisição)",
    category: "Meta Ads & Tráfego Pago",
    definition: "Custo médio para gerar uma venda ou conversão. Diferente do CPL (que mede custo por lead), o CPA mede o custo de uma conversão final. Para ser rentável, o CPA deve ser menor que a margem de contribuição do produto. CPA = Gasto em anúncios ÷ Número de vendas.",
    related: ["CPL", "ROAS", "Conversão", "CAC"],
  },
  {
    id: "lookalike",
    term: "Lookalike (Público Semelhante)",
    category: "Meta Ads & Tráfego Pago",
    definition: "Tipo de público do Meta Ads criado pelo algoritmo com base em uma fonte de dados (lista de compradores, visitantes do site, engajadores). O sistema encontra pessoas com características similares à fonte. A porcentagem (1%, 2%, 5%, 10%) define o quão parecido com a fonte é o público — 1% é o mais similar e menor volume, 10% é o mais amplo e menos preciso.",
    example: "Uma lista de 500 compradores do seu curso é usada como fonte. O Lookalike 1% encontra os 1% da população brasileira no Facebook mais parecidos com esses 500 compradores — aproximadamente 1 milhão de pessoas.",
    related: ["Público Frio", "Retargeting", "Pixel", "CAPI"],
  },
  {
    id: "retargeting",
    term: "Retargeting (Remarketing)",
    category: "Meta Ads & Tráfego Pago",
    definition: "Prática de mostrar anúncios para pessoas que já interagiram com sua marca — visitaram o site, assistiram a um vídeo, abriram um formulário, ou estão na sua lista de email. O retargeting converte 3-5x melhor que anúncios para público frio porque o trabalho de apresentação já foi feito.",
    example: "Visitantes da página de vendas que não compraram nos últimos 30 dias recebem anúncios específicos com depoimentos de alunos e informações sobre a garantia — atacando as principais objeções de quem já mostrou interesse.",
    related: ["Pixel", "Público Quente", "CAPI", "Funil de Anúncios"],
  },
  {
    id: "pixel",
    term: "Pixel (Meta Pixel)",
    category: "Meta Ads & Tráfego Pago",
    definition: "Código JavaScript instalado no site que rastreia o comportamento dos visitantes e envia dados para o Meta. Permite criar públicos de retargeting (visitantes, compradores, carrinho abandonado) e otimizar campanhas para conversões específicas. Após o iOS 14, o pixel de navegador tem limitações — a CAPI (API de Conversões) é o complemento essencial.",
    related: ["CAPI", "Retargeting", "Evento de Conversão", "iOS 14"],
  },
  {
    id: "capi",
    term: "CAPI (Conversions API / API de Conversões)",
    category: "Meta Ads & Tráfego Pago",
    definition: "Sistema que envia dados de conversão diretamente do servidor para o Meta, sem depender de cookies ou JavaScript no navegador. Soluciona o problema de rastreamento criado pelo iOS 14 e bloqueadores de anúncio. Com CAPI configurado corretamente, a taxa de rastreamento sobe de 50-60% (só pixel) para 85-95%.",
    related: ["Pixel", "iOS 14", "Evento de Conversão", "Server-Side Tracking"],
  },
  {
    id: "cbo",
    term: "CBO (Campaign Budget Optimization)",
    category: "Meta Ads & Tráfego Pago",
    definition: "Configuração de campanha no Meta Ads onde o orçamento é definido no nível da campanha e o algoritmo distribui automaticamente entre os conjuntos de anúncios com base na performance em tempo real. Ideal para campanhas com dados históricos suficientes. O algoritmo favorece os conjuntos que estão convertendo melhor.",
    related: ["ABO", "Conjunto de Anúncios", "Orçamento de Campanha"],
  },
  {
    id: "abo",
    term: "ABO (Ad Set Budget Optimization)",
    category: "Meta Ads & Tráfego Pago",
    definition: "Configuração onde o orçamento é definido individualmente para cada conjunto de anúncios. Oferece controle total sobre quanto cada público recebe — essencial na fase de testes para garantir dados iguais entre conjuntos e poder comparar performance com precisão.",
    related: ["CBO", "Conjunto de Anúncios", "Teste A/B"],
  },
  {
    id: "fase-de-aprendizado",
    term: "Fase de Aprendizado (Learning Phase)",
    category: "Meta Ads & Tráfego Pago",
    definition: "Período após criação ou alteração significativa de um conjunto de anúncios, durante o qual o algoritmo do Meta coleta dados para otimizar a entrega. Requer 50 eventos de otimização para sair dessa fase. Mexer no conjunto durante a fase de aprendizado reinicia o contador. A performance durante o aprendizado é instável e não representa o potencial real da campanha.",
    related: ["Conjunto de Anúncios", "Evento de Conversão", "Otimização"],
  },
  {
    id: "frequencia",
    term: "Frequência",
    category: "Meta Ads & Tráfego Pago",
    definition: "Número médio de vezes que uma pessoa do público-alvo viu seu anúncio. Frequência acima de 3 para público frio indica saturação — as pessoas já viram o anúncio múltiplas vezes sem converter, o que aumenta o CPM e reduz a performance. Para retargeting quente, frequência de 5-8 nas últimas 48h de lançamento é intencional e eficaz.",
    related: ["CPM", "Saturação de Criativo", "Fadiga de Audiência"],
  },
  {
    id: "ugc",
    term: "UGC (User Generated Content)",
    category: "Meta Ads & Tráfego Pago",
    definition: "Conteúdo criado por usuários ou produzido de forma a parecer orgânico — geralmente gravado na câmera frontal do celular, sem produção elaborada. Em Meta Ads, vídeos no estilo UGC frequentemente superam produções profissionais porque parecem conteúdo nativo do feed, gerando menos resistência do usuário. Reduz custo de produção e permite testar mais variações.",
    related: ["Criativo", "Hook Rate", "CTR", "Teste A/B de Criativo"],
  },
  {
    id: "whitelisting",
    term: "Whitelisting",
    category: "Meta Ads & Tráfego Pago",
    definition: "Prática de rodar anúncios através do perfil de um criador de conteúdo ou influenciador, em vez da sua própria página de empresa. O anúncio aparece como sendo do influenciador, o que reduz a resistência do público e aumenta a taxa de clique. Exige acesso ao Gerenciador de Negócios do influenciador.",
    related: ["UGC", "Influenciador", "CTR"],
  },

  // ─── ALGORITMOS & PLATAFORMAS ───────────────────────────────────
  {
    id: "fyp",
    term: "FYP (For You Page)",
    category: "Algoritmos & Plataformas",
    definition: "Página inicial do TikTok, alimentada exclusivamente pelo algoritmo de recomendação. Diferente do Instagram Feed (que prioriza quem você segue), o FYP mostra conteúdo de qualquer conta — conhecida ou não — com base no comportamento do usuário. É o mecanismo que permite que contas com zero seguidores virem virais.",
    related: ["Algoritmo TikTok", "Completion Rate", "Rewatch Rate"],
    lessonIds: ["tiktok-deep-1"],
  },
  {
    id: "completion-rate",
    term: "Completion Rate (Taxa de Conclusão)",
    category: "Algoritmos & Plataformas",
    definition: "Percentual de pessoas que assiste ou consume um conteúdo até o final. É a métrica mais honesta de valor de um conteúdo — difícil de manipular, reflete genuinamente se a entrega sustentou o interesse do início ao fim. No TikTok, é o fator de maior peso no algoritmo (35% do score). Benchmarks: vídeos curtos &gt;70%, médios &gt;50%, longos &gt;40%.",
    related: ["Hook Rate", "Rewatch Rate", "Algoritmo TikTok", "Retenção de Audiência"],
    lessonIds: ["atencao-1", "atencao-2", "tiktok-deep-1", "ig-quatro-sistemas", "segredo-3-predicao-comportamental"],
  },
  {
    id: "rewatch-rate",
    term: "Rewatch Rate (Taxa de Revisão)",
    category: "Algoritmos & Plataformas",
    definition: "Percentual de usuários que assiste ao vídeo mais de uma vez. É o sinal mais raro e mais valorizado pelos algoritmos — indica que o conteúdo tem densidade de informação suficiente para justificar rever. No TikTok representa aproximadamente 25% do score de ranking. Conteúdo que gera rewatch: listas densas, revelações no final, informação com muito valor comprimido.",
    related: ["Completion Rate", "Algoritmo TikTok", "Hook Rate"],
    lessonIds: ["atencao-2", "tiktok-deep-1", "ig-quatro-sistemas", "segredo-3-predicao-comportamental"],
  },
  {
    id: "hook-rate",
    term: "Hook Rate (Taxa de Parada)",
    category: "Algoritmos & Plataformas",
    definition: "Percentual de pessoas que para o scroll e começa a consumir o conteúdo ao ver os primeiros segundos. É determinado pelo hook (os primeiros 1-3 segundos do vídeo ou a primeira linha visível do texto). Um Hook Rate abaixo de 20% indica que o conteúdo não está competindo bem pela atenção no feed.",
    related: ["Hook", "Completion Rate", "CTR", "Algoritmo"],
    lessonIds: ["atencao-1", "tiktok-deep-1", "segredo-3-predicao-comportamental"],
  },
  {
    id: "avd",
    term: "AVD (Average View Duration)",
    category: "Algoritmos & Plataformas",
    definition: "Duração média de visualização de um vídeo no YouTube, em minutos e segundos absolutos (não em porcentagem). Para o algoritmo de sugestão do YouTube, o AVD absoluto importa mais que a porcentagem — um vídeo de 20 minutos com AVD de 12 min gera mais watch time total que um vídeo de 5 min com 80% de conclusão.",
    related: ["Watch Time", "YouTube Algorithm", "Completion Rate"],
    lessonIds: ["yt-dois-motores"],
  },
  {
    id: "watch-time",
    term: "Watch Time",
    category: "Algoritmos & Plataformas",
    definition: "Tempo total acumulado que os usuários passam assistindo aos vídeos de um canal no YouTube. É uma das métricas mais importantes para o algoritmo de sugestão e para monetização (necessário 4.000 horas de watch time público nos últimos 12 meses para se qualificar ao YouTube Partner Program). Playlists são uma das melhores ferramentas para aumentar watch time de sessão.",
    related: ["AVD", "YouTube Algorithm", "Playlists"],
    lessonIds: ["yt-dois-motores"],
  },
  {
    id: "eeat",
    term: "E-E-A-T (Experience, Expertise, Authoritativeness, Trustworthiness)",
    category: "Algoritmos & Plataformas",
    definition: "Framework do Google para avaliar a qualidade do conteúdo e do criador. Experience: autor tem experiência direta com o tema. Expertise: demonstra profundidade real de conhecimento. Authoritativeness: outros sites relevantes referenciam o conteúdo. Trustworthiness: o site e o autor são confiáveis. Fundamental para ranquear no Google, especialmente em nichos de saúde, finanças e direito.",
    related: ["SEO", "Google Algorithm", "Backlinks", "Autoridade de Domínio"],
  },
  {
    id: "core-web-vitals",
    term: "Core Web Vitals",
    category: "Algoritmos & Plataformas",
    definition: "Conjunto de métricas de experiência do usuário que o Google usa como fator de ranqueamento: LCP (Largest Contentful Paint — velocidade de carregamento), FID (First Input Delay — responsividade), CLS (Cumulative Layout Shift — estabilidade visual). Sites com baixo desempenho nos Core Web Vitals perdem posições no ranking do Google.",
    related: ["SEO", "Google Algorithm", "E-E-A-T"],
  },
  {
    id: "algoritmo-de-recomendacao",
    term: "Algoritmo de Recomendação",
    category: "Algoritmos & Plataformas",
    definition: "Sistema de inteligência artificial que decide qual conteúdo mostrar para qual usuário, com o objetivo central de maximizar o tempo na plataforma. Aprende com o comportamento do usuário (cliques, tempo de visualização, interações) e usa esse aprendizado para prever qual conteúdo vai reter aquela pessoa por mais tempo.",
    related: ["Machine Learning", "FYP", "Watch Time", "Engajamento"],
    lessonIds: ["atencao-1", "atencao-2", "tiktok-deep-1", "segredo-1-ilusao", "segredo-3-predicao-comportamental"],
  },
  {
    id: "shadow-ban",
    term: "Shadow Ban",
    category: "Algoritmos & Plataformas",
    definition: "Redução severa e não declarada do alcance de uma conta, aplicada pelo algoritmo da plataforma em resposta a comportamentos que violam as diretrizes (spam, uso de hashtags proibidas, conteúdo sensível, compra de seguidores). A conta não é notificada — simplesmente para de aparecer para não-seguidores. Diagnosticado quando o alcance cai abruptamente sem motivo aparente.",
    related: ["Algoritmo", "Diretrizes da Plataforma", "Alcance Orgânico"],
    lessonIds: ["atencao-2", "ig-quatro-sistemas", "segredo-1-ilusao"],
  },
  {
    id: "saves",
    term: "Saves (Salvamentos)",
    category: "Algoritmos & Plataformas",
    definition: "Ação de salvar um post para ver depois, disponível no Instagram e outras plataformas. É o sinal de maior peso no algoritmo do Instagram Explore e de alta relevância no Reels — indica que o conteúdo tem utilidade prática percebida ('vou precisar disso depois'). Posts com alta taxa de salvamento recebem distribuição amplificada.",
    related: ["Algoritmo Instagram", "Taxa de Engajamento", "Carrossel"],
    lessonIds: ["atencao-2", "ig-quatro-sistemas"],
  },
  {
    id: "collab-post",
    term: "Collab Post",
    category: "Algoritmos & Plataformas",
    definition: "Funcionalidade do Instagram que permite dois criadores publicarem o mesmo post simultaneamente — ele aparece no feed dos seguidores de ambas as contas, com os dois nomes no cabeçalho. É a maneira mais eficiente de dobrar o alcance orgânico imediatamente sem custo adicional. Ideal para lançamentos em parceria.",
    related: ["Lançamento Externo", "Joint Venture", "Alcance Orgânico"],
    lessonIds: ["ig-quatro-sistemas"],
  },

  // ─── COPYWRITING & PERSUASÃO ────────────────────────────────────
  {
    id: "hook",
    term: "Hook (Gancho)",
    category: "Copywriting & Persuasão",
    definition: "O elemento de abertura de um conteúdo — os primeiros 1-3 segundos de um vídeo, a primeira frase de um email, o headline de um anúncio — responsável por capturar a atenção e fazer a pessoa continuar. Um hook eficaz ativa curiosidade, reconhecimento próprio, dissonância cognitiva ou antecipação de recompensa.",
    example: "Hook ruim: 'Hoje vou falar sobre lançamentos digitais'. Hook forte: 'Você está perdendo R$30k por mês por não saber isso sobre lançamentos'.",
    related: ["Hook Rate", "Headline", "CTA", "Copywriting"],
  },
  {
    id: "headline",
    term: "Headline (Título/Manchete)",
    category: "Copywriting & Persuasão",
    definition: "Título principal de uma página de vendas, email, anúncio ou post. David Ogilvy disse que 80 centavos de cada dólar gasto em publicidade é desperdiçado se o headline falha — porque é o que decide se a pessoa vai ou não ler o resto. Um headline eficaz deve comunicar o maior benefício ou despertar a maior curiosidade em menos de 10 segundos de leitura.",
    related: ["Hook", "Copywriting", "Promessa", "VSL"],
  },
  {
    id: "cta",
    term: "CTA (Call to Action)",
    category: "Copywriting & Persuasão",
    definition: "Instrução explícita e específica que diz ao leitor/espectador qual ação tomar. O CTA deve ser claro, urgente e de baixa fricção. Um CTA eficaz especifica exatamente o que fazer ('Clique no botão abaixo para garantir sua vaga'), o que a pessoa vai receber ('e receber acesso imediato ao curso') e por que agora ('antes que o preço de lançamento expire').",
    example: "CTA fraco: 'Saiba mais'. CTA forte: 'Clique aqui e garanta sua vaga agora — o preço de R$997 só vale até domingo às 23h59'.",
    related: ["Hook", "Conversão", "Urgência", "Copywriting"],
  },
  {
    id: "mecanismo-unico",
    term: "Mecanismo Único",
    category: "Copywriting & Persuasão",
    definition: "O elemento diferenciador que explica POR QUE o seu método funciona onde outros falharam. Não é uma lista de features — é a narrativa que responde 'qual é o insight novo que torna isso possível?'. O mecanismo único justifica por que o cliente vai ter sucesso desta vez mesmo tendo falhado antes.",
    example: "Não 'nosso curso ensina marketing digital'. Mas 'o Método dos 3 Pilares que identifica o canal de tráfego com maior ROI para o seu nicho específico antes de gastar R$1 — eliminando o maior erro dos iniciantes'.",
    related: ["VSL", "Posicionamento", "Proposta Única de Valor"],
  },
  {
    id: "big-idea",
    term: "Big Idea (Grande Ideia)",
    category: "Copywriting & Persuasão",
    definition: "O conceito central e surpreendente que ancora toda uma campanha ou peça de copy. Criada por David Ogilvy, a Big Idea é o insight criativo que faz a campanha ser memorável e compartilhada. Uma Big Idea verdadeira pode sustentar anos de comunicação. Diferente de um slogan — é uma perspectiva nova sobre o problema do cliente.",
    related: ["Copywriting", "Posicionamento", "Criativo"],
  },
  {
    id: "prova-social",
    term: "Prova Social (Social Proof)",
    category: "Copywriting & Persuasão",
    definition: "Princípio psicológico documentado por Robert Cialdini: as pessoas usam o comportamento e as opiniões dos outros como guia para suas próprias decisões em situações de incerteza. Em marketing digital, se manifesta como: depoimentos de alunos, número de compradores, logos de clientes, avaliações, resultados documentados.",
    related: ["Gatilho Mental", "Depoimento", "Case de Sucesso", "Cialdini"],
  },
  {
    id: "escassez",
    term: "Escassez (Scarcity)",
    category: "Copywriting & Persuasão",
    definition: "Gatilho psicológico que aumenta o valor percebido de algo quando há limitação de quantidade ou disponibilidade. No marketing digital, pode ser: vagas limitadas (escassez real — turmas com limite têm razão legítima), bônus para os primeiros compradores ou preço de lançamento válido apenas por período determinado. Escassez falsa destrói credibilidade permanentemente.",
    related: ["Urgência", "FOMO", "Gatilho Mental", "Carência"],
  },
  {
    id: "urgência",
    term: "Urgência",
    category: "Copywriting & Persuasão",
    definition: "Gatilho psicológico que motiva ação imediata através da limitação de tempo. Diferente da escassez (que limita quantidade), a urgência limita o prazo. É o mecanismo central do fechamento de carrinho — sem deadline, não há urgência, e sem urgência, a maioria procrastina indefinidamente. Daniel Ariely demonstrou que deadlines são o principal antídoto à procrastinação.",
    related: ["Escassez", "FOMO", "Gatilho Mental", "Fechamento de Carrinho"],
  },
  {
    id: "fomo",
    term: "FOMO (Fear of Missing Out)",
    category: "Copywriting & Persuasão",
    definition: "Medo de ficar de fora de uma experiência ou oportunidade que outros estão aproveitando. É um dos gatilhos emocionais mais poderosos no marketing digital — combina escassez social (outros estão tendo resultado) com urgência (a janela está fechando). Mais eficaz quando baseado em evidências reais: depoimentos recentes, número de compradores.",
    related: ["Urgência", "Escassez", "Gatilho Mental", "Prova Social"],
  },
  {
    id: "gatilho-mental",
    term: "Gatilho Mental",
    category: "Copywriting & Persuasão",
    definition: "Mecanismos psicológicos automáticos que influenciam decisões de compra sem necessitar de análise consciente. Os 12 principais: autoridade, prova social, reciprocidade, comunidade, escassez, urgência, antecipação, evento, transformação, medo de perda, curiosidade e contraste. Estudados por Robert Cialdini no livro 'Influência'.",
    related: ["Escassez", "Urgência", "Prova Social", "Autoridade", "Reciprocidade"],
  },
  {
    id: "reciprocidade",
    term: "Reciprocidade",
    category: "Copywriting & Persuasão",
    definition: "Gatilho psicológico baseado na obrigação social de retribuir o que recebemos. Quando uma marca entrega valor genuíno (conteúdo gratuito, amostra, ajuda), o receptor sente uma pressão social de retribuir. É o princípio por trás do marketing de conteúdo: entregar valor antes de pedir dinheiro.",
    related: ["Gatilho Mental", "Marketing de Conteúdo", "Lead Magnet"],
  },
  {
    id: "authority",
    term: "Autoridade",
    category: "Copywriting & Persuasão",
    definition: "Gatilho psicológico que aumenta a confiança e a propensão à compra quando o vendedor demonstra expertise reconhecida. Elementos que constroem autoridade: credenciais, publicações, aparições na mídia, cases de resultado verificáveis, associação com outras autoridades do nicho, volume de estudantes/clientes.",
    related: ["Gatilho Mental", "Prova Social", "E-E-A-T"],
  },
  {
    id: "curiosity-gap",
    term: "Curiosity Gap (Lacuna de Curiosidade)",
    category: "Copywriting & Persuasão",
    definition: "Técnica de copywriting que cria uma lacuna intencional entre o que a pessoa sabe e o que ela quer saber — forçando a continuação da leitura ou visualização. Funciona porque o cérebro tem aversão a lacunas de conhecimento incompleto. Desenvolvido pelo psicólogo George Loewenstein na Teoria da Curiosidade.",
    example: "'O erro que 90% dos produtores cometem no dia do lançamento...' — a pessoa é forçada a continuar para descobrir qual é o erro.",
    related: ["Hook", "Headline", "Copywriting"],
  },
  {
    id: "swipe-file",
    term: "Swipe File",
    category: "Copywriting & Persuasão",
    definition: "Coleção pessoal de exemplos de copy, anúncios, emails, headlines e peças de marketing que funcionaram — seja do próprio portfólio ou coletados de referências externas. Copywriters profissionais mantêm swipe files para estudar padrões e se inspirar (não copiar) na hora de criar novas peças.",
    related: ["Copywriting", "Referência de Copy", "Headline"],
  },
  {
    id: "carta-de-vendas",
    term: "Carta de Vendas",
    category: "Copywriting & Persuasão",
    definition: "Longa peça de texto estruturada especificamente para vender. Segue uma sequência psicológica: headline → subheadline → história → problema → agitação → solução → mecanismo → prova social → oferta → bônus → garantia → FAQ → CTA. Precursora do VSL — muitas cartas de vendas modernas são convertidas em vídeo.",
    related: ["VSL", "Headline", "CTA", "Copywriting"],
  },

  // ─── EMAIL & WHATSAPP MARKETING ────────────────────────────────
  {
    id: "taxa-de-abertura",
    term: "Taxa de Abertura",
    category: "Email & WhatsApp Marketing",
    definition: "Percentual de destinatários de um email que abriram a mensagem. Calculado como: Emails abertos ÷ Emails entregues × 100. Benchmarks: 15-25% é médio, 25-35% é bom, acima de 35% é excelente para marketing digital PT-BR. A taxa de abertura é majoritariamente determinada pelo assunto (subject line) e pelo nome do remetente.",
    related: ["Taxa de Clique", "Assunto de Email", "Deliverability"],
  },
  {
    id: "taxa-de-clique-email",
    term: "Taxa de Clique (CTR de Email)",
    category: "Email & WhatsApp Marketing",
    definition: "Percentual de destinatários que clicaram em pelo menos um link do email. Calculado como: Cliques únicos ÷ Emails entregues × 100. Benchmarks: 2-5% é médio, 5-10% é bom. A taxa de clique é determinada pelo conteúdo do email e pelo alinhamento entre o assunto (que prometeu algo) e o corpo (que entregou essa promessa).",
    related: ["Taxa de Abertura", "CTA", "Copywriting de Email"],
  },
  {
    id: "deliverability",
    term: "Deliverability (Entregabilidade)",
    category: "Email & WhatsApp Marketing",
    definition: "Capacidade dos emails de chegar na caixa de entrada (não na pasta de spam). Afetada por: reputação do domínio, reputação do IP do servidor de envio, taxa de spam reports, taxa de bounces, engajamento histórico da lista. Manter boa deliverability exige higienização regular da lista e práticas de envio consistentes.",
    related: ["Bounce Rate", "Taxa de Abertura", "Lista de Email"],
  },
  {
    id: "bounce-email",
    term: "Bounce (Email)",
    category: "Email & WhatsApp Marketing",
    definition: "Email que não pôde ser entregue ao destinatário. Hard bounce: endereço inválido ou inexistente — o contato deve ser removido imediatamente. Soft bounce: problema temporário (caixa cheia, servidor fora do ar) — alguns provedores tentam reenviar automaticamente. Taxa de bounce acima de 2% prejudica a reputação do remetente.",
    related: ["Deliverability", "Lista de Email", "Higienização de Lista"],
  },
  {
    id: "lead-magnet",
    term: "Lead Magnet (Isca Digital)",
    category: "Email & WhatsApp Marketing",
    definition: "Material gratuito de alto valor percebido oferecido em troca do contato (email, telefone) do visitante. Deve resolver um problema específico e imediato do público-alvo. Quanto mais específico o problema que resolve, melhor a qualidade do lead capturado. Formatos: ebook, mini-curso, checklist, template, calculadora, planilha, quiz.",
    example: "'Checklist: 27 pontos para revisar antes de abrir o carrinho do seu lançamento' — altamente específico, valor claro, download imediato.",
    related: ["Lista de Email", "Funil de Captura", "Landing Page"],
    lessonIds: ["segredo-4-dois-jogos", "segredo-5-framework-independencia", "segredo-exercicio-auditoria"],
  },
  {
    id: "nurturing",
    term: "Nurturing (Nutrição de Leads)",
    category: "Email & WhatsApp Marketing",
    definition: "Processo de construir relacionamento e confiança com leads ao longo do tempo através de conteúdo relevante, até que estejam prontos para comprar. Uma sequência de nurturing típica entrega valor genuíno sem vender por 3-7 emails antes de apresentar uma oferta. Leads que passaram por nurturing convertem 2-5x melhor que leads frios.",
    related: ["Sequência de Email", "Lead Scoring", "Automação de Email"],
    lessonIds: ["segredo-4-dois-jogos", "segredo-5-framework-independencia"],
  },
  {
    id: "lead-scoring",
    term: "Lead Scoring",
    category: "Email & WhatsApp Marketing",
    definition: "Sistema que atribui pontos aos leads com base em comportamentos e características, para identificar quem está mais próximo de comprar. Pontos são adicionados por ações como abrir emails, clicar em links, visitar a página de vendas, assistir a um webinar. Leads com pontuação alta recebem abordagem mais direta de venda.",
    related: ["Nurturing", "CRM", "Automação de Marketing"],
  },
  {
    id: "opt-in",
    term: "Opt-in",
    category: "Email & WhatsApp Marketing",
    definition: "Ato de uma pessoa consentir ativamente em receber comunicações de marketing (email, SMS, WhatsApp). Double opt-in exige confirmação por email após o cadastro — gera listas menores mas de maior qualidade e entregabilidade. Exigido por lei em muitos países (GDPR na Europa, LGPD no Brasil).",
    related: ["LGPD", "Lista de Email", "Deliverability", "Consentimento"],
    lessonIds: ["segredo-4-dois-jogos", "segredo-5-framework-independencia", "segredo-exercicio-auditoria"],
  },
  {
    id: "broadcast",
    term: "Broadcast",
    category: "Email & WhatsApp Marketing",
    definition: "Envio de email ou mensagem de WhatsApp para toda a lista (ou um segmento dela) de uma vez, em um momento específico. Diferente das sequências automáticas, broadcasts são enviados em datas determinadas — usados para comunicados de abertura de carrinho, promoções sazonais, conteúdo relevante de momento.",
    related: ["Sequência de Email", "Segmentação", "Automação"],
  },
  {
    id: "segmentação-lista",
    term: "Segmentação de Lista",
    category: "Email & WhatsApp Marketing",
    definition: "Divisão da lista de contatos em grupos menores com base em características ou comportamentos comuns — para enviar mensagens mais relevantes para cada grupo. Segmentos comuns: compradores vs. não-compradores, por produto adquirido, por engajamento (quem abriu emails recentemente vs. inativos), por fonte de captura.",
    related: ["Lead Scoring", "Personalização", "Automação de Email"],
  },

  // ─── ANALYTICS & MÉTRICAS ──────────────────────────────────────
  {
    id: "cac",
    term: "CAC (Custo de Aquisição de Cliente)",
    category: "Analytics & Métricas",
    definition: "Custo total médio para adquirir um novo cliente pagante, incluindo todos os gastos com marketing e vendas. CAC = (Total gasto em marketing + Vendas) ÷ Número de novos clientes no período. Diferente do CPA (que considera apenas o custo do anúncio) — o CAC inclui salários, ferramentas, eventos e toda a estrutura de aquisição.",
    related: ["LTV", "ROAS", "CPA", "Margem de Lucro"],
    lessonIds: ["segredo-5-framework-independencia"],
  },
  {
    id: "ltv",
    term: "LTV (Lifetime Value / Valor do Cliente no Tempo)",
    category: "Analytics & Métricas",
    definition: "Receita total esperada de um cliente durante todo o relacionamento com a empresa. LTV = Ticket Médio × Frequência de Compra × Tempo de Relacionamento. Para assinaturas: LTV = Mensalidade × Tempo Médio de Permanência. O LTV é o teto máximo que você pode gastar para adquirir um cliente e ainda ser lucrativo.",
    example: "Um membership de R$297/mês onde os membros ficam em média 10 meses tem LTV de R$2.970. Você pode gastar até R$990 (33% do LTV) em CAC e ainda manter margens saudáveis.",
    related: ["CAC", "Churn Rate", "Receita Recorrente", "Escada de Valor"],
    lessonIds: ["segredo-4-dois-jogos", "segredo-5-framework-independencia"],
  },
  {
    id: "churn-rate",
    term: "Churn Rate (Taxa de Cancelamento)",
    category: "Analytics & Métricas",
    definition: "Percentual de clientes ou assinantes que cancelam em um período. Churn mensal de 10% significa que você perde metade da base em 7 meses. Para crescer, você precisa adquirir clientes mais rápido do que os perde — o que se torna progressivamente mais caro. Reduzir o churn é frequentemente mais rentável do que aumentar a aquisição.",
    related: ["LTV", "Receita Recorrente", "NPS", "Onboarding"],
    lessonIds: ["segredo-5-framework-independencia"],
  },
  {
    id: "nps",
    term: "NPS (Net Promoter Score)",
    category: "Analytics & Métricas",
    definition: "Métrica de satisfação de cliente baseada em uma única pergunta: 'De 0 a 10, qual a probabilidade de você recomendar para um amigo?' Promotores (9-10): potenciais embaixadores e indicadores. Passivos (7-8): satisfeitos mas não entusiasmados. Detratores (0-6): risco de churn e reputação negativa. NPS = % Promotores - % Detratores. Acima de 50 é excelente.",
    related: ["Churn Rate", "Indicação", "LTV", "Satisfação de Cliente"],
  },
  {
    id: "mrr",
    term: "MRR (Monthly Recurring Revenue)",
    category: "Analytics & Métricas",
    definition: "Receita recorrente mensal — o total de receita previsível gerado pelas assinaturas ativas em um mês. Principal métrica de saúde para negócios de membership e SaaS. MRR cresce quando: novos assinantes entram, assinantes fazem upgrade. MRR decresce com churn e downgrades. MRR × 12 = ARR (Receita Recorrente Anual).",
    related: ["ARR", "Churn Rate", "LTV", "Receita Recorrente"],
    lessonIds: ["segredo-4-dois-jogos", "segredo-5-framework-independencia", "segredo-exercicio-auditoria"],
  },
  {
    id: "taxa-de-conversao",
    term: "Taxa de Conversão",
    category: "Analytics & Métricas",
    definition: "Percentual de visitantes ou leads que realizam a ação desejada (compra, cadastro, clique). Calculada como: Conversões ÷ Total de visitantes/leads × 100. Benchmarks para lançamentos PT-BR: landing page de captura 20-40%, webinar 3-10% de conversão em vendas, página de vendas 1-5% de visitantes únicos.",
    related: ["CRO", "Funil de Vendas", "ROAS", "A/B Test"],
  },
  {
    id: "cro",
    term: "CRO (Conversion Rate Optimization)",
    category: "Analytics & Métricas",
    definition: "Processo sistemático de aumentar a porcentagem de visitantes que realizam uma ação desejada, sem necessariamente aumentar o tráfego. Usa testes A/B, análise de comportamento (mapas de calor, gravações de sessão), pesquisas com usuários e análise de dados para identificar e eliminar barreiras à conversão.",
    related: ["Taxa de Conversão", "Teste A/B", "Heatmap", "Landing Page"],
  },
  {
    id: "funil-de-vendas",
    term: "Funil de Vendas",
    category: "Analytics & Métricas",
    definition: "Representação do processo de transformação de visitantes desconhecidos em clientes. A forma de funil representa o afunilamento progressivo — muitas pessoas entram no topo, poucas chegam ao fundo (compra). Estágios típicos: Consciência (awareness) → Interesse → Consideração → Intenção → Compra → Fidelização.",
    related: ["Taxa de Conversão", "Topo/Meio/Fundo de Funil", "Lead"],
  },
  {
    id: "utm",
    term: "UTM (Urchin Tracking Module)",
    category: "Analytics & Métricas",
    definition: "Parâmetros adicionados a URLs para rastrear a origem do tráfego no Google Analytics. Os 5 parâmetros: utm_source (de onde vem — ex: facebook), utm_medium (o canal — ex: paid), utm_campaign (o nome da campanha), utm_content (variação do criativo), utm_term (keyword). Essencial para medir qual canal, campanha e criativo gera mais conversões.",
    example: "https://seusite.com/lancamento?utm_source=instagram&utm_medium=reels&utm_campaign=lancamento-maio&utm_content=hook-resultado",
    related: ["Google Analytics", "Atribuição", "ROAS Real"],
  },
  {
    id: "atribuicao",
    term: "Atribuição (Attribution)",
    category: "Analytics & Métricas",
    definition: "Modelo que define qual touchpoint (ponto de contato) recebe o crédito por uma venda quando o cliente passou por múltiplos canais antes de comprar. Modelos principais: Último clique (padrão do Google Analytics), Primeiro clique, Linear (divide igualmente entre todos), Data-Driven (machine learning). O Meta Ads usa por padrão '7 dias pós-clique + 1 dia pós-visualização', frequentemente exagerando o ROAS real.",
    related: ["UTM", "ROAS", "Google Analytics", "Multi-Touch"],
  },
  {
    id: "saúde-score",
    term: "Health Score (Score de Saúde)",
    category: "Analytics & Métricas",
    definition: "Pontuação composta que agrega múltiplas métricas em um único número para avaliar a saúde geral de um lançamento ou campanha. Em lançamentos, combina métricas de receita, engajamento de email, conversão e tráfego em um score de 0-100, facilitando a tomada de decisão sem precisar analisar cada métrica individualmente.",
    related: ["KPI", "Dashboard", "Métricas de Lançamento"],
  },

  // ─── MONETIZAÇÃO & FUNIS ────────────────────────────────────────
  {
    id: "upsell",
    term: "Upsell",
    category: "Monetização & Funis",
    definition: "Oferta de produto de maior valor apresentada após a decisão inicial de compra, aproveitando o 'modo compra' ativado do cliente. O upsell ideal é uma versão superior ou mais completa do que foi comprado. Aceito com um único clique (sem preencher cartão novamente). Taxa de aceitação média: 15-30% dos compradores.",
    example: "Cliente comprou o curso básico por R$497. Imediatamente após a confirmação, é apresentado o 'Pacote Completo' (curso avançado + mentoria mensal) por R$500 adicionais.",
    related: ["Downsell", "Order Bump", "Cross-sell", "Escada de Valor"],
  },
  {
    id: "downsell",
    term: "Downsell",
    category: "Monetização & Funis",
    definition: "Oferta de menor valor e preço apresentada quando o cliente recusa o upsell. A lógica: o cliente já mostrou interesse, apenas não quis (ou não pode) pagar o valor do upsell. O downsell oferece uma versão menor ou fragmentada, recuperando parte da receita que seria perdida com a recusa. Taxa de aceitação: 10-20% dos que recusaram o upsell.",
    related: ["Upsell", "Order Bump", "Funil de Vendas"],
  },
  {
    id: "order-bump",
    term: "Order Bump",
    category: "Monetização & Funis",
    definition: "Oferta adicional apresentada dentro do checkout, antes da confirmação do pagamento — geralmente como uma caixa de seleção. É o elemento de maior ROI de otimização de checkout, com taxas de aceitação de 20-40%. O produto deve ser complementar, de baixo preço relativo (10-30% do produto principal) e resolver um problema imediato do comprador.",
    related: ["Upsell", "Downsell", "Checkout", "CRO"],
  },
  {
    id: "escada-de-valor",
    term: "Escada de Valor (Value Ladder)",
    category: "Monetização & Funis",
    definition: "Arquitetura de produtos ordenados por valor e preço crescentes, onde cada degrau entrega mais resultado e cobra mais. Conceito criado por Russell Brunson. Permite que cada produto pague o custo de aquisição do próximo, e que clientes que querem mais possam subir naturalmente. Os degraus típicos: isca gratuita → produto de entrada → produto core → high ticket → continuidade.",
    related: ["LTV", "Upsell", "Funil de Vendas", "Receita Recorrente"],
    lessonIds: ["segredo-5-framework-independencia"],
  },
  {
    id: "membership",
    term: "Membership (Associação/Plano)",
    lessonIds: ["segredo-5-framework-independencia"],
    category: "Monetização & Funis",
    definition: "Modelo de receita recorrente onde o cliente paga mensalmente para acesso contínuo a conteúdo, comunidade, suporte ou serviço. É o modelo com maior previsibilidade de receita e maior LTV. O maior desafio é o churn — a taxa de cancelamento. Estratégias de retenção: onboarding excepcional, comunidade forte, entrega constante de novo valor.",
    related: ["Churn Rate", "MRR", "LTV", "Comunidade"],
  },
  {
    id: "ticket-medio",
    term: "Ticket Médio",
    category: "Monetização & Funis",
    definition: "Valor médio de cada venda. Calculado como: Receita total ÷ Número de vendas no período. Aumentar o ticket médio sem aumentar o número de clientes é uma das alavancas mais eficientes de crescimento — tipicamente via order bumps, upsells ou migrando para produto de maior valor.",
    related: ["LTV", "Upsell", "Order Bump", "Escada de Valor"],
  },
  {
    id: "receita-recorrente",
    term: "Receita Recorrente",
    category: "Monetização & Funis",
    definition: "Receita que é cobrada e recebida automaticamente em intervalos regulares (mensal, trimestral, anual) de assinantes ou membros. Proporciona previsibilidade financeira, permite planejamento de longo prazo e cria um 'piso' de receita independente de novos lançamentos. Base de todo negócio de SaaS e memberships.",
    related: ["MRR", "LTV", "Churn Rate", "Membership"],
  },
  {
    id: "high-ticket",
    term: "High Ticket",
    category: "Monetização & Funis",
    definition: "Produtos ou serviços de alto valor, tipicamente acima de R$2.000. Exige processo de venda mais consultivo (chamada de diagnóstico, proposta personalizada), mas permite margens altíssimas e base de clientes menor e mais qualificada. Frequentemente vendido via chamada 1:1, webinar ou evento ao vivo.",
    related: ["Escada de Valor", "Mentoria", "Consultoria", "Closer"],
  },
  {
    id: "funil-de-webinar",
    term: "Funil de Webinar",
    category: "Monetização & Funis",
    definition: "Funil de vendas centrado em um webinar (ao vivo ou evergreen) como principal mecanismo de conversão. Estrutura: anúncio/conteúdo → inscrição no webinar → emails de confirmação e lembrete → webinar (conteúdo + oferta) → sequência de follow-up pós-webinar. Um dos funis de maior conversão para produtos de R$497-R$2.997.",
    related: ["Webinar Evergreen", "Funil Perpétuo", "VSL", "Landing Page"],
  },

  // ─── AUTOMAÇÃO & FERRAMENTAS ────────────────────────────────────
  {
    id: "crm",
    term: "CRM (Customer Relationship Management)",
    category: "Automação & Ferramentas",
    definition: "Sistema para gerenciar o relacionamento com clientes e leads — registrando interações, histórico de compras, estágio no funil e atividades da equipe de vendas. Para produtores digitais, ferramentas como RD Station e ActiveCampaign funcionam como CRM integrado com email marketing e automações.",
    related: ["Automação de Marketing", "Lead Scoring", "Pipeline de Vendas"],
  },
  {
    id: "automação-de-marketing",
    term: "Automação de Marketing",
    category: "Automação & Ferramentas",
    definition: "Uso de software para executar tarefas de marketing repetitivas de forma automática — envio de emails em datas específicas, segmentação de lista por comportamento, lead scoring, notificações de vendas, follow-ups. Elimina trabalho manual e garante que cada lead receba a comunicação certa no momento certo.",
    related: ["CRM", "Sequência de Email", "Lead Scoring", "Funil Perpétuo"],
  },
  {
    id: "manychat",
    term: "ManyChat",
    category: "Automação & Ferramentas",
    definition: "Plataforma de automação de conversas no Instagram Direct e WhatsApp. Permite criar fluxos automáticos que respondem a palavras-chave nos comentários ou DMs — enviando um link de lead magnet para quem comentar 'QUERO', por exemplo. Altamente eficaz para captura de leads a partir de Reels e posts.",
    related: ["Instagram DM", "Automação", "Lead Magnet", "Chatbot"],
  },
  {
    id: "deadline-funnel",
    term: "Deadline Funnel",
    category: "Automação & Ferramentas",
    definition: "Ferramenta que cria deadlines individuais e personalizados para cada usuário em um funil perpétuo — cada pessoa tem seu próprio contador regressivo que expira em um momento único para ela. Quando o prazo vence, a página de vendas redireciona para uma página de 'oferta encerrada'. Garante que a urgência seja real, não fake.",
    related: ["Funil Perpétuo", "Urgência", "Lançamento Perpétuo", "Evergreen"],
  },
  {
    id: "hotmart",
    term: "Hotmart",
    category: "Automação & Ferramentas",
    definition: "Maior plataforma de produtos digitais do Brasil. Permite hospedar e vender cursos, ebooks e memberships, com sistema de pagamento integrado, checkout otimizado, área de membros, gerenciamento de afiliados, processamento de pagamentos parcelados e relatórios de venda. Cobra comissão de 9,9% + R$1,00 por venda.",
    related: ["Kiwify", "Eduzz", "Afiliado", "Checkout"],
  },
  {
    id: "kiwify",
    term: "Kiwify",
    category: "Automação & Ferramentas",
    definition: "Plataforma brasileira de venda de produtos digitais, concorrente da Hotmart com foco em facilidade de uso e checkout de alta conversão. Taxa: 3,49% + R$1,00 por venda (mais baixa que a Hotmart). Inclui: página de vendas, checkout com upsell/order bump, área de membros, gestão de afiliados e integrações com ferramentas de email.",
    related: ["Hotmart", "Eduzz", "Afiliado", "Checkout"],
  },
  {
    id: "everwebinar",
    term: "EverWebinar / WebinarJam",
    category: "Automação & Ferramentas",
    definition: "Plataformas para hospedar webinars ao vivo (WebinarJam) e webinars evergreen/simulados (EverWebinar). O EverWebinar permite que um webinar gravado seja exibido como se fosse ao vivo, com aparência de participantes em tempo real, chat simulado e sessão de perguntas — aumentando a taxa de comparecimento e conversão.",
    related: ["Webinar Evergreen", "Funil Perpétuo", "VSL"],
  },
  {
    id: "opus-clip",
    term: "Opus Clip",
    category: "Automação & Ferramentas",
    definition: "Ferramenta do agente que analisa vídeos longos e seleciona automaticamente os trechos de maior impacto para criar Shorts, Reels e TikToks. Reduz de horas para minutos o trabalho de repurposing de conteúdo longo. Adiciona captions automáticos, destaca palavras-chave e formata para o formato vertical 9:16.",
    related: ["Repurposing", "Shorts", "Reels", "TikTok"],
  },
  {
    id: "capcut",
    term: "CapCut",
    category: "Automação & Ferramentas",
    definition: "Editor de vídeo mobile e desktop da ByteDance (mesma empresa do TikTok), gratuito e com recursos avançados. Inclui: templates virais, legendas automáticas com sincronização, remoção de fundo, transições, efeitos sonoros e biblioteca de músicas. Tem integração nativa com TikTok e é a ferramenta preferida de criadores de conteúdo vertical.",
    related: ["TikTok", "Reels", "Edição de Vídeo", "UGC"],
  },
  {
    id: "metricool",
    term: "Metricool",
    category: "Automação & Ferramentas",
    definition: "Plataforma de analytics e agendamento de redes sociais. Permite agendar posts em múltiplas plataformas, analisar performance de conteúdo, comparar com concorrentes (análise de benchmarking), gerar relatórios automáticos e identificar os melhores horários de postagem para cada rede. Alternativa ao Later e Buffer com analytics mais avançado.",
    related: ["Agendamento", "Analytics", "Later", "Buffer"],
  },

  // ─── NEGÓCIO & ESTRATÉGIA ───────────────────────────────────────
  {
    id: "joint-venture",
    term: "Joint Venture (JV)",
    category: "Negócio & Estratégia",
    definition: "Parceria temporária entre dois negócios ou produtores para um lançamento ou projeto específico, com divisão acordada de receita. No mercado de infoprodutos, o JV mais comum é o lançamento externo: o parceiro promove o produto para sua lista em troca de 30-50% de comissão por venda. Diferente de uma afiliação padrão pela profundidade do envolvimento.",
    related: ["Lançamento Externo", "Afiliado", "Co-criação", "Comissão"],
  },
  {
    id: "posicionamento",
    term: "Posicionamento",
    category: "Negócio & Estratégia",
    definition: "Espaço que um produto ou marca ocupa na mente do consumidor em relação aos concorrentes. Define o ângulo único de comunicação: para quem, qual problema resolve especificamente, e por que é diferente das alternativas. O posicionamento correto é o que permite cobrar mais, converter mais fácil e construir autoridade mais rapidamente.",
    related: ["Nicho", "Proposta Única de Valor", "Mecanismo Único"],
  },
  {
    id: "proposta-unica-de-valor",
    term: "Proposta Única de Valor (PUV / UVP)",
    category: "Negócio & Estratégia",
    definition: "Declaração clara do que diferencia seu produto ou serviço, qual problema resolve e para quem. Uma boa PUV responde em uma frase: 'Para [quem], que [problema/desejo], nosso [produto] é [categoria] que [diferencial único] — diferente de [concorrentes] porque [prova]'.",
    example: "'Para produtores digitais que querem escalar de 6 para 7 dígitos sem contratar equipe, o NexOS é a única plataforma que executa um lançamento completo com o agente — do briefing ao carrinho aberto — em 7 dias'.",
    related: ["Posicionamento", "Mecanismo Único", "Copywriting"],
  },
  {
    id: "nicho",
    term: "Nicho",
    category: "Negócio & Estratégia",
    definition: "Segmento específico e bem delimitado de mercado. Nichos mais específicos têm menos competição, audiências mais engajadas e maior disposição a pagar — porque percebem que a solução foi feita exatamente para eles. A lógica do nicho é contraintuitiva: quanto mais específico, mais ampla a oportunidade de ser percebido como autoridade.",
    example: "Mercado: perda de peso. Nicho: perda de peso para mulheres acima de 40 anos com hipotireoidismo. Sub-nicho: protocolo alimentar para hipotireoidismo sem restrição de carboidratos.",
    related: ["Posicionamento", "Público-alvo", "Avatar"],
  },
  {
    id: "avatar",
    term: "Avatar (Persona/ICP)",
    category: "Negócio & Estratégia",
    definition: "Representação semi-fictícia do cliente ideal, construída com base em dados reais e pesquisa. Inclui: dados demográficos, comportamentos, dores específicas, desejos profundos, objeções à compra, linguagem que usa para descrever seus problemas. Quanto mais detalhado o avatar, mais precisa e eficaz é a comunicação.",
    related: ["Nicho", "Posicionamento", "Copywriting", "Público-alvo"],
  },
  {
    id: "funil-semente",
    term: "Análise SWOT",
    category: "Negócio & Estratégia",
    definition: "Framework estratégico que mapeia Forças (Strengths), Fraquezas (Weaknesses), Oportunidades (Opportunities) e Ameaças (Threats) de um negócio ou produto. As forças e fraquezas são fatores internos (controláveis). Oportunidades e ameaças são fatores externos (do mercado). Útil no planejamento de novos lançamentos e repositionamento.",
    related: ["Estratégia", "Posicionamento", "Análise Competitiva"],
  },
  {
    id: "lgpd",
    term: "LGPD (Lei Geral de Proteção de Dados)",
    category: "Negócio & Estratégia",
    definition: "Lei brasileira (nº 13.709/2018) que regula o tratamento de dados pessoais por empresas e pessoas físicas. Para marketing digital: exige consentimento explícito para captura de dados, política de privacidade clara, direito de exclusão de dados e segurança no armazenamento. Violações podem resultar em multas de até 2% do faturamento ou R$50 milhões.",
    related: ["Opt-in", "Política de Privacidade", "GDPR"],
  },
  {
    id: "white-label",
    term: "White Label",
    category: "Negócio & Estratégia",
    definition: "Modelo onde um produto ou serviço é produzido por uma empresa e revendido por outra sob a sua própria marca. Em SaaS, permite que agências ofereçam a plataforma para seus clientes com a marca da agência, sem revelar o fornecedor original. Comum em plataformas de automação, construtores de sites e ferramentas de email marketing.",
    related: ["B2B", "Licenciamento", "Agency"],
  },

  // ─── SEO & BUSCA ORGÂNICA ───────────────────────────────────────
  {
    id: "seo",
    term: "SEO (Search Engine Optimization)",
    category: "SEO & Busca Orgânica",
    definition: "Conjunto de técnicas para otimizar páginas e conteúdo para aparecer nas primeiras posições dos motores de busca (Google, YouTube) para termos relevantes, sem pagamento de anúncios. Dividido em: SEO On-page (conteúdo, títulos, velocidade, estrutura), SEO Off-page (backlinks, autoridade de domínio) e SEO Técnico (indexação, Core Web Vitals, sitemap).",
    related: ["Backlinks", "Autoridade de Domínio", "E-E-A-T", "Keywords"],
  },
  {
    id: "keyword",
    term: "Keyword (Palavra-chave)",
    category: "SEO & Busca Orgânica",
    definition: "Termos ou frases que os usuários digitam nos mecanismos de busca. Keywords de cauda longa (3+ palavras) têm menor volume mas maior intenção e menor competição. Keywords de cauda curta (1-2 palavras) têm alto volume mas alta competição. A estratégia ideal combina ambas — keywords curtas para autoridade e longas para tráfego qualificado.",
    related: ["SEO", "Intenção de Busca", "Volume de Busca"],
  },
  {
    id: "backlinks",
    term: "Backlinks (Links de Retorno)",
    category: "SEO & Busca Orgânica",
    definition: "Links de outros sites apontando para o seu. São o principal fator externo de ranqueamento no Google — cada backlink é interpretado como um 'voto de confiança'. A qualidade importa mais que a quantidade: um link de um site de alta autoridade vale muito mais que 100 links de sites irrelevantes. Links de sites relacionados ao seu nicho têm maior valor.",
    related: ["SEO", "Autoridade de Domínio", "E-E-A-T", "Link Building"],
  },
  {
    id: "intenção-de-busca",
    term: "Intenção de Busca",
    category: "SEO & Busca Orgânica",
    definition: "O objetivo por trás de uma pesquisa no Google. Os 3 tipos: Informacional (quer aprender — 'como fazer X'), Navegacional (quer encontrar um site específico — 'login Hotmart'), Transacional (quer comprar ou agir — 'comprar curso de marketing'). O conteúdo deve ser criado para o tipo de intenção da keyword-alvo.",
    related: ["Keyword", "SEO", "CRO", "Funil de Conteúdo"],
  },
  {
    id: "domain-authority",
    term: "Autoridade de Domínio (DA)",
    category: "SEO & Busca Orgânica",
    definition: "Métrica criada pela Moz (não pelo Google) para prever o potencial de ranqueamento de um domínio em buscas. Escala de 0-100. Calculada com base principalmente na quantidade e qualidade dos backlinks que o domínio recebe. Sites novos começam próximos de 1. Sites estabelecidos com muitos backlinks de qualidade chegam a 70-90+.",
    related: ["Backlinks", "SEO", "E-E-A-T"],
  },
  {
    id: "schema-markup",
    term: "Schema Markup",
    category: "SEO & Busca Orgânica",
    definition: "Código estruturado (em JSON-LD ou Microdata) adicionado ao HTML de uma página para ajudar o Google a entender o conteúdo e apresentá-lo de forma enriquecida nos resultados de busca (rich snippets). Para produtos digitais: Schema de Produto (mostra preço e avaliações), Schema de Evento (para webinars), Schema de FAQ (expande o resultado com perguntas/respostas).",
    related: ["SEO Técnico", "Rich Snippets", "Google Search"],
  },
  {
    id: "repurposing",
    term: "Repurposing (Reaproveitamento de Conteúdo)",
    category: "SEO & Busca Orgânica",
    definition: "Estratégia de transformar um conteúdo original em múltiplos formatos para distribuição em diferentes plataformas. Um vídeo longo do YouTube pode virar: Shorts, Reels, TikToks, podcast, artigo de blog, thread de LinkedIn, emails, carrosséis de Instagram. Maximiza o retorno de cada hora investida em produção de conteúdo.",
    related: ["Hub & Spoke", "Opus Clip", "Multi-plataforma"],
  },
];
