import type { Lang } from "@/lib/i18n";

const pt = {
  "gap.heading": "O problema não é falta de informação",
  "gap.title": "Você não precisa de mais um curso.",
  "gap.subtitle": "Precisa de uma operação que faça.",
  "gap.closing": "A distância entre “eu sei o que deveria fazer” e “minha campanha está vendendo” é execução.",
  "gap.offerLabel": "Condição de abertura",
  "gap.offerTitle": "Coloque a ideia em produção agora e pague parcelado no cartão.",
  "gap.offerBody": "A NexOS estrutura e executa a operação completa. Pagamento parcelado no cartão. Consulte as condições disponíveis no checkout.",
  "gap.cta.closed": "Turma encerrada",
  "gap.cta.open": "Quero colocar no ar",
  "gap.pain.course.marker": "01 / CURSOS",
  "gap.pain.course.title": "Você aprendeu a estratégia. A campanha nunca saiu do rascunho.",
  "gap.pain.course.body": "Módulos assistidos, anotações prontas, frameworks salvos. Mas ainda faltam a oferta, a copy, os criativos, a página, os anúncios e alguém capaz de fazer tudo conversar.",
  "gap.pain.traffic.marker": "02 / TRÁFEGO",
  "gap.pain.traffic.title": "Você sabe que precisa anunciar. Só não pode pagar para aprender errando.",
  "gap.pain.traffic.body": "Configurar conta, pixel, público, criativo, verba e remarketing ao mesmo tempo transforma cada clique em risco. O medo de queimar dinheiro paralisa antes do primeiro teste.",
  "gap.pain.agency.marker": "03 / AGÊNCIA",
  "gap.pain.agency.title": "Uma agência resolveria. Se coubesse no caixa de quem ainda nem lançou.",
  "gap.pain.agency.body": "Estrategista, copywriter, designer, editor, gestor de tráfego e CRM separados custam antes de gerar a primeira venda — e ainda deixam você responsável por coordenar todos eles.",
  "gap.pain.online.marker": "04 / RENDA ONLINE",
  "gap.pain.online.title": "Você enxerga pessoas monetizando. Não enxerga como replicar a máquina.",
  "gap.pain.online.body": "Curso, comunidade, canal, consultoria, infoproduto: o modelo parece simples quando está pronto. Por trás dele existe uma operação inteira que ninguém mostra funcionando em conjunto.",
  "work.heading": "A solução não é outra aula",
  "work.title": "Você chega com a ideia. A NexOS constrói e opera o que faltava.",
  "work.intro": "Não entregamos um plano para você montar sozinho. Entregamos a pesquisa, a oferta, os ativos, a infraestrutura, a distribuição e o acompanhamento funcionando como uma única operação.",
  "work.offer.title": "Inteligência & Oferta",
  "work.offer.body": "Transforma sua ideia em uma oferta vendável: encontra a dor, estuda o mercado, mapeia concorrentes e estrutura promessa, preço, bônus, objeções e ganchos para a campanha.",
  "work.video.title": "Produção de Vídeo",
  "work.video.body": "Você não precisa virar editor nem montar um estúdio. A NexOS roteiriza, produz, corta e renderiza vídeos usando gravações reais ou produção autônoma com voz e avatar.",
  "work.landing.title": "Landings & Criativos",
  "work.landing.body": "Não entrega um wireframe. Registra o domínio, escreve a copy, desenha a página, conecta a captura, produz os criativos e coloca tudo no ar.",
  "work.paid.title": "Tráfego Pago Multi-Canal",
  "work.paid.body": "Tira a campanha do gerenciador e coloca em circulação: cria públicos, sobe anúncios, testa criativos, acompanha verba e pausa o que não responde — dentro das suas regras.",
  "work.organic.title": "Distribuição Orgânica & Grupos",
  "work.organic.body": "Converte uma ideia em presença contínua: publica, aquece, responde e modera canais e comunidades sem deixar todo o calendário depender da sua energia.",
  "work.sales.title": "Vendas & Retenção",
  "work.sales.body": "A venda não termina no checkout. Acompanha leads no CRM, recupera abandonos, recebe compradores, conduz onboarding, trabalha retenção e ativa indicações.",
  "architecture.heading": "A Quebra de Silos",
  "architecture.title": "Seu projeto não travou por falta de potencial. Travou porque você virou o operador de cinco profissões.",
  "architecture.p1": "Você deveria decidir o que quer construir. Em vez disso, tenta aprender copy, design, edição, tráfego, automação e vendas ao mesmo tempo.",
  "architecture.p2": "O custo real não está só nas ferramentas. Está nos meses sem publicar, no anúncio que nunca foi testado e na oferta que continua dentro de um documento.",
  "architecture.p3.before": "Com a NexOS, o cérebro é unificado e ",
  "architecture.p3.emphasis": "autônomo",
  "architecture.p3.after": ".",
  "architecture.p4": "A inteligência orienta o texto. O estrategista instrui a renderização, que sobe as páginas online e entrega os vídeos ao tráfego. Toda a operação consome a mesma matriz — executando a campanha inteira sem você precisar intervir a cada etapa.",
  "architecture.hint": "[ Selecione um nó operacional ao lado para inspecionar ]",
  "architecture.label": "Arquitetura Operacional",
  "architecture.observe": "Observa",
  "architecture.decide": "Decide",
  "architecture.create": "Cria",
  "architecture.execute": "Executa",
  "architecture.measure": "Mede",
  "architecture.step.niche.title": "Pesquisa de Nicho e Análise de Concorrentes",
  "architecture.step.niche.status": "Concluído",
  "architecture.step.niche.observe": "Avaliações de concorrentes, debates em redes sociais, tendências de busca e buracos em produtos similares.",
  "architecture.step.niche.decide": "A dor exata não resolvida e o perfil do comprador mais propenso à conversão imediata.",
  "architecture.step.niche.create": "Matrizes de objeções, relatórios de inteligência de mercado e mapas de empatia operacionais.",
  "architecture.step.niche.execute": "Consolida as diretrizes no Dossiê interno, proibindo que agentes assumam premissas genéricas.",
  "architecture.step.niche.measure": "Densidade da demanda, sofisticação do mercado e viabilidade.",
  "architecture.step.offer.title": "Definição de Oferta e Ganchos (War Room)",
  "architecture.step.offer.status": "Concluído",
  "architecture.step.offer.observe": "O Dossiê validado cruzado com o seu histórico real de campanhas e custos de aquisição passados.",
  "architecture.step.offer.decide": "A promessa central irrecusável, bônus para elevar ticket, ancoragem de preço e ângulos de vendas (ganchos).",
  "architecture.step.offer.create": "Estruturas argumentativas completas para VSLs, páginas de vendas e anúncios.",
  "architecture.step.offer.execute": "Deixa a arquitetura de persuasão pronta para ser materializada nos formatos finais.",
  "architecture.step.offer.measure": "Alinhamento lógico com objeções e coerência com a política da marca.",
  "architecture.step.creative.title": "Copy, Design e Renderização Audiovisual",
  "architecture.step.creative.status": "Ativo",
  "architecture.step.creative.observe": "Os ganchos definidos, o tom de voz imutável do Dossiê e o pacote visual da sua empresa.",
  "architecture.step.creative.decide": "Quais formatos (estático, reel vertical, página longa) entregam a oferta com mais eficácia.",
  "architecture.step.creative.create": "Copy impecável, interfaces otimizadas, e vídeos 100% renderizados na nossa GPU (via vozes clonadas ou avatares).",
  "architecture.step.creative.execute": "Registra os domínios, aponta servidores DNS e coloca a landing page no ar sem fricção humana.",
  "architecture.step.creative.measure": "Velocidade da página (LCP), coesão visual e retenção estimada.",
  "architecture.step.distribution.title": "Distribuição Orgânica e Grupos",
  "architecture.step.distribution.status": "Ativo",
  "architecture.step.distribution.observe": "Picos de engajamento do seu nicho, algoritmos de distribuição e interações pendentes das comunidades.",
  "architecture.step.distribution.decide": "A ordem de publicação, as respostas certas em direct e como moderar o aquecimento de um grupo.",
  "architecture.step.distribution.create": "Legendas precisas, interações de moderação em WhatsApp/Telegram e alertas automáticos.",
  "architecture.step.distribution.execute": "Executa os posts em todas as redes orgânicas vinculadas nos horários estipulados.",
  "architecture.step.distribution.measure": "Crescimento de base, taxa de respostas orgânicas e retenção nos grupos de lançamento.",
  "architecture.step.ads.title": "Operação de Tráfego Pago",
  "architecture.step.ads.status": "Ativo",
  "architecture.step.ads.observe": "Os criativos recém-produzidos, a landing ativa, os públicos do pixel e as regras de orçamento diário.",
  "architecture.step.ads.decide": "Onde testar a verba primeiro (CBO/ABO), pausas de criativos fadigados e realocações de lances.",
  "architecture.step.ads.create": "Estruturas completas de campanha nas plataformas de anúncio mais rentáveis para a oferta.",
  "architecture.step.ads.execute": "Ativa publicações patrocinadas conectadas ao seu cartão de crédito nas redes de pesquisa e social.",
  "architecture.step.ads.measure": "CPA real, ROAS, fadiga de criativos e CTR cruzado (direto nos dashboards oficiais).",
  "architecture.step.crm.title": "Vendas, Retenção e Onboarding",
  "architecture.step.crm.status": "Ativo",
  "architecture.step.crm.observe": "Leads quentes, eventos de abandono de carrinho, compras confirmadas e conversas interrompidas.",
  "architecture.step.crm.decide": "A hora exata de invocar recuperação ativa, quebrar a objeção que falta ou dar boas-vindas VIP.",
  "architecture.step.crm.create": "Fluxos invisíveis de e-mail marketing, disparos via WhatsApp e alertas de alta prioridade.",
  "architecture.step.crm.execute": "Envia comunicações 1-a-1 diretamente para a base, sustentando o LTV do cliente a longo prazo.",
  "architecture.step.crm.measure": "Taxa de recuperação, churn, engajamento com onboarding e vendas cruzadas (upsell).",
  "governance.heading": "Governança Integrada",
  "governance.authorization.title": "Autorização Estrita",
  "governance.authorization.body": "As ações externas (publicar posts, subir campanhas de tráfego, enviar e-mails) só acontecem após sua aprovação ou dentro de limites pré-estabelecidos por você.",
  "governance.workspaces.title": "Workspaces Isolados",
  "governance.workspaces.body": "Perfeito para separar múltiplos produtos e serviços da mesma empresa, ou isolar clientes de agências. Os dados, a inteligência e as estratégias nunca se misturam.",
  "governance.metrics.title": "Métricas Reais. Fim.",
  "governance.metrics.body": "O sistema baseia-se em dados empíricos puxados diretamente de canais reais de tráfego e do seu CRM. Nenhuma IA inventando números de conversão para o painel parecer completo.",
  "proof.heading": "Lógica de Execução e Coerência",
  "proof.title": "Como garantimos que a autonomia não crie um frankenstein de IA genérica.",
  "proof.brain.title": "1. O Cérebro Único (Dossiê)",
  "proof.brain.body": "Modelos rasos cometem erros de lógica e causam contradições bizarras. A NexOS resolve isso criando um Dossiê mestre imutável para a campanha. O mesmo arquivo de regras bloqueia o roteirista de vídeo, baliza o copywriter e dita o tom dos anúncios — evitando saídas genéricas.",
  "proof.safety.title": "2. Autonomia com Trava de Segurança",
  "proof.safety.body": "Você pode automatizar a publicação a 100% ou exigir revisão. A NexOS desenha a página, edita os vídeos, formata os anúncios e prepara as postagens. Eles vão ao ar e o domínio é registrado assim que você dá o seu \"Aprovado\" — sem exigir o trabalho braçal de montar a peça na ferramenta.",
  "proof.decisions.title": "3. Fim das Decisões Ruins",
  "proof.decisions.body": "IAs tradicionais falham por não verem o quadro inteiro. Quando a agência autônoma relata que um criativo saturou e decide pausá-lo nas redes, ela cruzou o CTR de cliques reais com as conversões no seu CRM. Nenhuma decisão superficial é tomada sem cruzamento de dados empíricos.",
  "proof.memory.title": "4. Memória Institucional Ativa",
  "proof.memory.body": "Repetições maçantes acontecem quando a IA perde o contexto. A NexOS armazena vencedores, perdedores e lições aprendidas. O erro e a objeção que não funcionaram no mês passado já estão internalizados como regras de restrição permanente para a campanha atual.",
  "scarcity.title": "Apenas 100 Operações no Lançamento.",
  "scarcity.body": "Se o que impediu você até agora foi o custo e a complexidade de montar uma agência inteira, esta abertura foi desenhada para remover esse bloqueio: execução ponta a ponta e pagamento parcelado no cartão. Você confere as opções e escolhe a melhor condição no checkout. O acesso inicial é restrito. Não há exceções.",
  "scarcity.cta.closed": "Turma Encerrada",
  "scarcity.cta.open": "Reservar Minha Vaga Agora",
  "scarcity.status.closed": "As vagas foram preenchidas.",
  "scarcity.status.open": "A ordem de reserva define a prioridade de ativação.",
  "scarcity.credibility": "Esta landing page foi criada e colocada no ar pelos agentes da NexOS.",
  "scarcity.community": "Entre na lista agora e acesse nosso grupo para ver a operação acontecendo nos bastidores.",
  "footer.terms": "Termos de Uso",
  "footer.privacy": "Privacidade",
  "footer.deletion": "Exclusão de Dados",
  "footer.signature": "Operação Centralizada.",
  "glp.heading": "O Método GLP22",
  "glp.title.before": "A Engenharia de uma",
  "glp.title.accent": "Operação Autônoma.",
  "glp.intro1": "Não é um pacote de ferramentas. É o fluxo contínuo de 22 capacidades interdependentes — da ideia embrionária à escala de vendas.",
  "glp.intro2": "Cada etapa alimenta a próxima. O estrategista instrui a copy, a copy orienta o design, o design alimenta o tráfego. Tudo orquestrado por uma inteligência central, sem gaps de execução.",
  "glp.phase.strategy.label": "Fase 01",
  "glp.phase.strategy.name": "Estratégia e Fundações",
  "glp.phase.strategy.title": "Onde o achismo termina e a inteligência de mercado começa.",
  "glp.phase.strategy.item.01.title": "Imersão e intake",
  "glp.phase.strategy.item.01.desc": "Coleta profunda da sua visão, objetivos e restrições para balizar a operação sem recorrer a premissas genéricas.",
  "glp.phase.strategy.item.02.title": "Inteligência e análise de mercado",
  "glp.phase.strategy.item.02.desc": "Mapeamento ativo da concorrência e do ambiente competitivo para encontrar brechas de atenção, demandas ocultas e padrões de mercado.",
  "glp.phase.strategy.item.03.title": "Avatar, segmentação e jornada",
  "glp.phase.strategy.item.03.desc": "Definição clara do cliente ideal e desenho do caminho exato que ele percorre do primeiro contato até o momento da decisão.",
  "glp.phase.strategy.item.04.title": "Posicionamento, mecanismo e narrativa",
  "glp.phase.strategy.item.04.desc": "Construção de uma tese única e argumentação central que diferenciem sua mensagem da comoditização do nicho.",
  "glp.phase.strategy.item.05.title": "Engenharia da oferta",
  "glp.phase.strategy.item.05.desc": "Estruturação de preço, ancoragem, quebra de objeções, garantias e bônus para criar uma proposta comercial robusta.",
  "glp.phase.strategy.item.06.title": "Arquitetura estratégica do lançamento",
  "glp.phase.strategy.item.06.desc": "Desenho do formato e do modelo de vendas mais adequados, estipulando cronograma, eventos e pontos de contato da campanha.",
  "glp.phase.strategy.item.07.title": "Master Plan",
  "glp.phase.strategy.item.07.desc": "Consolidação de todas as diretrizes em um documento mestre, alinhando a execução autônoma em torno do mesmo objetivo.",
  "glp.phase.creation.label": "Fase 02",
  "glp.phase.creation.name": "Criação e Ativos Visuais",
  "glp.phase.creation.title": "Da arquitetura conceitual para interfaces e roteiros focados em conversão.",
  "glp.phase.creation.item.08.title": "Construção do funil",
  "glp.phase.creation.item.08.desc": "Desenho prático da estrutura de aquisição e qualificação, conectando os passos da jornada de compra de forma fluida.",
  "glp.phase.creation.item.09.title": "Copy",
  "glp.phase.creation.item.09.desc": "Redação persuasiva de cartas de vendas, anúncios e scripts visuais, orquestrada para respeitar o tom de voz definido no Master Plan.",
  "glp.phase.creation.item.10.title": "Direção criativa e produção visual",
  "glp.phase.creation.item.10.desc": "Desenvolvimento da identidade visual da campanha e desdobramento em peças gráficas e banners padronizados para todos os canais.",
  "glp.phase.creation.item.11.title": "Direção e produção de vídeos",
  "glp.phase.creation.item.11.desc": "Roteirização e renderização dinâmica de VSLs, anúncios e conteúdos audiovisuais voltados a reter a atenção nos segundos cruciais.",
  "glp.phase.creation.item.12.title": "Páginas e ativos digitais",
  "glp.phase.creation.item.12.desc": "Implementação de landing pages desenhadas para conversão e performance de carregamento, prontas para receber tráfego.",
  "glp.phase.infrastructure.label": "Fase 03",
  "glp.phase.infrastructure.name": "Infraestrutura e Engajamento",
  "glp.phase.infrastructure.title": "Sistemas técnicos, gestão de audiência e comunicação orgânica.",
  "glp.phase.infrastructure.item.13.title": "Infraestrutura, tracking e integrações",
  "glp.phase.infrastructure.item.13.desc": "Configuração técnica de pixels, tags e fluxos de dados, além de apoio em domínios e hospedagem (serviços faturados diretamente pelos fornecedores escolhidos).",
  "glp.phase.infrastructure.item.14.title": "CRM, gestão de leads, grupos e comunidades",
  "glp.phase.infrastructure.item.14.desc": "Estruturação das bases de contatos e organização de ambientes de aquecimento para centralizar a comunicação com os interessados.",
  "glp.phase.infrastructure.item.15.title": "Presença Digital e audiência",
  "glp.phase.infrastructure.item.15.desc": "Programação e controle de postagens para manter consistência nos perfis sociais, aproveitando os algoritmos de descoberta.",
  "glp.phase.infrastructure.item.16.title": "E-mail, mensagens e nutrição",
  "glp.phase.infrastructure.item.16.desc": "Desenvolvimento de sequências de comunicação ativa e fluxos automatizados para elevar o nível de consciência dos leads.",
  "glp.phase.sales.label": "Fase 04",
  "glp.phase.sales.name": "Aquisição e Vendas",
  "glp.phase.sales.title": "Geração de tráfego, orquestração e recuperação de receita.",
  "glp.phase.sales.item.17.title": "Mídia paga",
  "glp.phase.sales.item.17.desc": "Planejamento e gestão de campanhas publicitárias com distribuição de verba em criativos e públicos que apresentam o melhor custo por aquisição.",
  "glp.phase.sales.item.18.title": "Execução coordenada do lançamento",
  "glp.phase.sales.item.18.desc": "Sincronização de todos os canais, e-mails, grupos e anúncios nos dias-chave da campanha para um fluxo de aberturas de carrinho alinhado.",
  "glp.phase.sales.item.19.title": "Atendimento, vendas e conversão",
  "glp.phase.sales.item.19.desc": "Atuação voltada para recuperação de boletos/Pix, carrinhos abandonados e quebra de objeções de última hora, maximizando a receita aprovada.",
  "glp.phase.continuity.label": "Fase 05",
  "glp.phase.continuity.name": "Dados e Continuidade",
  "glp.phase.continuity.title": "Leitura de métricas, aprendizado institucional e próximos passos.",
  "glp.phase.continuity.item.20.title": "Monitoramento e otimização",
  "glp.phase.continuity.item.20.desc": "Acompanhamento e leitura contínua de métricas reais para possibilitar ajustes finos e proteção de orçamento ao longo da campanha.",
  "glp.phase.continuity.item.21.title": "Pós-lançamento e aprendizado",
  "glp.phase.continuity.item.21.desc": "Consolidação de dados de performance em inteligência institucional, registrando o que converteu melhor e mapeando novas objeções.",
  "glp.phase.continuity.item.22.title": "Continuidade, relançamento e perpétuo",
  "glp.phase.continuity.item.22.desc": "Transformação da inteligência acumulada em novas esteiras de vendas e adaptação do produto para campanhas sucessivas ou recorrência.",
} as const;

export type HomeTextKey = keyof typeof pt;

const en: Record<HomeTextKey, string> = {
  "gap.heading": "The problem isn't a lack of information",
  "gap.title": "You don't need another course.",
  "gap.subtitle": "You need an operation that gets it done.",
  "gap.closing": "The distance between “I know what I should do” and “my campaign is selling” is execution.",
  "gap.offerLabel": "Launch offer",
  "gap.offerTitle": "Put your idea into production now and pay in installments by card.",
  "gap.offerBody": "NexOS builds and runs the complete operation. Pay in installments by card. Check the available terms at checkout.",
  "gap.cta.closed": "Cohort closed",
  "gap.cta.open": "Let's launch it",
  "gap.pain.course.marker": "01 / COURSES",
  "gap.pain.course.title": "You learned the strategy. The campaign never left the draft.",
  "gap.pain.course.body": "You've watched the modules, taken notes, and saved the frameworks. But the offer, copy, creative, landing page, ads, and someone to bring it all together are still missing.",
  "gap.pain.traffic.marker": "02 / PAID TRAFFIC",
  "gap.pain.traffic.title": "You know you need to advertise. You just can't afford to learn by making mistakes.",
  "gap.pain.traffic.body": "Setting up the account, pixel, audience, creative, budget, and retargeting all at once turns every click into a risk. Fear of wasting money can stop you before the first test.",
  "gap.pain.agency.marker": "03 / AGENCY",
  "gap.pain.agency.title": "An agency could solve it—if a pre-launch business could afford one.",
  "gap.pain.agency.body": "A strategist, copywriter, designer, editor, media buyer, and CRM specialist all cost money before the first sale—and you'd still have to coordinate them.",
  "gap.pain.online.marker": "04 / ONLINE INCOME",
  "gap.pain.online.title": "You see people monetizing. You don't see how to replicate the machine.",
  "gap.pain.online.body": "Courses, communities, channels, consulting, digital products: the model looks simple once it's finished. Behind it is a whole operation that no one shows working together.",
  "work.heading": "The solution isn't another lesson",
  "work.title": "Bring the idea. NexOS builds and runs what was missing.",
  "work.intro": "We don't hand you a plan to assemble on your own. We deliver research, the offer, assets, infrastructure, distribution, and monitoring working as one operation.",
  "work.offer.title": "Market Intelligence & Offer",
  "work.offer.body": "Turns your idea into an offer people can buy: identifies the pain point, researches the market, maps competitors, and shapes the promise, price, bonuses, objections, and campaign hooks.",
  "work.video.title": "Video Production",
  "work.video.body": "You don't have to become an editor or build a studio. NexOS scripts, produces, edits, and renders videos using real footage or autonomous production with voice and avatars.",
  "work.landing.title": "Landing Pages & Creative",
  "work.landing.body": "We don't hand over a wireframe. We register the domain, write the copy, design the page, connect lead capture, produce the creative, and launch it.",
  "work.paid.title": "Multichannel Paid Traffic",
  "work.paid.body": "Takes the campaign out of the ad manager and into the market: creates audiences, launches ads, tests creative, monitors spend, and pauses what isn't working—within your rules.",
  "work.organic.title": "Organic Distribution & Communities",
  "work.organic.body": "Turns an idea into a consistent presence: publishing, warming up, responding, and moderating channels and communities without making the calendar depend on your energy.",
  "work.sales.title": "Sales & Retention",
  "work.sales.body": "The sale doesn't end at checkout. NexOS follows up with leads in the CRM, recovers abandoned checkouts, welcomes buyers, guides onboarding, supports retention, and encourages referrals.",
  "architecture.heading": "Breaking Down Silos",
  "architecture.title": "Your project didn't stall for lack of potential. It stalled because you became the operator of five different jobs.",
  "architecture.p1": "You should be deciding what you want to build. Instead, you're trying to learn copywriting, design, editing, paid traffic, automation, and sales all at once.",
  "architecture.p2": "The real cost isn't just the tools. It's the months without publishing, the ad that was never tested, and the offer still sitting in a document.",
  "architecture.p3.before": "With NexOS, the brain is unified and ",
  "architecture.p3.emphasis": "autonomous",
  "architecture.p3.after": ".",
  "architecture.p4": "Intelligence guides the copy. The strategist directs production, publishes the pages, and sends the videos into paid traffic. The whole operation uses the same playbook—running the entire campaign without needing you at every step.",
  "architecture.hint": "[ Select an operational node to inspect ]",
  "architecture.label": "Operational Architecture",
  "architecture.observe": "Observes",
  "architecture.decide": "Decides",
  "architecture.create": "Creates",
  "architecture.execute": "Executes",
  "architecture.measure": "Measures",
  "architecture.step.niche.title": "Niche Research & Competitor Analysis",
  "architecture.step.niche.status": "Complete",
  "architecture.step.niche.observe": "Competitor reviews, social media discussions, search trends, and gaps in similar products.",
  "architecture.step.niche.decide": "The precise unmet need and the buyer profile most likely to convert now.",
  "architecture.step.niche.create": "Objection matrices, market intelligence reports, and practical empathy maps.",
  "architecture.step.niche.execute": "Consolidates the guidelines in the internal dossier and prevents agents from relying on generic assumptions.",
  "architecture.step.niche.measure": "Demand density, market sophistication, and feasibility.",
  "architecture.step.offer.title": "Offer & Hook Development (War Room)",
  "architecture.step.offer.status": "Complete",
  "architecture.step.offer.observe": "The validated dossier, cross-checked against your campaign history and actual acquisition costs.",
  "architecture.step.offer.decide": "The compelling core promise, bonuses that increase order value, price anchoring, and sales angles (hooks).",
  "architecture.step.offer.create": "Complete argument structures for VSLs, sales pages, and ads.",
  "architecture.step.offer.execute": "Prepares the persuasion architecture to be produced in the final formats.",
  "architecture.step.offer.measure": "Logical alignment with objections and consistency with brand policy.",
  "architecture.step.creative.title": "Copy, Design & Video Rendering",
  "architecture.step.creative.status": "Active",
  "architecture.step.creative.observe": "Defined hooks, the dossier's consistent voice, and your company's visual assets.",
  "architecture.step.creative.decide": "Which formats—static, vertical Reel, or long-form page—present the offer most effectively.",
  "architecture.step.creative.create": "Polished copy, optimized interfaces, and videos rendered on our GPUs using cloned voices or avatars.",
  "architecture.step.creative.execute": "Registers domains, configures DNS servers, and launches the landing page without manual friction.",
  "architecture.step.creative.measure": "Page speed (LCP), visual cohesion, and estimated retention.",
  "architecture.step.distribution.title": "Organic Distribution & Communities",
  "architecture.step.distribution.status": "Active",
  "architecture.step.distribution.observe": "Engagement peaks in your niche, distribution algorithms, and pending community interactions.",
  "architecture.step.distribution.decide": "The publishing order, the right direct-message responses, and how to moderate a group's warm-up.",
  "architecture.step.distribution.create": "Precise captions, WhatsApp/Telegram moderation interactions, and automatic alerts.",
  "architecture.step.distribution.execute": "Publishes across all connected organic networks at the scheduled times.",
  "architecture.step.distribution.measure": "Audience growth, organic response rates, and retention in launch groups.",
  "architecture.step.ads.title": "Paid Traffic Operations",
  "architecture.step.ads.status": "Active",
  "architecture.step.ads.observe": "Newly produced creative, the active landing page, pixel audiences, and daily budget rules.",
  "architecture.step.ads.decide": "Where to test the budget first (CBO/ABO), when to pause fatigued creative, and how to reallocate bids.",
  "architecture.step.ads.create": "Complete campaign structures on the ad platforms best suited to the offer.",
  "architecture.step.ads.execute": "Activates sponsored posts connected to your credit card across search and social networks.",
  "architecture.step.ads.measure": "Actual CPA, ROAS, creative fatigue, and cross-channel CTR in the official dashboards.",
  "architecture.step.crm.title": "Sales, Retention & Onboarding",
  "architecture.step.crm.status": "Active",
  "architecture.step.crm.observe": "Warm leads, abandoned checkouts, confirmed purchases, and interrupted conversations.",
  "architecture.step.crm.decide": "The right moment to follow up, address the remaining objection, or send a VIP welcome.",
  "architecture.step.crm.create": "Automated email flows, WhatsApp messages, and high-priority alerts.",
  "architecture.step.crm.execute": "Sends one-to-one communications to your audience, supporting customer lifetime value over time.",
  "architecture.step.crm.measure": "Recovery rate, churn, onboarding engagement, and cross-sell revenue.",
  "governance.heading": "Integrated Governance",
  "governance.authorization.title": "Strict Authorization",
  "governance.authorization.body": "External actions—publishing posts, launching ad campaigns, and sending emails—only happen after your approval or within limits you set.",
  "governance.workspaces.title": "Isolated Workspaces",
  "governance.workspaces.body": "Separate products and services within one company or keep agency clients apart. Data, intelligence, and strategies never mix.",
  "governance.metrics.title": "Real Metrics. Period.",
  "governance.metrics.body": "The system is based on empirical data pulled directly from real traffic channels and your CRM. No AI making up conversion numbers to make a dashboard look complete.",
  "proof.heading": "Execution Logic & Consistency",
  "proof.title": "How we keep autonomy from creating a Frankenstein of generic AI.",
  "proof.brain.title": "1. One Brain (The Dossier)",
  "proof.brain.body": "Shallow models make logical errors and create strange contradictions. NexOS solves this with an immutable master dossier for each campaign. The same rule file guides the video scriptwriter, the copywriter, and the tone of the ads—preventing generic output.",
  "proof.safety.title": "2. Autonomy with a Safety Lock",
  "proof.safety.body": "Automate publishing fully or require review. NexOS designs the page, edits videos, formats ads, and prepares posts. They go live and the domain is registered once you approve—without making you do the manual work of assembling everything in a tool.",
  "proof.decisions.title": "3. Fewer Bad Decisions",
  "proof.decisions.body": "Traditional AI fails when it can't see the whole picture. When the autonomous agency reports that a creative is saturated and pauses it across networks, it has cross-checked real click-through rates with conversions in your CRM. No superficial decision is made without empirical data.",
  "proof.memory.title": "4. Active Institutional Memory",
  "proof.memory.body": "Repetitive work happens when AI loses context. NexOS stores wins, losses, and lessons learned. Last month's mistakes and ineffective objections become permanent guardrails for the current campaign.",
  "scarcity.title": "Only 100 Launch Spots.",
  "scarcity.body": "If the cost and complexity of building a full agency have held you back, this launch is designed to remove that barrier: end-to-end execution with installment payments by card. Review your options and choose the best terms at checkout. Initial access is limited. No exceptions.",
  "scarcity.cta.closed": "Cohort Closed",
  "scarcity.cta.open": "Reserve My Spot Now",
  "scarcity.status.closed": "All spots have been filled.",
  "scarcity.status.open": "Reservation order determines activation priority.",
  "scarcity.credibility": "This landing page was built and launched by NexOS agents.",
  "scarcity.community": "Join the list and access our group to see the operation behind the scenes.",
  "footer.terms": "Terms of Use",
  "footer.privacy": "Privacy",
  "footer.deletion": "Data Deletion",
  "footer.signature": "Centralized Operations.",
  "glp.heading": "The GLP22 Method",
  "glp.title.before": "The Engineering of an",
  "glp.title.accent": "Autonomous Operation.",
  "glp.intro1": "This isn't a bundle of tools. It's a continuous flow of 22 interdependent capabilities—from the first idea to scaling sales.",
  "glp.intro2": "Each step feeds the next. The strategist guides the copy, the copy guides design, and design feeds paid traffic. One central intelligence orchestrates everything with no execution gaps.",
  "glp.phase.strategy.label": "Phase 01",
  "glp.phase.strategy.name": "Strategy & Foundations",
  "glp.phase.strategy.title": "Where guesswork ends and market intelligence begins.",
  "glp.phase.strategy.item.01.title": "Discovery & intake",
  "glp.phase.strategy.item.01.desc": "A deep review of your vision, goals, and constraints to guide operations without relying on generic assumptions.",
  "glp.phase.strategy.item.02.title": "Market intelligence & analysis",
  "glp.phase.strategy.item.02.desc": "Active mapping of competitors and the competitive landscape to find attention gaps, unmet demand, and market patterns.",
  "glp.phase.strategy.item.03.title": "Audience avatar, segmentation & journey",
  "glp.phase.strategy.item.03.desc": "A clear definition of the ideal customer and the exact path from first contact to the buying decision.",
  "glp.phase.strategy.item.04.title": "Positioning, mechanism & narrative",
  "glp.phase.strategy.item.04.desc": "A distinctive thesis and core argument that set your message apart from the niche's commodity offers.",
  "glp.phase.strategy.item.05.title": "Offer engineering",
  "glp.phase.strategy.item.05.desc": "Pricing, anchoring, objection handling, guarantees, and bonuses shaped into a strong commercial offer.",
  "glp.phase.strategy.item.06.title": "Strategic launch architecture",
  "glp.phase.strategy.item.06.desc": "The right format and sales model, with the campaign schedule, events, and touchpoints defined.",
  "glp.phase.strategy.item.07.title": "Master Plan",
  "glp.phase.strategy.item.07.desc": "All guidelines consolidated into one master document to align autonomous execution around the same goal.",
  "glp.phase.creation.label": "Phase 02",
  "glp.phase.creation.name": "Creation & Visual Assets",
  "glp.phase.creation.title": "From conceptual architecture to conversion-focused interfaces and scripts.",
  "glp.phase.creation.item.08.title": "Funnel building",
  "glp.phase.creation.item.08.desc": "A practical acquisition and qualification structure that connects the steps in the buying journey.",
  "glp.phase.creation.item.09.title": "Copywriting",
  "glp.phase.creation.item.09.desc": "Persuasive sales letters, ads, and visual scripts, coordinated to match the voice defined in the Master Plan.",
  "glp.phase.creation.item.10.title": "Creative direction & visual production",
  "glp.phase.creation.item.10.desc": "Development of the campaign's visual identity and adaptation into consistent graphics and banners for every channel.",
  "glp.phase.creation.item.11.title": "Video direction & production",
  "glp.phase.creation.item.11.desc": "Dynamic scripting and rendering of VSLs, ads, and video content built to hold attention in the crucial seconds.",
  "glp.phase.creation.item.12.title": "Pages & digital assets",
  "glp.phase.creation.item.12.desc": "Conversion-focused landing pages optimized for loading performance and ready for traffic.",
  "glp.phase.infrastructure.label": "Phase 03",
  "glp.phase.infrastructure.name": "Infrastructure & Engagement",
  "glp.phase.infrastructure.title": "Technical systems, audience management, and organic communication.",
  "glp.phase.infrastructure.item.13.title": "Infrastructure, tracking & integrations",
  "glp.phase.infrastructure.item.13.desc": "Technical setup for pixels, tags, and data flows, with support for domains and hosting (billed directly by the providers you choose).",
  "glp.phase.infrastructure.item.14.title": "CRM, lead management, groups & communities",
  "glp.phase.infrastructure.item.14.desc": "Contact databases and warm-up spaces organized to centralize communication with interested prospects.",
  "glp.phase.infrastructure.item.15.title": "Digital presence & audience",
  "glp.phase.infrastructure.item.15.desc": "Posts scheduled and managed to keep social profiles consistent and make the most of discovery algorithms.",
  "glp.phase.infrastructure.item.16.title": "Email, messaging & nurturing",
  "glp.phase.infrastructure.item.16.desc": "Active communication sequences and automated flows that increase lead awareness.",
  "glp.phase.sales.label": "Phase 04",
  "glp.phase.sales.name": "Acquisition & Sales",
  "glp.phase.sales.title": "Traffic generation, orchestration, and revenue recovery.",
  "glp.phase.sales.item.17.title": "Paid media",
  "glp.phase.sales.item.17.desc": "Advertising campaigns planned and managed, allocating budget to the creative and audiences with the best acquisition costs.",
  "glp.phase.sales.item.18.title": "Coordinated launch execution",
  "glp.phase.sales.item.18.desc": "Channels, emails, groups, and ads synchronized on key campaign days for aligned cart openings.",
  "glp.phase.sales.item.19.title": "Support, sales & conversion",
  "glp.phase.sales.item.19.desc": "Recovery of payment slips/Pix and abandoned checkouts, plus last-minute objection handling to maximize approved revenue.",
  "glp.phase.continuity.label": "Phase 05",
  "glp.phase.continuity.name": "Data & Continuity",
  "glp.phase.continuity.title": "Metric analysis, institutional learning, and next steps.",
  "glp.phase.continuity.item.20.title": "Monitoring & optimization",
  "glp.phase.continuity.item.20.desc": "Continuous review of real metrics to fine-tune the campaign and protect the budget.",
  "glp.phase.continuity.item.21.title": "Post-launch review & learning",
  "glp.phase.continuity.item.21.desc": "Performance data consolidated into institutional intelligence, recording what converted best and identifying new objections.",
  "glp.phase.continuity.item.22.title": "Continuity, relaunch & evergreen",
  "glp.phase.continuity.item.22.desc": "Accumulated intelligence turned into new sales funnels and product adaptations for future or recurring campaigns.",
};

const es: Record<HomeTextKey, string> = {
  "gap.heading": "El problema no es la falta de información",
  "gap.title": "No necesitas otro curso.",
  "gap.subtitle": "Necesitas una operación que lo haga realidad.",
  "gap.closing": "La distancia entre «sé lo que debería hacer» y «mi campaña está vendiendo» es la ejecución.",
  "gap.offerLabel": "Condiciones de apertura",
  "gap.offerTitle": "Pon tu idea en marcha ahora y paga en cuotas con tarjeta.",
  "gap.offerBody": "NexOS estructura y ejecuta la operación completa. Paga en cuotas con tarjeta. Consulta las condiciones disponibles en el checkout.",
  "gap.cta.closed": "Grupo cerrado",
  "gap.cta.open": "Ponerlo en marcha",
  "gap.pain.course.marker": "01 / CURSOS",
  "gap.pain.course.title": "Aprendiste la estrategia. La campaña nunca salió del borrador.",
  "gap.pain.course.body": "Viste los módulos, tomaste notas y guardaste los frameworks. Pero todavía faltan la oferta, el copy, las creatividades, la página, los anuncios y alguien que lo conecte todo.",
  "gap.pain.traffic.marker": "02 / TRÁFICO PAGO",
  "gap.pain.traffic.title": "Sabes que necesitas anunciarte. Pero no puedes pagar para aprender a base de errores.",
  "gap.pain.traffic.body": "Configurar la cuenta, el píxel, la audiencia, las creatividades, el presupuesto y el remarketing al mismo tiempo convierte cada clic en un riesgo. El miedo a perder dinero puede detenerte antes de la primera prueba.",
  "gap.pain.agency.marker": "03 / AGENCIA",
  "gap.pain.agency.title": "Una agencia podría resolverlo, si una empresa que aún no lanzó pudiera pagarla.",
  "gap.pain.agency.body": "Un estratega, copywriter, diseñador, editor, gestor de anuncios y especialista en CRM cuestan antes de generar la primera venta, y aun así tendrías que coordinarlos.",
  "gap.pain.online.marker": "04 / INGRESOS ONLINE",
  "gap.pain.online.title": "Ves a personas monetizando. No ves cómo replicar la máquina.",
  "gap.pain.online.body": "Cursos, comunidades, canales, consultoría, productos digitales: el modelo parece sencillo cuando ya está listo. Detrás hay toda una operación que nadie muestra funcionando en conjunto.",
  "work.heading": "La solución no es otra clase",
  "work.title": "Tú llegas con la idea. NexOS construye y opera lo que faltaba.",
  "work.intro": "No te entregamos un plan para que lo armes por tu cuenta. Entregamos investigación, oferta, activos, infraestructura, distribución y seguimiento funcionando como una sola operación.",
  "work.offer.title": "Inteligencia de Mercado y Oferta",
  "work.offer.body": "Convierte tu idea en una oferta vendible: identifica la necesidad, estudia el mercado, analiza a la competencia y estructura la promesa, el precio, los bonos, las objeciones y los ganchos de campaña.",
  "work.video.title": "Producción de Video",
  "work.video.body": "No necesitas convertirte en editor ni montar un estudio. NexOS escribe los guiones, produce, edita y renderiza videos con grabaciones reales o producción autónoma con voz y avatares.",
  "work.landing.title": "Landing Pages y Creatividades",
  "work.landing.body": "No entregamos un wireframe. Registramos el dominio, escribimos el copy, diseñamos la página, conectamos la captura, producimos las creatividades y lo ponemos en línea.",
  "work.paid.title": "Tráfico Pago Multicanal",
  "work.paid.body": "Saca la campaña del administrador de anuncios y ponla en circulación: crea audiencias, lanza anuncios, prueba creatividades, supervisa el presupuesto y pausa lo que no responde, según tus reglas.",
  "work.organic.title": "Distribución Orgánica y Comunidades",
  "work.organic.body": "Convierte una idea en presencia continua: publica, activa, responde y modera canales y comunidades sin depender de tu energía para mantener todo el calendario.",
  "work.sales.title": "Ventas y Retención",
  "work.sales.body": "La venta no termina en el checkout. Da seguimiento a leads en el CRM, recupera compras abandonadas, recibe a los compradores, guía su onboarding, trabaja la retención y activa recomendaciones.",
  "architecture.heading": "El fin de los silos",
  "architecture.title": "Tu proyecto no se estancó por falta de potencial. Se estancó porque terminaste haciendo cinco trabajos.",
  "architecture.p1": "Deberías decidir qué quieres construir. En cambio, intentas aprender copy, diseño, edición, tráfico, automatización y ventas al mismo tiempo.",
  "architecture.p2": "El costo real no está solo en las herramientas. Está en los meses sin publicar, el anuncio que nunca se probó y la oferta que sigue dentro de un documento.",
  "architecture.p3.before": "Con NexOS, el cerebro está unificado y es ",
  "architecture.p3.emphasis": "autónomo",
  "architecture.p3.after": ".",
  "architecture.p4": "La inteligencia guía el texto. El estratega dirige la producción, publica las páginas y lleva los videos al tráfico. Toda la operación usa la misma matriz y ejecuta la campaña completa sin que tengas que intervenir en cada etapa.",
  "architecture.hint": "[ Selecciona un nodo operativo para inspeccionarlo ]",
  "architecture.label": "Arquitectura Operativa",
  "architecture.observe": "Observa",
  "architecture.decide": "Decide",
  "architecture.create": "Crea",
  "architecture.execute": "Ejecuta",
  "architecture.measure": "Mide",
  "architecture.step.niche.title": "Investigación del Nicho y Análisis de Competidores",
  "architecture.step.niche.status": "Completado",
  "architecture.step.niche.observe": "Reseñas de competidores, debates en redes sociales, tendencias de búsqueda y brechas en productos similares.",
  "architecture.step.niche.decide": "La necesidad concreta aún no resuelta y el perfil de comprador con mayor probabilidad de convertir ahora.",
  "architecture.step.niche.create": "Matrices de objeciones, informes de inteligencia de mercado y mapas de empatía operativos.",
  "architecture.step.niche.execute": "Consolida las directrices en el dossier interno y evita que los agentes partan de supuestos genéricos.",
  "architecture.step.niche.measure": "Densidad de la demanda, sofisticación del mercado y viabilidad.",
  "architecture.step.offer.title": "Definición de la Oferta y Ganchos (War Room)",
  "architecture.step.offer.status": "Completado",
  "architecture.step.offer.observe": "El dossier validado, contrastado con el historial real de campañas y los costos de adquisición anteriores.",
  "architecture.step.offer.decide": "La promesa central irresistible, bonos para elevar el ticket, anclaje de precios y ángulos de venta (ganchos).",
  "architecture.step.offer.create": "Estructuras argumentativas completas para VSL, páginas de venta y anuncios.",
  "architecture.step.offer.execute": "Deja lista la arquitectura persuasiva para materializarla en los formatos finales.",
  "architecture.step.offer.measure": "Coherencia lógica con las objeciones y alineación con la política de marca.",
  "architecture.step.creative.title": "Copy, Diseño y Renderizado Audiovisual",
  "architecture.step.creative.status": "Activo",
  "architecture.step.creative.observe": "Los ganchos definidos, la voz coherente del dossier y el paquete visual de tu empresa.",
  "architecture.step.creative.decide": "Qué formatos —estático, Reel vertical o página larga— presentan la oferta con mayor eficacia.",
  "architecture.step.creative.create": "Copy preciso, interfaces optimizadas y videos renderizados en nuestras GPU con voces clonadas o avatares.",
  "architecture.step.creative.execute": "Registra dominios, configura servidores DNS y publica la landing page sin fricción humana.",
  "architecture.step.creative.measure": "Velocidad de la página (LCP), cohesión visual y retención estimada.",
  "architecture.step.distribution.title": "Distribución Orgánica y Comunidades",
  "architecture.step.distribution.status": "Activo",
  "architecture.step.distribution.observe": "Picos de interacción del nicho, algoritmos de distribución e interacciones pendientes en las comunidades.",
  "architecture.step.distribution.decide": "El orden de publicación, las respuestas adecuadas por mensaje directo y cómo moderar la activación de un grupo.",
  "architecture.step.distribution.create": "Descripciones precisas, interacciones de moderación en WhatsApp/Telegram y alertas automáticas.",
  "architecture.step.distribution.execute": "Publica en todas las redes orgánicas conectadas en los horarios establecidos.",
  "architecture.step.distribution.measure": "Crecimiento de la audiencia, tasa de respuestas orgánicas y retención en los grupos de lanzamiento.",
  "architecture.step.ads.title": "Operación de Tráfico Pago",
  "architecture.step.ads.status": "Activo",
  "architecture.step.ads.observe": "Las creatividades recién producidas, la landing activa, las audiencias del píxel y las reglas del presupuesto diario.",
  "architecture.step.ads.decide": "Dónde probar primero el presupuesto (CBO/ABO), cuándo pausar creatividades desgastadas y cómo reasignar pujas.",
  "architecture.step.ads.create": "Estructuras completas de campaña en las plataformas publicitarias más rentables para la oferta.",
  "architecture.step.ads.execute": "Activa publicaciones patrocinadas vinculadas a tu tarjeta en redes de búsqueda y sociales.",
  "architecture.step.ads.measure": "CPA real, ROAS, desgaste creativo y CTR cruzado en los paneles oficiales.",
  "architecture.step.crm.title": "Ventas, Retención y Onboarding",
  "architecture.step.crm.status": "Activo",
  "architecture.step.crm.observe": "Leads activos, eventos de abandono del carrito, compras confirmadas y conversaciones interrumpidas.",
  "architecture.step.crm.decide": "El momento exacto para hacer seguimiento, resolver la objeción pendiente o dar una bienvenida VIP.",
  "architecture.step.crm.create": "Flujos de email marketing, envíos por WhatsApp y alertas de alta prioridad.",
  "architecture.step.crm.execute": "Envía comunicaciones individuales a tu audiencia y sostiene el valor de vida del cliente a largo plazo.",
  "architecture.step.crm.measure": "Tasa de recuperación, churn, interacción con el onboarding y ventas cruzadas.",
  "governance.heading": "Gobernanza Integrada",
  "governance.authorization.title": "Autorización Estricta",
  "governance.authorization.body": "Las acciones externas —publicar posts, lanzar campañas de tráfico y enviar emails— solo ocurren con tu aprobación o dentro de los límites que establezcas.",
  "governance.workspaces.title": "Espacios de Trabajo Aislados",
  "governance.workspaces.body": "Separa productos y servicios de una misma empresa o mantén aislados los clientes de una agencia. Los datos, la inteligencia y las estrategias nunca se mezclan.",
  "governance.metrics.title": "Métricas Reales. Punto.",
  "governance.metrics.body": "El sistema se basa en datos empíricos extraídos directamente de canales reales de tráfico y de tu CRM. Ninguna IA inventa cifras de conversión para que el panel parezca completo.",
  "proof.heading": "Lógica de Ejecución y Coherencia",
  "proof.title": "Cómo evitamos que la autonomía cree un Frankenstein de IA genérica.",
  "proof.brain.title": "1. Un Solo Cerebro (Dossier)",
  "proof.brain.body": "Los modelos superficiales cometen errores lógicos y generan contradicciones extrañas. NexOS lo resuelve creando un dossier maestro e inmutable para cada campaña. El mismo archivo de reglas guía al guionista de video, al copywriter y el tono de los anuncios, y evita resultados genéricos.",
  "proof.safety.title": "2. Autonomía con Bloqueo de Seguridad",
  "proof.safety.body": "Puedes automatizar la publicación por completo o exigir revisión. NexOS diseña la página, edita los videos, formatea los anuncios y prepara las publicaciones. Se publican y el dominio se registra cuando das tu aprobación, sin exigirte el trabajo manual de montar cada pieza en una herramienta.",
  "proof.decisions.title": "3. Menos Decisiones Equivocadas",
  "proof.decisions.body": "La IA tradicional falla cuando no ve el panorama completo. Cuando la agencia autónoma detecta que una creatividad se agotó y la pausa en las redes, ya cruzó el CTR de clics reales con las conversiones de tu CRM. No toma decisiones superficiales sin contrastar datos empíricos.",
  "proof.memory.title": "4. Memoria Institucional Activa",
  "proof.memory.body": "El trabajo repetitivo aparece cuando la IA pierde el contexto. NexOS guarda aciertos, errores y aprendizajes. Los errores y objeciones que no funcionaron el mes pasado ya se convierten en reglas permanentes para la campaña actual.",
  "scarcity.title": "Solo 100 Operaciones en el Lanzamiento.",
  "scarcity.body": "Si el costo y la complejidad de montar una agencia completa te han frenado, esta apertura está pensada para eliminar esa barrera: ejecución de principio a fin y pago en cuotas con tarjeta. Revisa las opciones y elige las mejores condiciones en el checkout. El acceso inicial es limitado. No hay excepciones.",
  "scarcity.cta.closed": "Grupo Cerrado",
  "scarcity.cta.open": "Reservar Mi Lugar Ahora",
  "scarcity.status.closed": "Se han ocupado todos los lugares.",
  "scarcity.status.open": "El orden de reserva define la prioridad de activación.",
  "scarcity.credibility": "Esta landing page fue creada y publicada por los agentes de NexOS.",
  "scarcity.community": "Únete a la lista y accede a nuestro grupo para ver la operación entre bastidores.",
  "footer.terms": "Términos de Uso",
  "footer.privacy": "Privacidad",
  "footer.deletion": "Eliminación de Datos",
  "footer.signature": "Operación Centralizada.",
  "glp.heading": "El Método GLP22",
  "glp.title.before": "La Ingeniería de una",
  "glp.title.accent": "Operación Autónoma.",
  "glp.intro1": "No es un paquete de herramientas. Es un flujo continuo de 22 capacidades interdependientes, desde la primera idea hasta la escala de ventas.",
  "glp.intro2": "Cada etapa impulsa la siguiente. El estratega guía el copy, el copy orienta el diseño y el diseño alimenta el tráfico. Una inteligencia central coordina todo, sin brechas de ejecución.",
  "glp.phase.strategy.label": "Fase 01",
  "glp.phase.strategy.name": "Estrategia y Fundamentos",
  "glp.phase.strategy.title": "Donde termina la intuición y comienza la inteligencia de mercado.",
  "glp.phase.strategy.item.01.title": "Inmersión e intake",
  "glp.phase.strategy.item.01.desc": "Recopilación profunda de tu visión, objetivos y restricciones para guiar la operación sin recurrir a supuestos genéricos.",
  "glp.phase.strategy.item.02.title": "Inteligencia y análisis de mercado",
  "glp.phase.strategy.item.02.desc": "Mapeo activo de la competencia y del entorno competitivo para encontrar brechas de atención, demandas ocultas y patrones de mercado.",
  "glp.phase.strategy.item.03.title": "Avatar, segmentación y recorrido",
  "glp.phase.strategy.item.03.desc": "Definición clara del cliente ideal y del camino exacto desde el primer contacto hasta la decisión.",
  "glp.phase.strategy.item.04.title": "Posicionamiento, mecanismo y narrativa",
  "glp.phase.strategy.item.04.desc": "Construcción de una tesis única y un argumento central que diferencien tu mensaje de las ofertas genéricas del nicho.",
  "glp.phase.strategy.item.05.title": "Ingeniería de la oferta",
  "glp.phase.strategy.item.05.desc": "Estructuración del precio, anclaje, respuesta a objeciones, garantías y bonos para crear una propuesta comercial sólida.",
  "glp.phase.strategy.item.06.title": "Arquitectura estratégica del lanzamiento",
  "glp.phase.strategy.item.06.desc": "Diseño del formato y modelo de ventas más adecuados, con cronograma, eventos y puntos de contacto de la campaña.",
  "glp.phase.strategy.item.07.title": "Master Plan",
  "glp.phase.strategy.item.07.desc": "Consolidación de todas las directrices en un documento maestro para alinear la ejecución autónoma con el mismo objetivo.",
  "glp.phase.creation.label": "Fase 02",
  "glp.phase.creation.name": "Creación y Activos Visuales",
  "glp.phase.creation.title": "De la arquitectura conceptual a interfaces y guiones orientados a la conversión.",
  "glp.phase.creation.item.08.title": "Construcción del embudo",
  "glp.phase.creation.item.08.desc": "Diseño práctico de la estructura de adquisición y calificación, conectando de forma fluida los pasos del recorrido de compra.",
  "glp.phase.creation.item.09.title": "Copywriting",
  "glp.phase.creation.item.09.desc": "Redacción persuasiva de cartas de venta, anuncios y guiones visuales, respetando el tono definido en el Master Plan.",
  "glp.phase.creation.item.10.title": "Dirección creativa y producción visual",
  "glp.phase.creation.item.10.desc": "Desarrollo de la identidad visual de la campaña y adaptación a piezas gráficas y banners consistentes en todos los canales.",
  "glp.phase.creation.item.11.title": "Dirección y producción de video",
  "glp.phase.creation.item.11.desc": "Guion y renderizado dinámico de VSL, anuncios y contenido audiovisual diseñado para retener la atención en los segundos clave.",
  "glp.phase.creation.item.12.title": "Páginas y activos digitales",
  "glp.phase.creation.item.12.desc": "Implementación de landing pages pensadas para convertir y cargar rápido, listas para recibir tráfico.",
  "glp.phase.infrastructure.label": "Fase 03",
  "glp.phase.infrastructure.name": "Infraestructura e Interacción",
  "glp.phase.infrastructure.title": "Sistemas técnicos, gestión de audiencia y comunicación orgánica.",
  "glp.phase.infrastructure.item.13.title": "Infraestructura, tracking e integraciones",
  "glp.phase.infrastructure.item.13.desc": "Configuración técnica de píxeles, etiquetas y flujos de datos, además de apoyo con dominios y hosting (servicios facturados directamente por los proveedores que elijas).",
  "glp.phase.infrastructure.item.14.title": "CRM, gestión de leads, grupos y comunidades",
  "glp.phase.infrastructure.item.14.desc": "Organización de las bases de contactos y de espacios de activación para centralizar la comunicación con las personas interesadas.",
  "glp.phase.infrastructure.item.15.title": "Presencia digital y audiencia",
  "glp.phase.infrastructure.item.15.desc": "Programación y control de publicaciones para mantener la constancia en perfiles sociales y aprovechar los algoritmos de descubrimiento.",
  "glp.phase.infrastructure.item.16.title": "Email, mensajes y nutrición",
  "glp.phase.infrastructure.item.16.desc": "Desarrollo de secuencias de comunicación activa y flujos automatizados para elevar el nivel de conciencia de los leads.",
  "glp.phase.sales.label": "Fase 04",
  "glp.phase.sales.name": "Adquisición y Ventas",
  "glp.phase.sales.title": "Generación de tráfico, coordinación y recuperación de ingresos.",
  "glp.phase.sales.item.17.title": "Medios pagados",
  "glp.phase.sales.item.17.desc": "Planificación y gestión de campañas publicitarias, distribuyendo el presupuesto entre las creatividades y audiencias con mejor costo por adquisición.",
  "glp.phase.sales.item.18.title": "Ejecución coordinada del lanzamiento",
  "glp.phase.sales.item.18.desc": "Sincronización de canales, emails, grupos y anuncios en los días clave de la campaña para alinear la apertura del carrito.",
  "glp.phase.sales.item.19.title": "Atención, ventas y conversión",
  "glp.phase.sales.item.19.desc": "Recuperación de recibos de pago/Pix y carritos abandonados, además de resolver objeciones de último momento para maximizar los ingresos aprobados.",
  "glp.phase.continuity.label": "Fase 05",
  "glp.phase.continuity.name": "Datos y Continuidad",
  "glp.phase.continuity.title": "Lectura de métricas, aprendizaje institucional y próximos pasos.",
  "glp.phase.continuity.item.20.title": "Monitoreo y optimización",
  "glp.phase.continuity.item.20.desc": "Seguimiento y lectura continua de métricas reales para ajustar y proteger el presupuesto durante la campaña.",
  "glp.phase.continuity.item.21.title": "Poslanzamiento y aprendizaje",
  "glp.phase.continuity.item.21.desc": "Consolidación de los datos de rendimiento en inteligencia institucional, registrando lo que mejor convirtió e identificando nuevas objeciones.",
  "glp.phase.continuity.item.22.title": "Continuidad, relanzamiento y evergreen",
  "glp.phase.continuity.item.22.desc": "Transformación de la inteligencia acumulada en nuevos embudos de venta y adaptación del producto para campañas sucesivas o recurrentes.",
};

const copyByLanguage: Record<Lang, Record<HomeTextKey, string>> = {
  "pt-BR": pt,
  "en-US": en,
  "es-LA": es,
};

export function homeText(lang: Lang, key: HomeTextKey): string {
  return copyByLanguage[lang][key];
}